// Settings labels for all languages (English, Urdu, Urdu/English)
export const settingsLabels = {
  en: {
    // General
    settings: "Settings",
    save: "Save",
    cancel: "Cancel",
    back: "Back",
    
    // Tabs
    shop: "Shop",
    printer: "Printer",
    camera: "Camera",
    language: "Language",
    modules: "Modules",
    theme: "Theme",
    paymentMethods: "Payment Methods",
    profile: "Profile",
    backup: "Backup",
    permissionPassword: "Permission Password",
    
    // Shop Settings
    shopName: "Shop Name",
    shopImage: "Shop Image",
    uploadImage: "Upload Image",
    changeImage: "Change Image",
    enterShopName: "Enter shop name",
    
    // Printer Settings
    printerHeight: "Printer Height (mm)",
    printerWidth: "Printer Width (mm)",
    printMode: "Print Mode",
    thermal: "Thermal",
    normal: "Normal",
    
    // Camera Settings
    selectCamera: "Select Camera",
    availableCameras: "Available Cameras",
    noCamerasFound: "No cameras found",
    scanCameras: "Scan Cameras",
    
    // Language Settings
    selectLanguage: "Select Language",
    english: "English",
    urdu: "Urdu",
    urduEnglish: "Urdu/English",
    
    // Module Settings
    moduleVisibility: "Module Visibility",
    enterPassword: "Enter Password",
    unlock: "Unlock",
    incorrectPassword: "Incorrect Password",
    dashboard: "Dashboard",
    pos: "POS",
    products: "Products",
    purchases: "Purchases",
    sales: "Sales",
    customers: "Customers",
    suppliers: "Suppliers",
    expenses: "Expenses",
    reports: "Reports",
    accounts: "Accounts",
    qarza: "Qarza",
    staff: "Staff",
    wastage: "Wastage",
    
    // Profile Settings
    profileSettings: "Profile Settings",
    name: "Name",
    email: "Email",
    phone: "Phone",
    role: "Role",
    updateProfile: "Update Profile",
    
    // Messages
    shopSettingsSaved: "Shop settings saved successfully",
    printerSettingsSaved: "Printer settings saved successfully",
    cameraSettingsSaved: "Camera settings saved successfully",
    languageSettingsSaved: "Language settings saved successfully",
    moduleSettingsSaved: "Module settings saved successfully",
    profileUpdated: "Profile updated successfully",
    failedToSave: "Failed to save settings",
    moduleSettingsUnlocked: "Module settings unlocked",
    
    // Theme Settings
    themeBuilder: "Theme Builder",
    themeBuilderDescription: "Choose a preset, customize colors, and save your active application theme.",
    presetThemes: "Preset Themes",
    customThemeEditor: "Custom Theme Editor",
    customThemeEditorDescription: "This section is password protected. Enter the password to unlock custom theme editing.",
    unlockPassword: "Unlock password",
    enterPassword: "Enter password",
    unlock: "Unlock",
    clear: "Clear",
    customEditingUnlocked: "Custom editing unlocked. Change colors below and save to persist.",
    themeName: "Theme name",
    customTheme: "Custom Theme",
    resetPreset: "Reset preset",
    saveTheme: "Save Theme",
    saving: "Saving...",
    resetToDefault: "Reset to the default theme preview. Save to persist.",
    themeSelected: "selected. Saving active theme...",
    themeSelectedSaved: "selected and saved as active theme.",
    themeSelectedFailed: "selected. Unable to save active theme. Please save manually.",
    themeSaved: "Theme saved and applied successfully.",
    themeUpdateFailed: "Theme update failed.",
    incorrectPassword: "Incorrect password. Try again.",
    customThemeUnlocked: "Custom theme editor unlocked.",
    preset: "Preset",
    
    // Backup Settings
    backupAndSync: "Backup & Sync Settings",
    backupAndSyncDescription: "Manage online database backup and synchronization",
    onlineSync: "Online Sync",
    onlineSyncDescription: "Cloud storage and synchronization status",
    storageUsage: "Storage Usage",
    used: "Used",
    total: "Total",
    remaining: "Remaining",
    syncAllData: "Sync All Data",
    syncRequiredOnly: "Sync Required Only",
    stopSync: "Stop Sync",
    lastSynced: "Last synced",
    autoSyncInterval: "Auto Sync Interval",
    autoSyncIntervalDescription: "Configure automatic backup synchronization",
    syncFrequency: "Sync Frequency",
    enterValue: "Enter value",
    set: "Set",
    autoSyncActive: "Auto-sync is active. Data will sync every",
    autoSyncDisabled: "Auto-sync is disabled. Manual sync only.",
    aboutBackupSync: "About Backup & Sync",
    syncAllDescription: "Uploads complete database to cloud storage",
    syncRequiredDescription: "Only uploads changed/modified data",
    autoSyncDescription: "Automatically syncs at configured intervals",
    storageUsageDescription: "Storage usage shows cloud database space utilization",
    minutes: "Minutes",
    hours: "Hours",
    days: "Days",
    second: "second",
    minute: "minute",
    hour: "hour",
    day: "day",
    excelBackup: "Excel Backup",
    excelBackupDescription: "Export all database data to Excel file",
    excelBackupPath: "Excel Backup Path",
    enterExcelBackupPath: "Enter Excel backup path",
    exportExcel: "Export Excel",
    exporting: "Exporting...",
    excelExportSuccess: "Excel export completed successfully",
    excelExportFailed: "Excel export failed",
    
    // Permission Password Settings
    permissionPasswordSettings: "Permission Password Settings",
    permissionPasswordDescription: "Set a password to protect sensitive operations",
    permissionPassword: "Permission Password",
    enterPermissionPassword: "Enter permission password",
    passwordRequired: "Permission password is required",
    failedToFetchPassword: "Failed to fetch current password",
    passwordSaved: "Permission password saved successfully",
    failedToSavePassword: "Failed to save permission password",
    passwordDescription: "This password is used to authorize sensitive operations. Only visible to admin users.",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    
    // Payment Methods Settings
    paymentMethodsSettings: "Payment Methods Settings",
    paymentMethodsDescription: "Configure available payment methods for your shop",
    addPaymentMethod: "Add Payment Method",
    editPaymentMethod: "Edit Payment Method",
    paymentMethodName: "Payment Method Name",
    enterPaymentMethodName: "Enter payment method name",
    paymentMethodNameRequired: "Payment method name is required",
    paymentMethodPlaceholder: "e.g., Cash, Bank Transfer, JazzCash",
    paymentMethodType: "Payment Method Type",
    cash: "Cash",
    card: "Card",
    bankTransfer: "Bank Transfer",
    other: "Other",
    savePaymentMethod: "Save Payment Method",
    deletePaymentMethod: "Delete Payment Method",
    paymentMethodAdded: "Payment method added successfully",
    paymentMethodDeleted: "Payment method deleted successfully",
    paymentMethodFailed: "Payment method operation failed",
    loading: "Loading...",
    name: "Name",
    status: "Status",
    actions: "Actions",
    active: "Active",
    inactive: "Inactive",
    noPaymentMethods: "No payment methods found",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    saving: "Saving...",
    add: "Add",
    update: "Update",
  },
  ur: {
    // General
    settings: "سیٹنگز",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    back: "واپس",
    
    // Tabs
    shop: "دکان",
    printer: "پرنٹر",
    camera: "کیمرا",
    language: "زبان",
    modules: "ماڈیولز",
    theme: "تھیم",
    paymentMethods: "ادائیگی کے طریقے",
    profile: "پروفائل",
    backup: "بیک اپ",
    permissionPassword: "اجازت پاس ورڈ",
    
    // Shop Settings
    shopName: "دکان کا نام",
    shopImage: "دکان کی تصویر",
    uploadImage: "تصویر اپ لوڈ کریں",
    changeImage: "تصویر تبدیل کریں",
    enterShopName: "دکان کا نام درج کریں",
    
    // Printer Settings
    printerHeight: "پرنٹر کی اونچائی (ملی میٹر)",
    printerWidth: "پرنٹر کی چوڑائی (ملی میٹر)",
    printMode: "پرنٹ موڈ",
    thermal: "تھرمل",
    normal: "عام",
    
    // Camera Settings
    selectCamera: "کیمرا منتخب کریں",
    availableCameras: "دستیاب کیمرے",
    noCamerasFound: "کوئی کیمرا نہیں ملا",
    scanCameras: "کیمرے اسکین کریں",
    
    // Language Settings
    selectLanguage: "زبان منتخب کریں",
    english: "انگریزی",
    urdu: "اردو",
    urduEnglish: "اردو/انگریزی",
    
    // Module Settings
    moduleVisibility: "ماڈیول کی نظر",
    enterPassword: "پاس ورڈ درج کریں",
    unlock: "کھولیں",
    incorrectPassword: "غلط پاس ورڈ",
    dashboard: "ڈیش بورڈ",
    pos: "POS",
    products: "پروڈکٹس",
    purchases: "خریداریاں",
    sales: "فروخت",
    customers: "صارفین",
    suppliers: "فراہم کنندگان",
    expenses: "خرچے",
    reports: "رپورٹس",
    accounts: "اکاؤنٹس",
    qarza: "قرضہ",
    staff: "اسٹاف",
    wastage: "ضیاع",
    
    // Profile Settings
    profileSettings: "پروفائل سیٹنگز",
    name: "نام",
    email: "ای میل",
    phone: "فون",
    role: "کردار",
    updateProfile: "پروفائل اپ ڈیٹ کریں",
    
    // Messages
    shopSettingsSaved: "دکان کی سیٹنگز کامیابی سے محفوظ ہو گئیں",
    printerSettingsSaved: "پرنٹر سیٹنگز کامیابی سے محفوظ ہو گئیں",
    cameraSettingsSaved: "کیمرا سیٹنگز کامیابی سے محفوظ ہو گئیں",
    languageSettingsSaved: "زبان کی سیٹنگز کامیابی سے محفوظ ہو گئیں",
    moduleSettingsSaved: "ماڈیول سیٹنگز کامیابی سے محفوظ ہو گئیں",
    profileUpdated: "پروفائل کامیابی سے اپ ڈیٹ ہو گئی",
    failedToSave: "سیٹنگز محفوظ کرنے میں ناکامی",
    moduleSettingsUnlocked: "ماڈیول سیٹنگز کھول دی گئیں",
    
    // Theme Settings
    themeBuilder: "تھیم بلڈر",
    themeBuilderDescription: "پری سیٹ منتخب کریں، رنگوں کو کسٹمائز کریں، اور اپنی ایپلیکیشن کا تھیم محفوظ کریں۔",
    presetThemes: "پری سیٹ تھیمز",
    customThemeEditor: "کسٹم تھیم ایڈیٹر",
    customThemeEditorDescription: "یہ سیکشن پاس ورڈ سے محفوظ ہے۔ کسٹم تھیم ایڈیٹنگ کو انلاک کرنے کے لیے پاس ورڈ درج کریں۔",
    unlockPassword: "انلاک پاس ورڈ",
    enterPassword: "پاس ورڈ درج کریں",
    unlock: "انلاک",
    clear: "صاف کریں",
    customEditingUnlocked: "کسٹم ایڈیٹنگ انلاک ہو گئی۔ نیچے رنگ تبدیل کریں اور محفوظ کرنے کے لیے محفوظ کریں۔",
    themeName: "تھیم کا نام",
    customTheme: "کسٹم تھیم",
    resetPreset: "پری سیٹ ری سیٹ کریں",
    saveTheme: "تھیم محفوظ کریں",
    saving: "محفوظ کر رہا ہے...",
    resetToDefault: "ڈیفالٹ تھیم پر ری سیٹ کریں۔ محفوظ کرنے کے لیے محفوظ کریں۔",
    themeSelected: "منتخب ہوا۔ ایکٹو تھیم محفوظ کر رہا ہے...",
    themeSelectedSaved: "منتخب ہوا اور ایکٹو تھیم کے طور پر محفوظ ہوا۔",
    themeSelectedFailed: "منتخب ہوا۔ ایکٹو تھیم محفوظ کرنے میں ناکامی۔ دستی طور پر محفوظ کریں۔",
    themeSaved: "تھیم کامیابی سے محفوظ اور اپلائی ہوا۔",
    themeUpdateFailed: "تھیم اپ ڈیٹ ناکام ہوا۔",
    incorrectPassword: "غلط پاس ورڈ۔ دوبارہ کوشش کریں۔",
    customThemeUnlocked: "کسٹم تھیم ایڈیٹر انلاک ہو گیا۔",
    preset: "پری سیٹ",
    
    // Backup Settings
    backupAndSync: "بیک اپ اور سنکرونائزیشن سیٹنگز",
    backupAndSyncDescription: "آن لائن ڈیٹا بیس بیک اپ اور سنکرونائزیشن کا انتظام کریں",
    onlineSync: "آن لائن سنک",
    onlineSyncDescription: "کلاؤڈ اسٹوریج اور سنکرونائزیشن کی حیثیت",
    storageUsage: "اسٹوریج استعمال",
    used: "استعمال شدہ",
    total: "کل",
    remaining: "باقی",
    syncAllData: "تمام ڈیٹا سنک کریں",
    syncRequiredOnly: "صرف ضروری سنک کریں",
    stopSync: "سنک روکیں",
    lastSynced: "آخری سنک",
    autoSyncInterval: "آٹو سنک انٹروال",
    autoSyncIntervalDescription: "آٹومیٹک بیک اپ سنکرونائزیشن کنفیگر کریں",
    syncFrequency: "سنک فریکوئنسی",
    enterValue: "ویلیو درج کریں",
    set: "سیٹ",
    autoSyncActive: "آٹو سنک ایکٹیو ہے۔ ڈیٹا ہر سنک ہوگا",
    autoSyncDisabled: "آٹو سنک غیر فعال ہے۔ صرف دستی سنک۔",
    aboutBackupSync: "بیک اپ اور سنک کے بارے میں",
    syncAllDescription: "مکمل ڈیٹا بیس کو کلاؤڈ اسٹوریج میں اپ لوڈ کرتا ہے",
    syncRequiredDescription: "صرف تبدیل شدہ/ترمیم شدہ ڈیٹا اپ لوڈ کرتا ہے",
    autoSyncDescription: "کنفیگر شدہ انٹروالز پر خود بخود سنک کرتا ہے",
    storageUsageDescription: "اسٹوریج استعمال کلاؤڈ ڈیٹا بیس اسپیس یوٹیلیزیشن دکھاتا ہے",
    minutes: "منٹس",
    hours: "گھنٹے",
    days: "دن",
    second: "سیکنڈ",
    minute: "منٹ",
    hour: "گھنٹا",
    day: "دن",
    excelBackup: "ایکسل بیک اپ",
    excelBackupDescription: "تمام ڈیٹا بیس ڈیٹا کو ایکسل فائل میں ایکسپورٹ کریں",
    excelBackupPath: "ایکسل بیک اپ پاتھ",
    enterExcelBackupPath: "ایکسل بیک اپ پاتھ درج کریں",
    exportExcel: "ایکسل ایکسپورٹ",
    exporting: "ایکسپورٹ ہو رہا ہے...",
    excelExportSuccess: "ایکسل ایکسپورت کامیابی سے مکمل ہوا",
    excelExportFailed: "ایکسل ایکسپورت ناکام ہوا",
    
    // Permission Password Settings
    permissionPasswordSettings: "اجازت پاس ورڈ سیٹنگز",
    permissionPasswordDescription: "حساس آپریشنز کو محفوظ کرنے کے لیے پاس ورڈ سیٹ کریں",
    permissionPassword: "اجازت پاس ورڈ",
    enterPermissionPassword: "اجازت پاس ورڈ درج کریں",
    passwordRequired: "اجازت پاس ورڈ ضروری ہے",
    failedToFetchPassword: "موجودہ پاس ورڈ حاصل کرنے میں ناکامی",
    passwordSaved: "اجازت پاس ورڈ کامیابی سے محفوظ ہوا",
    failedToSavePassword: "اجازت پاس ورڈ محفوظ کرنے میں ناکامی",
    passwordDescription: "یہ پاس ورڈ حساس آپریشنز کو اجازت دینے کے لیے استعمال ہوتا ہے۔ صرف ایڈمن صارفین کے لیے نظر آتا ہے۔",
    edit: "ایڈٹ",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    
    // Payment Methods Settings
    paymentMethodsSettings: "ادائیگی کے طریقوں کی سیٹنگز",
    paymentMethodsDescription: "اپنے دکان کے لیے دستیاب ادائیگی کے طریقوں کو کنفیگر کریں",
    addPaymentMethod: "ادائیگی کا طریقہ شامل کریں",
    editPaymentMethod: "ادائیگی کا طریقہ ایڈٹ کریں",
    paymentMethodName: "ادائیگی کا طریقہ نام",
    enterPaymentMethodName: "ادائیگی کا طریقہ نام درج کریں",
    paymentMethodNameRequired: "ادائیگی کا طریقہ نام ضروری ہے",
    paymentMethodPlaceholder: "مثال: نقد، بینک ٹرانسفر، جاز کیش",
    paymentMethodType: "ادائیگی کا طریقہ ٹائپ",
    cash: "نقد",
    card: "کارڈ",
    bankTransfer: "بینک ٹرانسفر",
    other: "دیگر",
    savePaymentMethod: "ادائیگی کا طریقہ محفوظ کریں",
    deletePaymentMethod: "ادائیگی کا طریقہ حذف کریں",
    paymentMethodAdded: "ادائیگی کا طریقہ کامیابی سے شامل ہوا",
    paymentMethodDeleted: "ادائیگی کا طریقہ کامیابی سے حذف ہوا",
    paymentMethodFailed: "ادائیگی کا طریقہ آپریشن ناکام ہوا",
    loading: "لوڈ ہو رہا ہے...",
    name: "نام",
    status: "حیثیت",
    actions: "ایکشنز",
    active: "ایکٹو",
    inactive: "ان ایکٹو",
    noPaymentMethods: "کوئی ادائیگی کا طریقہ نہیں ملا",
    edit: "ایڈٹ",
    delete: "حذف کریں",
    cancel: "منسوخ کریں",
    saving: "محفوظ کر رہا ہے...",
    add: "شامل کریں",
    update: "اپ ڈیٹ کریں",
  },
  ur_en: {
    // General
    settings: "سیٹنگز / Settings",
    save: "محفوظ کریں / Save",
    cancel: "منسوخ کریں / Cancel",
    back: "واپس / Back",
    
    // Tabs
    shop: "دکان / Shop",
    printer: "پرنٹر / Printer",
    camera: "کیمرا / Camera",
    language: "زبان / Language",
    modules: "ماڈیولز / Modules",
    theme: "تھیم / Theme",
    paymentMethods: "ادائیگی کے طریقے / Payment Methods",
    profile: "پروفائل / Profile",
    backup: "بیک اپ / Backup",
    permissionPassword: "اجازت پاس ورڈ / Permission Password",
    
    // Shop Settings
    shopName: "دکان کا نام / Shop Name",
    shopImage: "دکان کی تصویر / Shop Image",
    uploadImage: "تصویر اپ لوڈ کریں / Upload Image",
    changeImage: "تصویر تبدیل کریں / Change Image",
    enterShopName: "دکان کا نام درج کریں / Enter shop name",
    
    // Printer Settings
    printerHeight: "پرنٹر کی اونچائی (ملی میٹر) / Printer Height (mm)",
    printerWidth: "پرنٹر کی چوڑائی (ملی میٹر) / Printer Width (mm)",
    printMode: "پرنٹ موڈ / Print Mode",
    thermal: "تھرمل / Thermal",
    normal: "عام / Normal",
    
    // Camera Settings
    selectCamera: "کیمرا منتخب کریں / Select Camera",
    availableCameras: "دستیاب کیمرے / Available Cameras",
    noCamerasFound: "کوئی کیمرا نہیں ملا / No cameras found",
    scanCameras: "کیمرے اسکین کریں / Scan Cameras",
    
    // Language Settings
    selectLanguage: "زبان منتخب کریں / Select Language",
    english: "انگریزی / English",
    urdu: "اردو / Urdu",
    urduEnglish: "اردو/انگریزی / Urdu/English",
    
    // Module Settings
    moduleVisibility: "ماڈیول کی نظر / Module Visibility",
    enterPassword: "پاس ورڈ درج کریں / Enter Password",
    unlock: "کھولیں / Unlock",
    incorrectPassword: "غلط پاس ورڈ / Incorrect Password",
    dashboard: "ڈیش بورڈ / Dashboard",
    pos: "POS",
    products: "پروڈکٹس / Products",
    purchases: "خریداریاں / Purchases",
    sales: "فروخت / Sales",
    customers: "صارفین / Customers",
    suppliers: "فراہم کنندگان / Suppliers",
    expenses: "خرچے / Expenses",
    reports: "رپورٹس / Reports",
    accounts: "اکاؤنٹس / Accounts",
    qarza: "قرضہ / Qarza",
    staff: "اسٹاف / Staff",
    wastage: "ضیاع / Wastage",
    
    // Profile Settings
    profileSettings: "پروفائل سیٹنگز / Profile Settings",
    name: "نام / Name",
    email: "ای میل / Email",
    phone: "فون / Phone",
    role: "کردار / Role",
    updateProfile: "پروفائل اپ ڈیٹ کریں / Update Profile",
    
    // Messages
    shopSettingsSaved: "دکان کی سیٹنگز کامیابی سے محفوظ ہو گئیں / Shop settings saved successfully",
    printerSettingsSaved: "پرنٹر سیٹنگز کامیابی سے محفوظ ہو گئیں / Printer settings saved successfully",
    cameraSettingsSaved: "کیمرا سیٹنگز کامیابی سے محفوظ ہو گئیں / Camera settings saved successfully",
    languageSettingsSaved: "زبان کی سیٹنگز کامیابی سے محفوظ ہو گئیں / Language settings saved successfully",
    moduleSettingsSaved: "ماڈیول سیٹنگز کامیابی سے محفوظ ہو گئیں / Module settings saved successfully",
    profileUpdated: "پروفائل کامیابی سے اپ ڈیٹ ہو گئی / Profile updated successfully",
    failedToSave: "سیٹنگز محفوظ کرنے میں ناکامی / Failed to save settings",
    moduleSettingsUnlocked: "ماڈیول سیٹنگز کھول دی گئیں / Module settings unlocked",
    
    // Theme Settings
    themeBuilder: "تھیم بلڈر / Theme Builder",
    themeBuilderDescription: "پری سیٹ منتخب کریں، رنگوں کو کسٹمائز کریں، اور اپنی ایپلیکیشن کا تھیم محفوظ کریں۔ / Choose a preset, customize colors, and save your active application theme.",
    presetThemes: "پری سیٹ تھیمز / Preset Themes",
    customThemeEditor: "کسٹم تھیم ایڈیٹر / Custom Theme Editor",
    customThemeEditorDescription: "یہ سیکشن پاس ورڈ سے محفوظ ہے۔ کسٹم تھیم ایڈیٹنگ کو انلاک کرنے کے لیے پاس ورڈ درج کریں۔ / This section is password protected. Enter the password to unlock custom theme editing.",
    unlockPassword: "انلاک پاس ورڈ / Unlock password",
    enterPassword: "پاس ورڈ درج کریں / Enter password",
    unlock: "انلاک / Unlock",
    clear: "صاف کریں / Clear",
    customEditingUnlocked: "کسٹم ایڈیٹنگ انلاک ہو گئی۔ نیچے رنگ تبدیل کریں اور محفوظ کرنے کے لیے محفوظ کریں۔ / Custom editing unlocked. Change colors below and save to persist.",
    themeName: "تھیم کا نام / Theme name",
    customTheme: "کسٹم تھیم / Custom Theme",
    resetPreset: "پری سیٹ ری سیٹ کریں / Reset preset",
    saveTheme: "تھیم محفوظ کریں / Save Theme",
    saving: "محفوظ کر رہا ہے... / Saving...",
    resetToDefault: "ڈیفالٹ تھیم پر ری سیٹ کریں۔ محفوظ کرنے کے لیے محفوظ کریں۔ / Reset to the default theme preview. Save to persist.",
    themeSelected: "منتخب ہوا۔ ایکٹو تھیم محفوظ کر رہا ہے... / selected. Saving active theme...",
    themeSelectedSaved: "منتخب ہوا اور ایکٹو تھیم کے طور پر محفوظ ہوا۔ / selected and saved as active theme.",
    themeSelectedFailed: "منتخب ہوا۔ ایکٹو تھیم محفوظ کرنے میں ناکامی۔ دستی طور پر محفوظ کریں۔ / selected. Unable to save active theme. Please save manually.",
    themeSaved: "تھیم کامیابی سے محفوظ اور اپلائی ہوا۔ / Theme saved and applied successfully.",
    themeUpdateFailed: "تھیم اپ ڈیٹ ناکام ہوا۔ / Theme update failed.",
    incorrectPassword: "غلط پاس ورڈ۔ دوبارہ کوشش کریں۔ / Incorrect password. Try again.",
    customThemeUnlocked: "کسٹم تھیم ایڈیٹر انلاک ہو گیا۔ / Custom theme editor unlocked.",
    preset: "پری سیٹ / Preset",
    
    // Backup Settings
    backupAndSync: "بیک اپ اور سنکرونائزیشن سیٹنگز / Backup & Sync Settings",
    backupAndSyncDescription: "آن لائن ڈیٹا بیس بیک اپ اور سنکرونائزیشن کا انتظام کریں / Manage online database backup and synchronization",
    onlineSync: "آن لائن سنک / Online Sync",
    onlineSyncDescription: "کلاؤڈ اسٹوریج اور سنکرونائزیشن کی حیثیت / Cloud storage and synchronization status",
    storageUsage: "اسٹوریج استعمال / Storage Usage",
    used: "استعمال شدہ / Used",
    total: "کل / Total",
    remaining: "باقی / Remaining",
    syncAllData: "تمام ڈیٹا سنک کریں / Sync All Data",
    syncRequiredOnly: "صرف ضروری سنک کریں / Sync Required Only",
    stopSync: "سنک روکیں / Stop Sync",
    lastSynced: "آخری سنک / Last synced",
    autoSyncInterval: "آٹو سنک انٹروال / Auto Sync Interval",
    autoSyncIntervalDescription: "آٹومیٹک بیک اپ سنکرونائزیشن کنفیگر کریں / Configure automatic backup synchronization",
    syncFrequency: "سنک فریکوئنسی / Sync Frequency",
    enterValue: "ویلیو درج کریں / Enter value",
    set: "سیٹ / Set",
    autoSyncActive: "آٹو سنک ایکٹیو ہے۔ ڈیٹا ہر سنک ہوگا / Auto-sync is active. Data will sync every",
    autoSyncDisabled: "آٹو سنک غیر فعال ہے۔ صرف دستی سنک۔ / Auto-sync is disabled. Manual sync only.",
    aboutBackupSync: "بیک اپ اور سنک کے بارے میں / About Backup & Sync",
    syncAllDescription: "مکمل ڈیٹا بیس کو کلاؤڈ اسٹوریج میں اپ لوڈ کرتا ہے / Uploads complete database to cloud storage",
    syncRequiredDescription: "صرف تبدیل شدہ/ترمیم شدہ ڈیٹا اپ لوڈ کرتا ہے / Only uploads changed/modified data",
    autoSyncDescription: "کنفیگر شدہ انٹروالز پر خود بخود سنک کرتا ہے / Automatically syncs at configured intervals",
    storageUsageDescription: "اسٹوریج استعمال کلاؤڈ ڈیٹا بیس اسپیس یوٹیلیزیشن دکھاتا ہے / Storage usage shows cloud database space utilization",
    minutes: "منٹس / Minutes",
    hours: "گھنٹے / Hours",
    days: "دن / Days",
    second: "سیکنڈ / second",
    minute: "منٹ / minute",
    hour: "گھنٹا / hour",
    day: "دن / day",
    excelBackup: "ایکسل بیک اپ / Excel Backup",
    excelBackupDescription: "تمام ڈیٹا بیس ڈیٹا کو ایکسل فائل میں ایکسپورٹ کریں / Export all database data to Excel file",
    excelBackupPath: "ایکسل بیک اپ پاتھ / Excel Backup Path",
    enterExcelBackupPath: "ایکسل بیک اپ پاتھ درج کریں / Enter Excel backup path",
    exportExcel: "ایکسل ایکسپورٹ / Export Excel",
    exporting: "ایکسپورٹ ہو رہا ہے... / Exporting...",
    excelExportSuccess: "ایکسل ایکسپورت کامیابی سے مکمل ہوا / Excel export completed successfully",
    excelExportFailed: "ایکسل ایکسپورت ناکام ہوا / Excel export failed",
    
    // Permission Password Settings
    permissionPasswordSettings: "اجازت پاس ورڈ سیٹنگز / Permission Password Settings",
    permissionPasswordDescription: "حساس آپریشنز کو محفوظ کرنے کے لیے پاس ورڈ سیٹ کریں / Set a password to protect sensitive operations",
    permissionPassword: "اجازت پاس ورڈ / Permission Password",
    enterPermissionPassword: "اجازت پاس ورڈ درج کریں / Enter permission password",
    passwordRequired: "اجازت پاس ورڈ ضروری ہے / Permission password is required",
    failedToFetchPassword: "موجودہ پاس ورڈ حاصل کرنے میں ناکامی / Failed to fetch current password",
    passwordSaved: "اجازت پاس ورڈ کامیابی سے محفوظ ہوا / Permission password saved successfully",
    failedToSavePassword: "اجازت پاس ورڈ محفوظ کرنے میں ناکامی / Failed to save permission password",
    passwordDescription: "یہ پاس ورڈ حساس آپریشنز کو اجازت دینے کے لیے استعمال ہوتا ہے۔ صرف ایڈمن صارفین کے لیے نظر آتا ہے۔ / This password is used to authorize sensitive operations. Only visible to admin users.",
    edit: "ایڈٹ / Edit",
    save: "محفوظ کریں / Save",
    cancel: "منسوخ کریں / Cancel",
    
    // Payment Methods Settings
    paymentMethodsSettings: "ادائیگی کے طریقوں کی سیٹنگز / Payment Methods Settings",
    paymentMethodsDescription: "اپنے دکان کے لیے دستیاب ادائیگی کے طریقوں کو کنفیگر کریں / Configure available payment methods for your shop",
    addPaymentMethod: "ادائیگی کا طریقہ شامل کریں / Add Payment Method",
    editPaymentMethod: "ادائیگی کا طریقہ ایڈٹ کریں / Edit Payment Method",
    paymentMethodName: "ادائیگی کا طریقہ نام / Payment Method Name",
    enterPaymentMethodName: "ادائیگی کا طریقہ نام درج کریں / Enter payment method name",
    paymentMethodNameRequired: "ادائیگی کا طریقہ نام ضروری ہے / Payment method name is required",
    paymentMethodPlaceholder: "مثال: نقد، بینک ٹرانسفر، جاز کیش / e.g., Cash, Bank Transfer, JazzCash",
    paymentMethodType: "ادائیگی کا طریقہ ٹائپ / Payment Method Type",
    cash: "نقد / Cash",
    card: "کارڈ / Card",
    bankTransfer: "بینک ٹرانسفر / Bank Transfer",
    other: "دیگر / Other",
    savePaymentMethod: "ادائیگی کا طریقہ محفوظ کریں / Save Payment Method",
    deletePaymentMethod: "ادائیگی کا طریقہ حذف کریں / Delete Payment Method",
    paymentMethodAdded: "ادائیگی کا طریقہ کامیابی سے شامل ہوا / Payment method added successfully",
    paymentMethodDeleted: "ادائیگی کا طریقہ کامیابی سے حذف ہوا / Payment method deleted successfully",
    paymentMethodFailed: "ادائیگی کا طریقہ آپریشن ناکام ہوا / Payment method operation failed",
    loading: "لوڈ ہو رہا ہے... / Loading...",
    name: "نام / Name",
    status: "حیثیت / Status",
    actions: "ایکشنز / Actions",
    active: "ایکٹو / Active",
    inactive: "ان ایکٹو / Inactive",
    noPaymentMethods: "کوئی ادائیگی کا طریقہ نہیں ملا / No payment methods found",
    edit: "ایڈٹ / Edit",
    delete: "حذف کریں / Delete",
    cancel: "منسوخ کریں / Cancel",
    saving: "محفوظ کر رہا ہے... / Saving...",
    add: "شامل کریں / Add",
    update: "اپ ڈیٹ کریں / Update",
  },
};

export const getSettingsLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return settingsLabels[langKey] || settingsLabels.en;
};
