export const reportsLabels = {
  en: {
    // Common
    reports: "Reports",
    refresh: "Refresh",
    filters: "Filters",
    search: "Search",
    apply: "Apply",
    cancel: "Cancel",
    viewDetails: "View Details",
    noDataFound: "No data found",
    loading: "Loading...",
    
    // Period filters
    period: "Period",
    transactionPeriod: "Transaction Period",
    allPeriods: "All Periods",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    last3Months: "Last 3 Months",
    thisYear: "This Year",
    customRange: "Custom Range",
    fromDate: "From Date",
    toDate: "To Date",
    category: "Category",
    
    // Sales Report
    salesReport: "Sales Report",
    salesDataFor: "Sales data for",
    customerType: "Customer Type",
    allCustomers: "All Customers",
    walkIn: "Walk-in",
    registered: "Registered",
    paymentStatus: "Payment Status",
    paid: "Paid",
    partial: "Partial",
    unpaid: "Unpaid",
    sortBy: "Sort By",
    sortOrder: "Order",
    ascending: "Ascending",
    descending: "Descending",
    invoiceNo: "Invoice No",
    items: "Items",
    total: "Total",
    paidAmount: "Paid",
    dueAmount: "Due",
    actions: "Actions",
    view: "View",
    averageOrderValue: "Average Order Value",
    totalItemsSold: "Total Items Sold",
    invoiceDetails: "Invoice Details",
    customerInfo: "Customer Information",
    paymentInfo: "Payment Information",
    discountTax: "Discount & Tax",
    
    // Purchase Report
    purchaseReport: "Purchase Report",
    purchaseDataFor: "Purchase data for",
    allSuppliers: "All Suppliers",
    deliveryStatus: "Delivery Status",
    allDeliveryStatuses: "All Statuses",
    delivered: "Delivered",
    ordered: "Ordered",
    rejected: "Rejected",
    isRejected: "Is Rejected",
    topSupplier: "Top Supplier",
    purchaseDetails: "Purchase Details",
    
    // Inventory Report
    inventoryReport: "Inventory Report",
    inventoryAnalysis: "Comprehensive inventory analysis with auto-tagging",
    allCategories: "All Categories",
    productName: "Product Name",
    searchByName: "Search by name",
    productCode: "Product Code",
    searchByCode: "Search by code",
    tag: "Tag",
    allTags: "All Tags",
    deadStock: "Dead Stock",
    lowStock: "Low Stock",
    fastSelling: "Fast Selling",
    overstock: "Overstock",
    expired: "Expired",
    nearExpiry: "Near Expiry",
    highReturn: "High Return",
    sortByDefault: "Default",
    sortByTag: "Tag",
    sortByHighestSales: "Highest Sales",
    sortByLowestSales: "Lowest Sales",
    sortByMostReturned: "Most Returned",
    sortByExpiryDate: "Expiry Date",
    sortByStockLevel: "Stock Level",
    totalProducts: "Total Products",
    deadStockCount: "Dead Stock",
    lowStockCount: "Low Stock",
    fastSellingCount: "Fast Selling",
    overstockCount: "Overstock",
    expiredCount: "Expired",
    nearExpiryCount: "Near Expiry",
    highReturnCount: "High Return",
    
    // Customer Report
    customerReport: "Customer Report",
    customerAnalytics: "Customer analytics and ranking",
    totalSpent: "Total Spent",
    totalSales: "Total Sales",
    totalCustomers: "Total Customers",
    avgOrderValue: "Avg Order Value",
    totalDue: "Total Due",
    topCustomer: "Top Customer",
    newCustomers: "New Customers",
    customerDetails: "Customer Details",
    
    // Supplier Report
    supplierReport: "Supplier Report",
    supplierAnalytics: "Supplier analytics and payment tracking",
    totalSuppliers: "Total Suppliers",
    totalBills: "Total Bills",
    supplierDetails: "Supplier Details",
    lastPurchase: "Last Purchase",
    
    // Expense Report
    expenseReport: "Expense Report",
    expenseAnalysis: "Expense analytics and breakdown",
    averageExpense: "Average Expense",
    highestExpense: "Highest Expense",
    categories: "Categories",
    expensesByCategory: "Expenses by Category",
    expensesByType: "Expenses by Type",
    amount: "Amount",
    type: "Type",
    notes: "Notes",
    
    // Staff Report
    staffReport: "Staff Report",
    staffPerformance: "Comprehensive staff performance, attendance, and salary report",
    staffMember: "Staff Member",
    allStaff: "All Staff",
    totalStaff: "Total Staff",
    totalExpectedSalary: "Total Expected Salary",
    totalSalariesPaid: "Total Salaries Paid",
    remainingSalary: "Remaining Salary",
    averageSalary: "Average Salary",
    totalAdvances: "Total Advances",
    totalWorkingHours: "Total Working Hours",
    avgWorkingHours: "Avg Working Hours",
    totalPresentDays: "Total Present Days",
    totalAbsentDays: "Total Absent Days",
    avgAttendancePercent: "Avg Attendance",
    highestAttendance: "Highest Attendance",
    topPerformer: "Top Performer",
    totalDeductions: "Total Deductions",
    totalAttendance: "Total Attendance",
    attendanceRate: "Attendance Rate",
    ordersHandled: "Orders Handled",
    staffDetails: "Staff Details",
    exportPdf: "Export PDF",
    previewReport: "Report Preview",
    viewAndExportReport: "Zoom preview and export this report",
    exporting: "Exporting...",
    
    // Credits & Debits Report
    creditsDebitsReport: "Credits & Debits Report",
    creditsDebitsAnalysis: "Track credit account transactions and balances",
    accountType: "Account Type",
    allTypes: "All Types",
    general: "General",
    customer: "Customer",
    supplier: "Supplier",
    status: "Status",
    allStatuses: "All Statuses",
    toPay: "To Give",
    toReceive: "To Receive",
    cleared: "Cleared",
    account: "Account",
    creditAccounts: "Accounts",
    totalToPay: "Total To Give",
    totalPaid: "Total Paid",
    statusAndBalance: "Status & Balance",
    viewLedger: "View Ledger",
    totalAccounts: "Total Accounts",
    iOwe: "To Give",
    owedToMe: "To Receive",
    netBalance: "Net Balance",
    noAccountsFound: "No Accounts Found",
    tryAdjustingFilters: "Try adjusting your filters",
    date: "Date",
    description: "Description",
    source: "Source",
    accountLedger: "Account Ledger",
    accountName: "Account Name",
    accountTypeLabel: "Account Type",
    phone: "Phone",
    currentBalance: "Current Balance",
    transactionHistory: "Transaction History",
    debit: "Debit",
    credit: "Credit",
    balance: "Balance",
    noTransactions: "No transactions found",
    
    // Main Business Report
    mainBusinessReport: "Main Business Report",
    businessOverview: "Comprehensive business overview and financial summary",
    overview: "Overview",
    returnsAndWastage: "Returns and Wastage",
    profitability: "Profitability",
    totalSalaries: "Total Salaries",
    purchaseReturns: "Purchase Returns",
    saleReturns: "Sale Returns",
    wastageLoss: "Wastage Loss",
    wastageCost: "Wastage Cost",
    inventoryWastage: "Inventory Wastage",
    wastage: "Wastage",
    saleCount: "Sale Count",
    netLossForPeriodHeading: "Net loss for this period",
    qarzaReceivable: "Qarza Receivable",
    qarzaPayable: "Qarza Payable",
    netProfit: "Net Profit",
    grossProfit: "Gross Profit",
    profitMargin: "Profit Margin",
    finalBusinessResult: "Final Business Result",
    profit: "Profit",
    loss: "Loss",
    businessFormula: "Sales - Purchases - Expenses - Wastage - Salaries",
    netMargin: "Net Margin",
    netQarza: "Net Qarza",
    orders: "orders",
    purchases: "purchases",
    payments: "payments",
    returns: "returns",
    records: "records",
    completedOrders: "completed orders",
    owedToYouByCustomers: "owed to you by customers",
    owedByYouToSuppliers: "owed by you to suppliers",
    grossMargin: "Gross Margin",
    netMarginPercentage: "Net Margin",
    paymentSourceSections: "Payment Source Sections",
    revenueFromCompletedOrders: "Revenue from completed orders",
    costOfInventoryPurchases: "Cost of inventory purchases",
    operatingExpenses: "Operating expenses",
    staffSalaryPayments: "Staff salary payments",
    returnsSentToSuppliers: "Returns sent to suppliers",
    returnsToSuppliers: "Returns to suppliers",
    customerProductReturns: "Customer product returns",
    inventoryWastageCost: "Inventory wastage cost",
    qarzaReceivablePayable: "Qarza Receivable / Payable",
    outstandingCredit: "Outstanding credit",
    byProduct: "By Product",
    units: "units",
    transactions: "transactions",
    breakdown: "Breakdown",
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    periodFilter: "Period Filter",
    showingFirst50: "Showing first 50 of",
    noTransactionsInPeriod: "No transactions in this period",
    orderNumber: "Order Number",
    invoiceNumber: "Invoice Number",
    title: "Title",
    product: "Product",
    quantity: "Quantity",
    costPrice: "Cost Price",
    totalLoss: "Total Loss",
    returnNumber: "Return Number",
    staffName: "Staff Name",
    productReturnsByReason: "Product Returns by Reason",
    purchaseReturnsBySupplier: "Purchase Returns by Supplier",
    wastagesByProduct: "Wastages by Product",
    salariesByStaff: "Salaries by Staff",
    salesByPaymentMethod: "Sales by Payment Method",
    salesByCategory: "Sales by Category",
    purchasesByCategory: "Purchases by Category",
    topSellingProducts: "Top Selling Products",
    topSuppliers: "Top Suppliers",
    topCustomers: "Top Customers",
    netProfitForPeriod: "Net profit for this period",
    netLossForPeriod: "Net loss for this period",
    receivable: "Receivable",
    payable: "Payable",
    salaries: "Salaries",
    inventory: "Inventory",
    sales: "Sales",
    expenses: "Expenses",
    totalPurchases: "Total Purchases",
    totalExpenses: "Total Expenses",
    netProfitLoss: "Net Profit/Loss",
  },
  ur: {
    // Common
    reports: "رپورٹس",
    refresh: "تازہ کاری",
    filters: "فلٹرز",
    search: "تلاش",
    apply: "لاگو کریں",
    cancel: "منسوخ کریں",
    viewDetails: "تفصیلات دیکھیں",
    noDataFound: "کوئی ڈیٹا نہیں ملا",
    loading: "لوڈ ہو رہا ہے...",
    
    // Period filters
    period: "مدت",
    transactionPeriod: "لین دین کی مدت",
    allPeriods: "تمام مدتیں",
    today: "آج",
    thisWeek: "اس ہفتے",
    thisMonth: "اس مہینے",
    last3Months: "پچھلے 3 مہینے",
    thisYear: "اس سال",
    customRange: "حسب ضرورت حد",
    fromDate: "سے تاریخ",
    toDate: "تک تاریخ",
    category: "زمرہ",
    
    // Sales Report
    salesReport: "فروخت رپورٹ",
    salesDataFor: "فروخت کا ڈیٹا",
    customerType: "گاہک کی قسم",
    allCustomers: "تمام گاہک",
    walkIn: "واک ان",
    registered: "رجسٹرڈ",
    paymentStatus: "ادائیگی کی حیثیت",
    paid: "ادا شدہ",
    partial: "جزوی",
    unpaid: "غیر ادا",
    sortBy: "ترتیب دیں",
    sortOrder: "ترتیب",
    ascending: "بڑھتی ہوئی",
    descending: "گھرتی ہوئی",
    invoiceNo: "انوائس نمبر",
    items: "اشیاء",
    total: "کل",
    paidAmount: "ادا شدہ",
    dueAmount: "باقی",
    actions: "اقدامات",
    view: "دیکھیں",
    totalItemsSold: "کل فروخت شدہ اشیاء",
    invoiceDetails: "انوائس کی تفصیلات",
    customerInfo: "گاہک کی معلومات",
    paymentInfo: "ادائیگی کی معلومات",
    discountTax: "ڈسکاؤنٹ اور ٹیکس",
    
    // Purchase Report
    purchaseReport: "خریداری رپورٹ",
    purchaseDataFor: "خریداری کا ڈیٹا",
    allSuppliers: "تمام سپلائرز",
    deliveryStatus: "ڈیلیوری کی حیثیت",
    allDeliveryStatuses: "تمام حیثیت",
    delivered: "پہنچا دیا",
    ordered: "آرڈر دیا",
    rejected: "مسترد",
    isRejected: "مسترد ہے",
    topSupplier: "بہترین سپلائر",
    purchaseDetails: "خریداری کی تفصیلات",
    
    // Inventory Report
    inventoryReport: "انوینٹری رپورٹ",
    inventoryAnalysis: "مکمل انوینٹری تجزیہ خودکار ٹیگنگ کے ساتھ",
    allCategories: "تمام زمرے",
    productName: "پروڈکٹ کا نام",
    searchByName: "نام سے تلاش کریں",
    productCode: "پروڈکٹ کوڈ",
    searchByCode: "کوڈ سے تلاش کریں",
    tag: "ٹیگ",
    allTags: "تمام ٹیگز",
    deadStock: "ڈیڈ اسٹاک",
    lowStock: "کم اسٹاک",
    fastSelling: "تیز فروخت",
    overstock: "زیادہ اسٹاک",
    expired: "ختم ہو چکا",
    nearExpiry: "ختم ہونے قریب",
    highReturn: "زیادہ واپسی",
    sortByDefault: "ڈیفالٹ",
    sortByTag: "ٹیگ",
    sortByHighestSales: "سب سے زیادہ فروخت",
    sortByLowestSales: "سب سے کم فروخت",
    sortByMostReturned: "سب سے زیادہ واپسی",
    sortByExpiryDate: "ختم ہونے کی تاریخ",
    sortByStockLevel: "اسٹاک لیول",
    totalProducts: "کل پروڈکٹس",
    deadStockCount: "ڈیڈ اسٹاک",
    lowStockCount: "کم اسٹاک",
    fastSellingCount: "تیز فروخت",
    overstockCount: "زیادہ اسٹاک",
    expiredCount: "ختم ہو چکے",
    nearExpiryCount: "ختم ہونے قریب",
    highReturnCount: "زیادہ واپسی",
    
    // Customer Report
    customerReport: "کسٹمر رپورٹ",
    customerAnalytics: "کسٹمر تجزیہ اور درجہ بندی",
    totalSpent: "کل خرچ کیا",
    totalSales: "کل فروخت",
    totalCustomers: "کل کسٹمرز",
    avgOrderValue: "اوسط آرڈر ویلیو",
    totalDue: "کل بقایا",
    topCustomer: "بہترین کسٹمر",
    newCustomers: "نئے کسٹمرز",
    customerDetails: "کسٹمر کی تفصیلات",
    
    // Supplier Report
    supplierReport: "سپلائر رپورٹ",
    supplierAnalytics: "سپلائر کے تجزیات اور ادائیگی کی ٹریکنگ",
    totalSuppliers: "کل سپلائرز",
    totalBills: "کل بلز",
    supplierDetails: "سپلائر کی تفصیلات",
    lastPurchase: "آخری خریداری",
    
    // Expense Report
    expenseReport: "اخراجات رپورٹ",
    expenseAnalysis: "اخراجات کے تجزیات اور تفصیل",
    averageExpense: "اوسط اخراجات",
    highestExpense: "سب سے زیادہ اخراجات",
    categories: "زمرے",
    expensesByCategory: "زمرہ کے لحاظ سے اخراجات",
    expensesByType: "قسم کے لحاظ سے اخراجات",
    amount: "رقم",
    type: "قسم",
    notes: "نوٹس",
    
    // Staff Report
    staffReport: "اسٹاف رپورٹ",
    staffPerformance: "مکمل اسٹاف کارکردگی، حاضری اور تنخواہ رپورٹ",
    staffMember: "اسٹاف ممبر",
    allStaff: "تمام اسٹاف",
    totalStaff: "کل اسٹاف",
    totalExpectedSalary: "کل متوقع تنخواہ",
    totalSalariesPaid: "کل تنخواہ ادا شدہ",
    remainingSalary: "باقی تنخواہ",
    averageSalary: "اوسط تنخواہ",
    totalAdvances: "کل پیشگی",
    totalWorkingHours: "کل کام کے گھنٹے",
    avgWorkingHours: "اوسط کام کے گھنٹے",
    totalPresentDays: "کل موجود دن",
    totalAbsentDays: "کل غیر موجود دن",
    avgAttendancePercent: "اوسط حاضری",
    highestAttendance: "سب سے زیادہ حاضری",
    topPerformer: "بہترین کارکردگی",
    totalDeductions: "کل کٹوتی",
    totalAttendance: "کل حاضری",
    attendanceRate: "حاضری کی شرح",
    ordersHandled: "آرڈرز ہینڈل کیے",
    staffDetails: "اسٹاف کی تفصیلات",
    exportPdf: "پی ڈی ایف ایکسپورٹ کریں",
    previewReport: "رپورٹ کا پیش نظارہ",
    viewAndExportReport: "اس رپورٹ کو برآمد کرنے سے پہلے زوم کریں اور دیکھیں",
    exporting: "برآمد ہو رہا ہے...",
    
    // Credits & Debits Report
    creditsDebitsReport: "کریڈٹ اور ڈیبٹ رپورٹ",
    creditsDebitsAnalysis: "کریڈٹ اکاؤنٹ لین دین اور بیلنس ٹریک کریں",
    accountType: "اکاؤنٹ کی قسم",
    allTypes: "تمام اقسام",
    general: "عام",
    customer: "گاہک",
    supplier: "سپلائر",
    status: "حیثیت",
    allStatuses: "تمام حیثیت",
    toPay: "دینا ہے",
    toReceive: "وصول کرنا ہے",
    cleared: "صاف",
    account: "اکاؤنٹ",
    creditAccounts: "اکاؤنٹس",
    totalToPay: "کل دینا ہے",
    totalPaid: "کل ادا شدہ",
    statusAndBalance: "حیثیت اور بیلنس",
    viewLedger: "لیجر دیکھیں",
    totalAccounts: "کل اکاؤنٹس",
    iOwe: "دینا ہے",
    owedToMe: "وصول کرنا ہے",
    netBalance: "نیٹ بیلنس",
    noAccountsFound: "کوئی اکاؤنٹ نہیں ملا",
    tryAdjustingFilters: "اپنے فلٹرز ایڈجسٹ کرنے کی کوشش کریں",
    date: "تاریخ",
    description: "تفصیل",
    source: "ماخذ",
    accountLedger: "اکاؤنٹ لیجر",
    accountName: "اکاؤنٹ کا نام",
    accountTypeLabel: "اکاؤنٹ کی قسم",
    phone: "فون",
    currentBalance: "موجودہ بیلنس",
    transactionHistory: "لین دین کی تاریخ",
    debit: "ڈیبٹ",
    credit: "کریڈٹ",
    balance: "بیلنس",
    noTransactions: "کوئی لین دین نہیں ملا",
    
    // Main Business Report
    mainBusinessReport: "مین کاروبار رپورٹ",
    businessOverview: "مکمل کاروبار کا جائزہ اور مالیاتی خلاصہ",
    overview: "جائزہ",
    returnsAndWastage: "واپسی اور ضیاع",
    profitability: "منافع کی صلاحیت",
    totalSalaries: "کل تنخواہیں",
    purchaseReturns: "خریداری کی واپسی / Purchase Returns",
    saleReturns: "فروخت کی واپسی / Sale Returns",
    wastageLoss: "ضیاع کا نقصان / Wastage Loss",
    wastageCost: "ضیاع کی لاگت / Wastage Cost",
    inventoryWastage: "انوینٹری ضیاع / Inventory Wastage",
    wastage: "ضیاع / Wastage",
    saleCount: "فروخت کی تعداد / Sale Count",
    netLossForPeriodHeading: "اس مدت کے لیے خالص نقصان / Net loss for this period",
    qarzaReceivable: "قرضہ وصول کرنا ہے",
    qarzaPayable: "قرضہ ادا کرنا ہے",
    netProfit: "خالص منافع",
    grossProfit: "گروس منافع",
    profitMargin: "منافع کا مارجن",
    finalBusinessResult: "حتمی کاروباری نتیجہ",
    profit: "منافع",
    loss: "نقصان",
    businessFormula: "فروخت - خریداری - اخراجات - ضیاع - تنخواہیں",
    netMargin: "نیٹ مارجن",
    netQarza: "نیٹ قرضہ",
    orders: "آرڈرز",
    purchases: "خریداریاں",
    payments: "ادائیگیاں",
    returns: "واپسیاں",
    records: "ریکارڈز",
    completedOrders: "مکمل آرڈرز",
    owedToYouByCustomers: "گاہکوں کی طرف سے آپ کو واجب",
    owedByYouToSuppliers: "سپلائرز کو آپ کی طرف سے واجب",
    grossMargin: "گروس مارجن",
    netMarginPercentage: "نیٹ مارجن",
    paymentSourceSections: "ادائیگی کا ماخذ سیکشنز",
    revenueFromCompletedOrders: "مکمل آرڈرز سے آمدنی",
    costOfInventoryPurchases: "انوینٹری خریداری کی لاگت",
    operatingExpenses: "آپریٹنگ اخراجات",
    staffSalaryPayments: "اسٹاف تنخواہ کی ادائیگیاں",
    returnsSentToSuppliers: "سپلائرز کو بھیجی گئی واپسیاں",
    returnsToSuppliers: "سپلائرز کو واپسیاں",
    customerProductReturns: "گاہک کی پروڈکٹ واپسیاں",
    inventoryWastageCost: "انوینٹری ضیاع کی لاگت",
    qarzaReceivablePayable: "قرضہ وصول کرنا ہے / ادا کرنا ہے",
    outstandingCredit: "باقی کریڈٹ",
    byProduct: "پروڈکٹ کے لحاظ سے",
    units: "یونٹس",
    transactions: "لین دین",
    breakdown: "تفصیل",
    expandAll: "سبھی کو پھیلائیں",
    collapseAll: "سبھی کو سمیٹیں",
    periodFilter: "مدت فلٹر",
    showingFirst50: "پہلے 50 دکھا رہے ہیں",
    noTransactionsInPeriod: "اس مدت میں کوئی لین دین نہیں",
    orderNumber: "آرڈر نمبر",
    invoiceNumber: "انوائس نمبر",
    title: "عنوان",
    product: "پروڈکٹ",
    quantity: "مقدار",
    costPrice: "لاگت قیمت",
    totalLoss: "کل نقصان",
    returnNumber: "واپسی نمبر",
    staffName: "اسٹاف کا نام",
    productReturnsByReason: "وجہ کے لحاظ سے پروڈکٹ واپسیاں",
    purchaseReturnsBySupplier: "سپلائر کے لحاظ سے خریداری واپسیاں",
    wastagesByProduct: "پروڈکٹ کے لحاظ سے ضیاع",
    salariesByStaff: "اسٹاف کے لحاظ سے تنخواہیں",
    salesByPaymentMethod: "ادائیگی کے طریقے کے لحاظ سے فروخت",
    salesByCategory: "زمرہ کے لحاظ سے فروخت",
    purchasesByCategory: "زمرہ کے لحاظ سے خریداری",
    topSellingProducts: "بہترین فروخت پروڈکٹس",
    topSuppliers: "بہترین سپلائرز",
    topCustomers: "بہترین گاہک",
    netProfitForPeriod: "اس مدت کے لیے خالص منافع",
    netLossForPeriod: "اس مدت کے لیے خالص نقصان",
    receivable: "وصول کرنا ہے",
    payable: "ادا کرنا ہے",
    sales: "فروخت",
    salaries: "تنخواہیں",
    inventory: "انوینٹری",
    expenses: "خرچے",
    totalPurchases: "کل خریداری",
    totalExpenses: "کل اخراجات",
    netProfitLoss: "خالص منافع / نقصان",
  },
  ur_en: {
    // Common
    reports: "رپورٹس / Reports",
    refresh: "تازہ کاری / Refresh",
    filters: "فلٹرز / Filters",
    search: "تلاش / Search",
    apply: "لاگو کریں / Apply",
    cancel: "منسوخ کریں / Cancel",
    viewDetails: "تفصیلات دیکھیں / View Details",
    noDataFound: "کوئی ڈیٹا نہیں ملا / No data found",
    loading: "لوڈ ہو رہا ہے / Loading...",
    
    // Period filters
    period: "مدت / Period",
    transactionPeriod: "لین دین کی مدت / Transaction Period",
    allPeriods: "تمام مدتیں / All Periods",
    today: "آج / Today",
    thisWeek: "اس ہفتے / This Week",
    thisMonth: "اس مہینے / This Month",
    last3Months: "پچھلے 3 مہینے / Last 3 Months",
    thisYear: "اس سال / This Year",
    customRange: "حسب ضرورت حد / Custom Range",
    fromDate: "سے تاریخ / From Date",
    toDate: "تک تاریخ / To Date",
    category: "زمرہ / Category",
    
    // Sales Report
    salesReport: "فروخت رپورٹ / Sales Report",
    salesDataFor: "فروخت کا ڈیٹا / Sales data for",
    customerType: "گاہک کی قسم / Customer Type",
    allCustomers: "تمام گاہک / All Customers",
    walkIn: "واک ان / Walk-in",
    registered: "رجسٹرڈ / Registered",
    paymentStatus: "ادائیگی کی حیثیت / Payment Status",
    paid: "ادا شدہ / Paid",
    partial: "جزوی / Partial",
    unpaid: "غیر ادا / Unpaid",
    sortBy: "ترتیب دیں / Sort By",
    sortOrder: "ترتیب / Order",
    ascending: "بڑھتی ہوئی / Ascending",
    descending: "گھرتی ہوئی / Descending",
    invoiceNo: "انوائس نمبر / Invoice No",
    items: "اشییں / Items",
    total: "کل / Total",
    paidAmount: "ادا شدہ / Paid",
    dueAmount: "باقی / Due",
    actions: "اقدامات / Actions",
    view: "دیکھیں / View",
    totalItemsSold: "کل فروخت شدہ اشیاء / Total Items Sold",
    invoiceDetails: "انوائس کی تفصیلات / Invoice Details",
    customerInfo: "گاہک کی معلومات / Customer Information",
    paymentInfo: "ادائیگی کی معلومات / Payment Information",
    discountTax: "ڈسکاؤنٹ اور ٹیکس / Discount & Tax",
    
    // Purchase Report
    purchaseReport: "خریداری رپورٹ / Purchase Report",
    purchaseDataFor: "خریداری کا ڈیٹا / Purchase data for",
    allSuppliers: "تمام سپلائرز / All Suppliers",
    deliveryStatus: "ڈیلیوری کی حیثیت / Delivery Status",
    allDeliveryStatuses: "تمام حیثیت / All Statuses",
    delivered: "پہنچا دیا / Delivered",
    ordered: "آرڈر دیا / Ordered",
    rejected: "مسترد / Rejected",
    isRejected: "مسترد ہے / Is Rejected",
    topSupplier: "بہترین سپلائر / Top Supplier",
    purchaseDetails: "خریداری کی تفصیلات / Purchase Details",
    
    // Inventory Report
    inventoryReport: "انوینٹری رپورٹ / Inventory Report",
    inventoryAnalysis: "مکمل انوینٹری تجزیہ خودکار ٹیگنگ کے ساتھ / Comprehensive inventory analysis with auto-tagging",
    allCategories: "تمام زمرے / All Categories",
    productName: "پروڈکٹ کا نام / Product Name",
    searchByName: "نام سے تلاش کریں / Search by name",
    productCode: "پروڈکٹ کوڈ / Product Code",
    searchByCode: "کوڈ سے تلاش کریں / Search by code",
    tag: "ٹیگ / Tag",
    allTags: "تمام ٹیگز / All Tags",
    deadStock: "ڈیڈ اسٹاک / Dead Stock",
    lowStock: "کم اسٹاک / Low Stock",
    fastSelling: "تیز فروخت / Fast Selling",
    overstock: "زیادہ اسٹاک / Overstock",
    expired: "ختم ہو چکا / Expired",
    nearExpiry: "ختم ہونے قریب / Near Expiry",
    highReturn: "زیادہ واپسی / High Return",
    sortByDefault: "ڈیفالٹ / Default",
    sortByTag: "ٹیگ / Tag",
    sortByHighestSales: "سب سے زیادہ فروخت / Highest Sales",
    sortByLowestSales: "سب سے کم فروخت / Lowest Sales",
    sortByMostReturned: "سب سے زیادہ واپسی / Most Returned",
    sortByExpiryDate: "ختم ہونے کی تاریخ / Expiry Date",
    sortByStockLevel: "اسٹاک لیول / Stock Level",
    totalProducts: "کل پروڈکٹس / Total Products",
    deadStockCount: "ڈیڈ اسٹاک / Dead Stock",
    lowStockCount: "کم اسٹاک / Low Stock",
    fastSellingCount: "تیز فروخت / Fast Selling",
    overstockCount: "زیادہ اسٹاک / Overstock",
    expiredCount: "ختم ہو چکے / Expired",
    nearExpiryCount: "ختم ہونے قریب / Near Expiry",
    highReturnCount: "زیادہ واپسی / High Return",
    
    // Customer Report
    customerReport: "کسٹمر رپورٹ / Customer Report",
    customerAnalytics: "کسٹمر تجزیہ اور درجہ بندی / Customer analytics and ranking",
    totalSpent: "کل خرچ کیا / Total Spent",
    totalSales: "کل فروخت / Total Sales",
    totalCustomers: "کل کسٹمرز / Total Customers",
    avgOrderValue: "اوسط آرڈر ویلیو / Avg Order Value",
    totalDue: "کل بقایا / Total Due",
    topCustomer: "بہترین کسٹمر / Top Customer",
    newCustomers: "نئے کسٹمرز / New Customers",
    customerDetails: "کسٹمر کی تفصیلات / Customer Details",
    
    // Supplier Report
    supplierReport: "سپلائر رپورٹ / Supplier Report",
    supplierAnalytics: "سپلائر کے تجزیات اور ادائیگی کی ٹریکنگ / Supplier analytics and payment tracking",
    totalSuppliers: "کل سپلائرز / Total Suppliers",
    totalBills: "کل بلز / Total Bills",
    supplierDetails: "سپلائر کی تفصیلات / Supplier Details",
    lastPurchase: "آخری خریداری / Last Purchase",
    
    // Expense Report
    expenseReport: "اخراجات رپورٹ / Expense Report",
    expenseAnalysis: "اخراجات کے تجزیات اور تفصیل / Expense analytics and breakdown",
    averageExpense: "اوسط اخراجات / Average Expense",
    highestExpense: "سب سے زیادہ اخراجات / Highest Expense",
    categories: "زمرے / Categories",
    expensesByCategory: "زمرہ کے لحاظ سے اخراجات / Expenses by Category",
    expensesByType: "قسم کے لحاظ سے اخراجات / Expenses by Type",
    amount: "رقم / Amount",
    type: "قسم / Type",
    notes: "نوٹس / Notes",
    
    // Staff Report
    staffReport: "اسٹاف رپورٹ / Staff Report",
    staffPerformance: "مکمل اسٹاف کارکردگی، حاضری اور تنخواہ رپورٹ / Comprehensive staff performance, attendance, and salary report",
    staffMember: "اسٹاف ممبر / Staff Member",
    allStaff: "تمام اسٹاف / All Staff",
    totalStaff: "کل اسٹاف / Total Staff",
    totalExpectedSalary: "کل متوقع تنخواہ / Total Expected Salary",
    totalSalariesPaid: "کل تنخواہ ادا شدہ / Total Salaries Paid",
    remainingSalary: "باقی تنخواہ / Remaining Salary",
    averageSalary: "اوسط تنخواہ / Average Salary",
    totalAdvances: "کل پیشگی / Total Advances",
    totalWorkingHours: "کل کام کے گھنٹے / Total Working Hours",
    avgWorkingHours: "اوسط کام کے گھنٹے / Avg Working Hours",
    totalPresentDays: "کل موجود دن / Total Present Days",
    totalAbsentDays: "کل غیر موجود دن / Total Absent Days",
    avgAttendancePercent: "اوسط حاضری / Avg Attendance",
    highestAttendance: "سب سے زیادہ حاضری / Highest Attendance",
    topPerformer: "بہترین کارکردگی / Top Performer",
    totalDeductions: "کل کٹوتی / Total Deductions",
    totalAttendance: "کل حاضری / Total Attendance",
    attendanceRate: "حاضری کی شرح / Attendance Rate",
    ordersHandled: "آرڈرز ہینڈل کیے / Orders Handled",
    staffDetails: "اسٹاف کی تفصیلات / Staff Details",
    exportPdf: "پی ڈی ایف ایکسپورٹ کریں / Export PDF",
    
    // Credits & Debits Report
    creditsDebitsReport: "کریڈٹ اور ڈیبٹ رپورٹ / Credits & Debits Report",
    creditsDebitsAnalysis: "کریڈٹ اکاؤنٹ لین دین اور بیلنس ٹریک کریں / Track credit account transactions and balances",
    accountType: "اکاؤنٹ کی قسم / Account Type",
    allTypes: "تمام اقسام / All Types",
    general: "عام / General",
    customer: "گاہک / Customer",
    supplier: "سپلائر / Supplier",
    status: "حیثیت / Status",
    allStatuses: "تمام حیثیت / All Statuses",
    toPay: "دینا ہے / To Give",
    toReceive: "وصول کرنا ہے / To Receive",
    cleared: "صاف / Cleared",
    account: "اکاؤنٹ / Account",
    creditAccounts: "اکاؤنٹس / Accounts",
    totalToPay: "کل دینا ہے / Total To Give",
    totalPaid: "کل ادا شدہ / Total Paid",
    statusAndBalance: "حیثیت اور بیلنس / Status & Balance",
    viewLedger: "لیجر دیکھیں / View Ledger",
    totalAccounts: "کل اکاؤنٹس / Total Accounts",
    iOwe: "دینا ہے / To Give",
    owedToMe: "وصول کرنا ہے / To Receive",
    netBalance: "نیٹ بیلنس / Net Balance",
    noAccountsFound: "کوئی اکاؤنٹ نہیں ملا / No Accounts Found",
    tryAdjustingFilters: "اپنے فلٹرز ایڈجسٹ کرنے کی کوشش کریں / Try adjusting your filters",
    date: "تاریخ / Date",
    description: "تفصیل / Description",
    source: "ماخذ / Source",
    accountLedger: "اکاؤنٹ لیجر / Account Ledger",
    accountName: "اکاؤنٹ کا نام / Account Name",
    accountTypeLabel: "اکاؤنٹ کی قسم / Account Type",
    phone: "فون / Phone",
    currentBalance: "موجودہ بیلنس / Current Balance",
    transactionHistory: "لین دین کی تاریخ / Transaction History",
    debit: "ڈیبٹ / Debit",
    credit: "کریڈٹ / Credit",
    balance: "بیلنس / Balance",
    noTransactions: "کوئی لین دین نہیں ملا / No transactions found",
    
    // Main Business Report
    mainBusinessReport: "مین کاروبار رپورٹ / Main Business Report",
    businessOverview: "مکمل کاروبار کا جائزہ اور مالیاتی خلاصہ / Comprehensive business overview and financial summary",
    overview: "جائزہ / Overview",
    returnsAndWastage: "واپسی اور ضیاع / Returns and Wastage",
    profitability: "منافع کی صلاحیت / Profitability",
    totalSalaries: "کل تنخواہیں / Total Salaries",
    purchaseReturns: "خریداری کی واپسی / Purchase Returns",
    saleReturns: "فروخت کی واپسی / Sale Returns",
    wastageLoss: "ضیاع کا نقصان / Wastage Loss",
    wastageCost: "ضیاع کی لاگت / Wastage Cost",
    inventoryWastage: "انوینٹری ضیاع / Inventory Wastage",
    wastage: "ضیاع / Wastage",
    saleCount: "فروخت کی تعداد / Sale Count",
    netLossForPeriodHeading: "اس مدت کے لیے خالص نقصان / Net loss for this period",
    qarzaReceivable: "قرضہ وصول کرنا ہے / Qarza Receivable",
    qarzaPayable: "قرضہ ادا کرنا ہے / Qarza Payable",
    netProfit: "خالص منافع / Net Profit",
    grossProfit: "گروس منافع / Gross Profit",
    profitMargin: "منافع کا مارجن / Profit Margin",
    finalBusinessResult: "حتمی کاروباری نتیجہ / Final Business Result",
    profit: "منافع / Profit",
    loss: "نقصان / Loss",
    businessFormula: "فروخت - خریداری - اخراجات - ضیاع - تنخواہیں / Sales - Purchases - Expenses - Wastage - Salaries",
    netMargin: "نیٹ مارجن / Net Margin",
    netQarza: "نیٹ قرضہ / Net Qarza",
    orders: "آرڈرز / orders",
    purchases: "خریداریاں / purchases",
    payments: "ادائیگیاں / payments",
    returns: "واپسیاں / returns",
    records: "ریکارڈز / records",
    completedOrders: "مکمل آرڈرز / completed orders",
    owedToYouByCustomers: "گاہکوں کی طرف سے آپ کو واجب / owed to you by customers",
    owedByYouToSuppliers: "سپلائرز کو آپ کی طرف سے واجب / owed by you to suppliers",
    grossMargin: "گروس مارجن / Gross Margin",
    netMarginPercentage: "نیٹ مارجن / Net Margin",
    paymentSourceSections: "ادائیگی کا ماخذ سیکشنز / Payment Source Sections",
    revenueFromCompletedOrders: "مکمل آرڈرز سے آمدنی / Revenue from completed orders",
    costOfInventoryPurchases: "انوینٹری خریداری کی لاگت / Cost of inventory purchases",
    operatingExpenses: "آپریٹنگ اخراجات / Operating expenses",
    staffSalaryPayments: "اسٹاف تنخواہ کی ادائیگیاں / Staff salary payments",
    returnsSentToSuppliers: "سپلائرز کو بھیجی گئی واپسیاں / Returns sent to suppliers",
    returnsToSuppliers: "سپلائرز کو واپسیاں / Returns to suppliers",
    customerProductReturns: "گاہک کی پروڈکٹ واپسیاں / Customer product returns",
    inventoryWastageCost: "انوینٹری ضیاع کی لاگت / Inventory wastage cost",
    qarzaReceivablePayable: "قرضہ وصول کرنا ہے / ادا کرنا ہے / Qarza Receivable / Payable",
    outstandingCredit: "باقی کریڈٹ / Outstanding credit",
    byProduct: "پروڈکٹ کے لحاظ سے / By Product",
    units: "یونٹس / units",
    transactions: "لین دین / transactions",
    breakdown: "تفصیل / Breakdown",
    expandAll: "سبھی کو پھیلائیں / Expand All",
    collapseAll: "سبھی کو سمیٹیں / Collapse All",
    periodFilter: "مدت فلٹر / Period Filter",
    showingFirst50: "پہلے 50 دکھا رہے ہیں / Showing first 50 of",
    noTransactionsInPeriod: "اس مدت میں کوئی لین دین نہیں / No transactions in this period",
    orderNumber: "آرڈر نمبر / Order Number",
    invoiceNumber: "انوائس نمبر / Invoice Number",
    title: "عنوان / Title",
    product: "پروڈکٹ / Product",
    quantity: "مقدار / Quantity",
    costPrice: "لاگت قیمت / Cost Price",
    totalLoss: "کل نقصان / Total Loss",
    returnNumber: "واپسی نمبر / Return Number",
    staffName: "اسٹاف کا نام / Staff Name",
    productReturnsByReason: "وجہ کے لحاظ سے پروڈکٹ واپسیاں / Product Returns by Reason",
    purchaseReturnsBySupplier: "سپلائر کے لحاظ سے خریداری واپسیاں / Purchase Returns by Supplier",
    wastagesByProduct: "پروڈکٹ کے لحاظ سے ضیاع / Wastages by Product",
    salariesByStaff: "اسٹاف کے لحاظ سے تنخواہیں / Salaries by Staff",
    salesByPaymentMethod: "ادائیگی کے طریقے کے لحاظ سے فروخت / Sales by Payment Method",
    salesByCategory: "زمرہ کے لحاظ سے فروخت / Sales by Category",
    purchasesByCategory: "زمرہ کے لحاظ سے خریداری / Purchases by Category",
    topSellingProducts: "بہترین فروخت پروڈکٹس / Top Selling Products",
    topSuppliers: "بہترین سپلائرز / Top Suppliers",
    topCustomers: "بہترین گاہک / Top Customers",
    netProfitForPeriod: "اس مدت کے لیے خالص منافع / Net profit for this period",
    netLossForPeriod: "اس مدت کے لیے خالص نقصان / Net loss for this period",
    receivable: "وصول کرنا ہے / Receivable",
    payable: "ادا کرنا ہے / Payable",
    sales: "فروخت / Sales",
    salaries: "تنخواہیں / Salaries",
    inventory: "انوینٹری / Inventory",
    expenses: "خرچے / Expenses",
    totalPurchases: "کل خریداری / Total Purchases",
    totalExpenses: "کل اخراجات / Total Expenses",
    netProfitLoss: "خالص منافع / نقصان / Net Profit/Loss",
  },
};

export const getReportsLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return reportsLabels[langKey] || reportsLabels.en;
};
