export const reportsLabels = {
  en: {
    // Common
    reports: "Reports",
    refresh: "Refresh",
    filters: "Filters",
    search: "Search",
    apply: "Apply",
    cancel: "Cancel",
    viewDetails: "View Details",
    noDataFound: "No data found",
    loading: "Loading...",
    
    // Period filters
    period: "Period",
    today: "Today",
    thisMonth: "This Month",
    last3Months: "Last 3 Months",
    thisYear: "This Year",
    customRange: "Custom Range",
    fromDate: "From Date",
    toDate: "To Date",
    
    // Sales Report
    salesReport: "Sales Report",
    salesDataFor: "Sales data for",
    customerType: "Customer Type",
    allCustomers: "All Customers",
    walkIn: "Walk-in",
    registered: "Registered",
    customer: "Customer",
    paymentStatus: "Payment Status",
    allStatuses: "All Statuses",
    paid: "Paid",
    partial: "Partial",
    unpaid: "Unpaid",
    sortBy: "Sort By",
    sortOrder: "Order",
    ascending: "Ascending",
    descending: "Descending",
    amount: "Amount",
    date: "Date",
    invoiceNo: "Invoice No",
    items: "Items",
    total: "Total",
    paidAmount: "Paid",
    dueAmount: "Due",
    actions: "Actions",
    view: "View",
    totalSales: "Total Sales",
    totalOrders: "Total Orders",
    totalPaid: "Total Paid",
    totalDue: "Total Due",
    averageOrderValue: "Average Order Value",
    totalItemsSold: "Total Items Sold",
    invoiceDetails: "Invoice Details",
    customerInfo: "Customer Information",
    paymentInfo: "Payment Information",
    discountTax: "Discount & Tax",
    
    // Purchase Report
    purchaseReport: "Purchase Report",
    purchaseDataFor: "Purchase data for",
    supplier: "Supplier",
    allSuppliers: "All Suppliers",
    deliveryStatus: "Delivery Status",
    allDeliveryStatuses: "All Statuses",
    delivered: "Delivered",
    ordered: "Ordered",
    rejected: "Rejected",
    isRejected: "Is Rejected",
    totalPurchases: "Total Purchases",
    totalPaid: "Total Paid",
    totalDue: "Total Due",
    topSupplier: "Top Supplier",
    purchaseDetails: "Purchase Details",
    
    // Inventory Report
    inventoryReport: "Inventory Report",
    inventoryAnalysis: "Comprehensive inventory analysis with auto-tagging",
    category: "Category",
    allCategories: "All Categories",
    productName: "Product Name",
    searchByName: "Search by name",
    productCode: "Product Code",
    searchByCode: "Search by code",
    tag: "Tag",
    allTags: "All Tags",
    deadStock: "Dead Stock",
    lowStock: "Low Stock",
    fastSelling: "Fast Selling",
    overstock: "Overstock",
    expired: "Expired",
    nearExpiry: "Near Expiry",
    highReturn: "High Return",
    sortByDefault: "Default",
    sortByTag: "Tag",
    sortByHighestSales: "Highest Sales",
    sortByLowestSales: "Lowest Sales",
    sortByMostReturned: "Most Returned",
    sortByExpiryDate: "Expiry Date",
    sortByStockLevel: "Stock Level",
    totalProducts: "Total Products",
    deadStockCount: "Dead Stock",
    lowStockCount: "Low Stock",
    fastSellingCount: "Fast Selling",
    overstockCount: "Overstock",
    expiredCount: "Expired",
    nearExpiryCount: "Near Expiry",
    highReturnCount: "High Return",
    
    // Customer Report
    customerReport: "Customer Report",
    customerAnalytics: "Customer analytics and ranking",
    allTypes: "All",
    totalSpent: "Total Spent",
    totalOrders: "Total Orders",
    lastPurchase: "Last Purchase",
    totalCustomers: "Total Customers",
    averageOrderValue: "Average Order Value",
    topCustomer: "Top Customer",
    customerDetails: "Customer Details",
    
    // Supplier Report
    supplierReport: "Supplier Report",
    supplierAnalytics: "Supplier analytics and payment tracking",
    totalSuppliers: "Total Suppliers",
    totalBills: "Total Bills",
    lastPurchase: "Last Purchase",
    supplierDetails: "Supplier Details",
    
    // Expense Report
    expenseReport: "Expense Report",
    expenseAnalytics: "Expense analytics and breakdown",
    totalExpenses: "Total Expenses",
    averageExpense: "Average Expense",
    highestExpense: "Highest Expense",
    expenseByCategory: "Expense by Category",
    expenseByType: "Expense by Type",
    expenseTransactions: "Expense Transactions",
    date: "Date",
    description: "Description",
    category: "Category",
    type: "Type",
    amount: "Amount",
    paymentMethod: "Payment Method",
    source: "Source",
    
    // Staff Report
    staffReport: "Staff Report",
    staffPerformance: "Comprehensive staff performance, attendance, and salary report",
    staffMember: "Staff Member",
    allStaff: "All Staff",
    totalStaff: "Total Staff",
    totalSalariesPaid: "Total Salaries Paid",
    averageSalary: "Average Salary",
    totalAdvances: "Total Advances",
    totalDeductions: "Total Deductions",
    totalAttendance: "Total Attendance",
    attendanceRate: "Attendance Rate",
    ordersHandled: "Orders Handled",
    staffDetails: "Staff Details",
    exportPdf: "Export PDF",
    
    // Credits & Debits Report
    creditsDebitsReport: "Credits & Debits Report",
    trackTransactions: "Track credit account transactions and balances",
    accountType: "Account Type",
    allTypes: "All Types",
    personal: "Personal",
    business: "Business",
    others: "Others",
    status: "Status",
    allStatuses: "All Statuses",
    toPay: "To Pay",
    toReceive: "To Receive",
    cleared: "Cleared",
    accountLedger: "Account Ledger",
    accountName: "Account Name",
    accountTypeLabel: "Account Type",
    phone: "Phone",
    currentBalance: "Current Balance",
    transactionHistory: "Transaction History",
    description: "Description",
    source: "Source",
    debit: "Debit",
    credit: "Credit",
    balance: "Balance",
    noTransactions: "No transactions found",
    
    // Main Business Report
    mainBusinessReport: "Main Business Report",
    businessOverview: "Comprehensive business overview and financial summary",
    totalSales: "Total Sales",
    totalPurchases: "Total Purchases",
    totalExpenses: "Total Expenses",
    netProfit: "Net Profit",
    grossProfit: "Gross Profit",
    profitMargin: "Profit Margin",
    salesByCategory: "Sales by Category",
    purchasesByCategory: "Purchases by Category",
    expensesByCategory: "Expenses by Category",
    topSellingProducts: "Top Selling Products",
    topSuppliers: "Top Suppliers",
    topCustomers: "Top Customers",
  },
  ur: {
    // Common
    reports: "رپورٹس",
    refresh: "تازہ کاری",
    filters: "فلٹرز",
    search: "تلاش",
    apply: "لاگو کریں",
    cancel: "منسوخ کریں",
    viewDetails: "تفصیلات دیکھیں",
    noDataFound: "کوئی ڈیٹا نہیں ملا",
    loading: "لوڈ ہو رہا ہے...",
    
    // Period filters
    period: "مدت",
    today: "آج",
    thisMonth: "اس مہینے",
    last3Months: "پچھلے 3 مہینے",
    thisYear: "اس سال",
    customRange: "حسب ضرورت حد",
    fromDate: "سے تاریخ",
    toDate: "تک تاریخ",
    
    // Sales Report
    salesReport: "فروخت رپورٹ",
    salesDataFor: "فروخت کا ڈیٹا",
    customerType: "گاہک کی قسم",
    allCustomers: "تمام گاہک",
    walkIn: "واک ان",
    registered: "رجسٹرڈ",
    customer: "گاہک",
    paymentStatus: "ادائیگی کی حیثیت",
    allStatuses: "تمام حیثیت",
    paid: "ادا شدہ",
    partial: "جزوی",
    unpaid: "غیر ادا",
    sortBy: "ترتیب دیں",
    sortOrder: "ترتیب",
    ascending: "بڑھتی ہوئی",
    descending: "گھرتی ہوئی",
    amount: "رقم",
    date: "تاریخ",
    invoiceNo: "انوائس نمبر",
    items: "اشیاء",
    total: "کل",
    paidAmount: "ادا شدہ",
    dueAmount: "باقی",
    actions: "اقدامات",
    view: "دیکھیں",
    totalSales: "کل فروخت",
    totalOrders: "کل آرڈرز",
    totalPaid: "کل ادا شدہ",
    totalDue: "کل باقی",
    averageOrderValue: "اوسط آرڈر ویلیو",
    totalItemsSold: "کل فروخت شدہ اشیاء",
    invoiceDetails: "انوائس کی تفصیلات",
    customerInfo: "گاہک کی معلومات",
    paymentInfo: "ادائیگی کی معلومات",
    discountTax: "ڈسکاؤنٹ اور ٹیکس",
    
    // Purchase Report
    purchaseReport: "خریداری رپورٹ",
    purchaseDataFor: "خریداری کا ڈیٹا",
    supplier: "سپلائر",
    allSuppliers: "تمام سپلائرز",
    deliveryStatus: "ڈیلیوری کی حیثیت",
    allDeliveryStatuses: "تمام حیثیت",
    delivered: "پہنچا دیا",
    ordered: "آرڈر دیا",
    rejected: "مسترد",
    isRejected: "مسترد ہے",
    totalPurchases: "کل خریداری",
    totalPaid: "کل ادا شدہ",
    totalDue: "کل باقی",
    topSupplier: "بہترین سپلائر",
    purchaseDetails: "خریداری کی تفصیلات",
    
    // Inventory Report
    inventoryReport: "انوینٹری رپورٹ",
    inventoryAnalysis: "مکمل انوینٹری تجزیہ خودکار ٹیگنگ کے ساتھ",
    category: "زمرہ",
    allCategories: "تمام زمرے",
    productName: "پروڈکٹ کا نام",
    searchByName: "نام سے تلاش کریں",
    productCode: "پروڈکٹ کوڈ",
    searchByCode: "کوڈ سے تلاش کریں",
    tag: "ٹیگ",
    allTags: "تمام ٹیگز",
    deadStock: "ڈیڈ اسٹاک",
    lowStock: "کم اسٹاک",
    fastSelling: "تیز فروخت",
    overstock: "زیادہ اسٹاک",
    expired: "ختم ہو چکا",
    nearExpiry: "ختم ہونے قریب",
    highReturn: "زیادہ واپسی",
    sortByDefault: "ڈیفالٹ",
    sortByTag: "ٹیگ",
    sortByHighestSales: "سب سے زیادہ فروخت",
    sortByLowestSales: "سب سے کم فروخت",
    sortByMostReturned: "سب سے زیادہ واپسی",
    sortByExpiryDate: "ختم ہونے کی تاریخ",
    sortByStockLevel: "اسٹاک لیول",
    totalProducts: "کل پروڈکٹس",
    deadStockCount: "ڈیڈ اسٹاک",
    lowStockCount: "کم اسٹاک",
    fastSellingCount: "تیز فروخت",
    overstockCount: "زیادہ اسٹاک",
    expiredCount: "ختم ہو چکے",
    nearExpiryCount: "ختم ہونے قریب",
    highReturnCount: "زیادہ واپسی",
    
    // Customer Report
    customerReport: "گاہک رپورٹ",
    customerAnalytics: "گاہک کے تجزیات اور درجہ بندی",
    allTypes: "تمام",
    totalSpent: "کل خرچ",
    totalOrders: "کل آرڈرز",
    lastPurchase: "آخری خریداری",
    totalCustomers: "کل گاہک",
    averageOrderValue: "اوسط آرڈر ویلیو",
    topCustomer: "بہترین گاہک",
    customerDetails: "گاہک کی تفصیلات",
    
    // Supplier Report
    supplierReport: "سپلائر رپورٹ",
    supplierAnalytics: "سپلائر کے تجزیات اور ادائیگی کی ٹریکنگ",
    totalSuppliers: "کل سپلائرز",
    totalBills: "کل بلز",
    lastPurchase: "آخری خریداری",
    supplierDetails: "سپلائر کی تفصیلات",
    
    // Expense Report
    expenseReport: "اخراجات رپورٹ",
    expenseAnalytics: "اخراجات کے تجزیات اور تفصیل",
    totalExpenses: "کل اخراجات",
    averageExpense: "اوسط اخراجات",
    highestExpense: "سب سے زیادہ اخراجات",
    expenseByCategory: "زمرہ کے لحاظ سے اخراجات",
    expenseByType: "قسم کے لحاظ سے اخراجات",
    expenseTransactions: "اخراجات کی لین دین",
    date: "تاریخ",
    description: "تفصیل",
    category: "زمرہ",
    type: "قسم",
    amount: "رقم",
    paymentMethod: "ادائیگی کا طریقہ",
    source: "ماخذ",
    
    // Staff Report
    staffReport: "اسٹاف رپورٹ",
    staffPerformance: "مکمل اسٹاف کارکردگی، حاضری اور تنخواہ رپورٹ",
    staffMember: "اسٹاف ممبر",
    allStaff: "تمام اسٹاف",
    totalStaff: "کل اسٹاف",
    totalSalariesPaid: "کل تنخواہ ادا شدہ",
    averageSalary: "اوسط تنخواہ",
    totalAdvances: "کل پیشگی",
    totalDeductions: "کل کٹوتی",
    totalAttendance: "کل حاضری",
    attendanceRate: "حاضری کی شرح",
    ordersHandled: "آرڈرز ہینڈل کیے",
    staffDetails: "اسٹاف کی تفصیلات",
    exportPdf: "پی ڈی ایف ایکسپورٹ کریں",
    
    // Credits & Debits Report
    creditsDebitsReport: "کریڈٹ اور ڈیبٹ رپورٹ",
    trackTransactions: "کریڈٹ اکاؤنٹ لین دین اور بیلنس ٹریک کریں",
    accountType: "اکاؤنٹ کی قسم",
    allTypes: "تمام اقسام",
    personal: "ذاتی",
    business: "کاروباری",
    others: "دیگر",
    status: "حیثیت",
    allStatuses: "تمام حیثیت",
    toPay: "ادا کرنا ہے",
    toReceive: "وصول کرنا ہے",
    cleared: "صاف",
    accountLedger: "اکاؤنٹ لیجر",
    accountName: "اکاؤنٹ کا نام",
    accountTypeLabel: "اکاؤنٹ کی قسم",
    phone: "فون",
    currentBalance: "موجودہ بیلنس",
    transactionHistory: "لین دین کی تاریخ",
    description: "تفصیل",
    source: "ماخذ",
    debit: "ڈیبٹ",
    credit: "کریڈٹ",
    balance: "بیلنس",
    noTransactions: "کوئی لین دین نہیں ملا",
    
    // Main Business Report
    mainBusinessReport: "مین کاروبار رپورٹ",
    businessOverview: "مکمل کاروبار کا جائزہ اور مالیاتی خلاصہ",
    totalSales: "کل فروخت",
    totalPurchases: "کل خریداری",
    totalExpenses: "کل اخراجات",
    netProfit: "خالص منافع",
    grossProfit: "گروس منافع",
    profitMargin: "منافع کا مارجن",
    salesByCategory: "زمرہ کے لحاظ سے فروخت",
    purchasesByCategory: "زمرہ کے لحاظ سے خریداری",
    expensesByCategory: "زمرہ کے لحاظ سے اخراجات",
    topSellingProducts: "بہترین فروخت پروڈکٹس",
    topSuppliers: "بہترین سپلائرز",
    topCustomers: "بہترین گاہک",
  },
  ur_en: {
    // Common
    reports: "رپورٹس / Reports",
    refresh: "تازہ کاری / Refresh",
    filters: "فلٹرز / Filters",
    search: "تلاش / Search",
    apply: "لاگو کریں / Apply",
    cancel: "منسوخ کریں / Cancel",
    viewDetails: "تفصیلات دیکھیں / View Details",
    noDataFound: "کوئی ڈیٹا نہیں ملا / No data found",
    loading: "لوڈ ہو رہا ہے / Loading...",
    
    // Period filters
    period: "مدت / Period",
    today: "آج / Today",
    thisMonth: "اس مہینے / This Month",
    last3Months: "پچھلے 3 مہینے / Last 3 Months",
    thisYear: "اس سال / This Year",
    customRange: "حسب ضرورت حد / Custom Range",
    fromDate: "سے تاریخ / From Date",
    toDate: "تک تاریخ / To Date",
    
    // Sales Report
    salesReport: "فروخت رپورٹ / Sales Report",
    salesDataFor: "فروخت کا ڈیٹا / Sales data for",
    customerType: "گاہک کی قسم / Customer Type",
    allCustomers: "تمام گاہک / All Customers",
    walkIn: "واک ان / Walk-in",
    registered: "رجسٹرڈ / Registered",
    customer: "گاہک / Customer",
    paymentStatus: "ادائیگی کی حیثیت / Payment Status",
    allStatuses: "تمام حیثیت / All Statuses",
    paid: "ادا شدہ / Paid",
    partial: "جزوی / Partial",
    unpaid: "غیر ادا / Unpaid",
    sortBy: "ترتیب دیں / Sort By",
    sortOrder: "ترتیب / Order",
    ascending: "بڑھتی ہوئی / Ascending",
    descending: "گھرتی ہوئی / Descending",
    amount: "رقم / Amount",
    date: "تاریخ / Date",
    invoiceNo: "انوائس نمبر / Invoice No",
    items: "اشییں / Items",
    total: "کل / Total",
    paidAmount: "ادا شدہ / Paid",
    dueAmount: "باقی / Due",
    actions: "اقدامات / Actions",
    view: "دیکھیں / View",
    totalSales: "کل فروخت / Total Sales",
    totalOrders: "کل آرڈرز / Total Orders",
    totalPaid: "کل ادا شدہ / Total Paid",
    totalDue: "کل باقی / Total Due",
    averageOrderValue: "اوسط آرڈر ویلیو / Average Order Value",
    totalItemsSold: "کل فروخت شدہ اشیاء / Total Items Sold",
    invoiceDetails: "انوائس کی تفصیلات / Invoice Details",
    customerInfo: "گاہک کی معلومات / Customer Information",
    paymentInfo: "ادائیگی کی معلومات / Payment Information",
    discountTax: "ڈسکاؤنٹ اور ٹیکس / Discount & Tax",
    
    // Purchase Report
    purchaseReport: "خریداری رپورٹ / Purchase Report",
    purchaseDataFor: "خریداری کا ڈیٹا / Purchase data for",
    supplier: "سپلائر / Supplier",
    allSuppliers: "تمام سپلائرز / All Suppliers",
    deliveryStatus: "ڈیلیوری کی حیثیت / Delivery Status",
    allDeliveryStatuses: "تمام حیثیت / All Statuses",
    delivered: "پہنچا دیا / Delivered",
    ordered: "آرڈر دیا / Ordered",
    rejected: "مسترد / Rejected",
    isRejected: "مسترد ہے / Is Rejected",
    totalPurchases: "کل خریداری / Total Purchases",
    totalPaid: "کل ادا شدہ / Total Paid",
    totalDue: "کل باقی / Total Due",
    topSupplier: "بہترین سپلائر / Top Supplier",
    purchaseDetails: "خریداری کی تفصیلات / Purchase Details",
    
    // Inventory Report
    inventoryReport: "انوینٹری رپورٹ / Inventory Report",
    inventoryAnalysis: "مکمل انوینٹری تجزیہ خودکار ٹیگنگ کے ساتھ / Comprehensive inventory analysis with auto-tagging",
    category: "زمرہ / Category",
    allCategories: "تمام زمرے / All Categories",
    productName: "پروڈکٹ کا نام / Product Name",
    searchByName: "نام سے تلاش کریں / Search by name",
    productCode: "پروڈکٹ کوڈ / Product Code",
    searchByCode: "کوڈ سے تلاش کریں / Search by code",
    tag: "ٹیگ / Tag",
    allTags: "تمام ٹیگز / All Tags",
    deadStock: "ڈیڈ اسٹاک / Dead Stock",
    lowStock: "کم اسٹاک / Low Stock",
    fastSelling: "تیز فروخت / Fast Selling",
    overstock: "زیادہ اسٹاک / Overstock",
    expired: "ختم ہو چکا / Expired",
    nearExpiry: "ختم ہونے قریب / Near Expiry",
    highReturn: "زیادہ واپسی / High Return",
    sortByDefault: "ڈیفالٹ / Default",
    sortByTag: "ٹیگ / Tag",
    sortByHighestSales: "سب سے زیادہ فروخت / Highest Sales",
    sortByLowestSales: "سب سے کم فروخت / Lowest Sales",
    sortByMostReturned: "سب سے زیادہ واپسی / Most Returned",
    sortByExpiryDate: "ختم ہونے کی تاریخ / Expiry Date",
    sortByStockLevel: "اسٹاک لیول / Stock Level",
    totalProducts: "کل پروڈکٹس / Total Products",
    deadStockCount: "ڈیڈ اسٹاک / Dead Stock",
    lowStockCount: "کم اسٹاک / Low Stock",
    fastSellingCount: "تیز فروخت / Fast Selling",
    overstockCount: "زیادہ اسٹاک / Overstock",
    expiredCount: "ختم ہو چکے / Expired",
    nearExpiryCount: "ختم ہونے قریب / Near Expiry",
    highReturnCount: "زیادہ واپسی / High Return",
    
    // Customer Report
    customerReport: "گاہک رپورٹ / Customer Report",
    customerAnalytics: "گاہک کے تجزیات اور درجہ بندی / Customer analytics and ranking",
    allTypes: "تمام / All",
    totalSpent: "کل خرچ / Total Spent",
    totalOrders: "کل آرڈرز / Total Orders",
    lastPurchase: "آخری خریداری / Last Purchase",
    totalCustomers: "کل گاہک / Total Customers",
    averageOrderValue: "اوسط آرڈر ویلیو / Average Order Value",
    topCustomer: "بہترین گاہک / Top Customer",
    customerDetails: "گاہک کی تفصیلات / Customer Details",
    
    // Supplier Report
    supplierReport: "سپلائر رپورٹ / Supplier Report",
    supplierAnalytics: "سپلائر کے تجزیات اور ادائیگی کی ٹریکنگ / Supplier analytics and payment tracking",
    totalSuppliers: "کل سپلائرز / Total Suppliers",
    totalBills: "کل بلز / Total Bills",
    lastPurchase: "آخری خریداری / Last Purchase",
    supplierDetails: "سپلائر کی تفصیلات / Supplier Details",
    
    // Expense Report
    expenseReport: "اخراجات رپورٹ / Expense Report",
    expenseAnalytics: "اخراجات کے تجزیات اور تفصیل / Expense analytics and breakdown",
    totalExpenses: "کل اخراجات / Total Expenses",
    averageExpense: "اوسط اخراجات / Average Expense",
    highestExpense: "سب سے زیادہ اخراجات / Highest Expense",
    expenseByCategory: "زمرہ کے لحاظ سے اخراجات / Expense by Category",
    expenseByType: "قسم کے لحاظ سے اخراجات / Expense by Type",
    expenseTransactions: "اخراجات کی لین دین / Expense Transactions",
    date: "تاریخ / Date",
    description: "تفصیل / Description",
    category: "زمرہ / Category",
    type: "قسم / Type",
    amount: "رقم / Amount",
    paymentMethod: "ادائیگی کا طریقہ / Payment Method",
    source: "ماخذ / Source",
    
    // Staff Report
    staffReport: "اسٹاف رپورٹ / Staff Report",
    staffPerformance: "مکمل اسٹاف کارکردگی، حاضری اور تنخواہ رپورٹ / Comprehensive staff performance, attendance, and salary report",
    staffMember: "اسٹاف ممبر / Staff Member",
    allStaff: "تمام اسٹاف / All Staff",
    totalStaff: "کل اسٹاف / Total Staff",
    totalSalariesPaid: "کل تنخواہ ادا شدہ / Total Salaries Paid",
    averageSalary: "اوسط تنخواہ / Average Salary",
    totalAdvances: "کل پیشگی / Total Advances",
    totalDeductions: "کل کٹوتی / Total Deductions",
    totalAttendance: "کل حاضری / Total Attendance",
    attendanceRate: "حاضری کی شرح / Attendance Rate",
    ordersHandled: "آرڈرز ہینڈل کیے / Orders Handled",
    staffDetails: "اسٹاف کی تفصیلات / Staff Details",
    exportPdf: "پی ڈی ایف ایکسپورٹ کریں / Export PDF",
    
    // Credits & Debits Report
    creditsDebitsReport: "کریڈٹ اور ڈیبٹ رپورٹ / Credits & Debits Report",
    trackTransactions: "کریڈٹ اکاؤنٹ لین دین اور بیلنس ٹریک کریں / Track credit account transactions and balances",
    accountType: "اکاؤنٹ کی قسم / Account Type",
    allTypes: "تمام اقسام / All Types",
    personal: "ذاتی / Personal",
    business: "کاروباری / Business",
    others: "دیگر / Others",
    status: "حیثیت / Status",
    allStatuses: "تمام حیثیت / All Statuses",
    toPay: "ادا کرنا ہے / To Pay",
    toReceive: "وصول کرنا ہے / To Receive",
    cleared: "صاف / Cleared",
    accountLedger: "اکاؤنٹ لیجر / Account Ledger",
    accountName: "اکاؤنٹ کا نام / Account Name",
    accountTypeLabel: "اکاؤنٹ کی قسم / Account Type",
    phone: "فون / Phone",
    currentBalance: "موجودہ بیلنس / Current Balance",
    transactionHistory: "لین دین کی تاریخ / Transaction History",
    description: "تفصیل / Description",
    source: "ماخذ / Source",
    debit: "ڈیبٹ / Debit",
    credit: "کریڈٹ / Credit",
    balance: "بیلنس / Balance",
    noTransactions: "کوئی لین دین نہیں ملا / No transactions found",
    
    // Main Business Report
    mainBusinessReport: "مین کاروبار رپورٹ / Main Business Report",
    businessOverview: "مکمل کاروبار کا جائزہ اور مالیاتی خلاصہ / Comprehensive business overview and financial summary",
    totalSales: "کل فروخت / Total Sales",
    totalPurchases: "کل خریداری / Total Purchases",
    totalExpenses: "کل اخراجات / Total Expenses",
    netProfit: "خالص منافع / Net Profit",
    grossProfit: "گروس منافع / Gross Profit",
    profitMargin: "منافع کا مارجن / Profit Margin",
    salesByCategory: "زمرہ کے لحاظ سے فروخت / Sales by Category",
    purchasesByCategory: "زمرہ کے لحاظ سے خریداری / Purchases by Category",
    expensesByCategory: "زمرہ کے لحاظ سے اخراجات / Expenses by Category",
    topSellingProducts: "بہترین فروخت پروڈکٹس / Top Selling Products",
    topSuppliers: "بہترین سپلائرز / Top Suppliers",
    topCustomers: "بہترین گاہک / Top Customers",
  },
};

export const getReportsLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return reportsLabels[langKey] || reportsLabels.en;
};
