export const productLabels = {
  en: {
    // Page titles
    productManagement: "Product Management",
    manageProducts: "Manage your shop products",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    productCategories: "Product Categories",
    productSubCategories: "Product Sub-Categories",
    
    // Form labels
    name: "Name",
    sku: "SKU",
    barcode: "Barcode",
    category: "Category",
    subCategory: "Sub-Category",
    price: "Price",
    cost: "Cost",
    stock: "Stock",
    minStock: "Min Stock",
    maxStock: "Max Stock",
    description: "Description",
    image: "Image",
    supplier: "Supplier",
    brand: "Brand",
    unit: "Unit",
    weight: "Weight",
    dimensions: "Dimensions",
    taxRate: "Tax Rate",
    discount: "Discount",
    
    // Units
    pieces: "Pieces",
    kg: "Kg",
    liters: "Liters",
    meters: "Meters",
    boxes: "Boxes",
    countPcs: "Count (pcs)",
    weightMg: "Weight (mg)",
    weightG: "Weight (g)",
    weightKg: "Weight (kg)",
    volumeMl: "Volume (ml)",
    volumeL: "Volume (L)",
    
    // CRUD form
    productImage: "Product Image",
    changeImage: "Change image",
    clickOrDrag: "Click or drag to upload",
    pngJpgWebp: "PNG, JPG, WebP — max 5MB",
    onlyPngJpg: "Only PNG, JPG, JPEG or WebP allowed",
    maxFileSize: "Max file size is 5MB",
    productName: "Product Name",
    productNameRequired: "Product Name is required",
    productCode: "Product Code",
    brandName: "Brand Name",
    brandNameRequired: "Brand Name is required",
    barcode: "Barcode",
    barcodeRequired: "Barcode is required",
    scanOrType: "Scan or type",
    description: "Description",
    descriptionRequired: "Description is required",
    productDescription: "Product description",
    selectCategory: "Select category",
    selectSubCategory: "Select sub category",
    selectUnit: "Select unit",
    selectTaxType: "Select tax type",
    defaultCostPrice: "Default Cost Price",
    defaultRetailPrice: "Default Retail Price",
    defaultWholesalePrice: "Default Wholesale Price",
    taxPercent: "Tax Percent",
    taxType: "Tax Type",
    percentage: "Percentage",
    fixed: "Fixed",
    minStockLevel: "Min Stock Level",
    minStockLevelRequired: "Min Stock Level is required",
    maxStockLevel: "Max Stock Level",
    maxStockLevelRequired: "Max Stock Level is required",
    maxGreaterThanMin: "Max must be greater than Min",
    allowNegativeStock: "Allow Negative Stock",
    allowDiscount: "Allow Discount",
    maxDiscountPercent: "Max Discount %",
    mustBeGreaterThanZero: "Must be greater than 0",
    rackLocation: "Rack Location",
    active: "Active",
    showMoreOptions: "Show more options",
    hideAdditionalFields: "Hide additional fields",
    scan: "Scan",
    new: "New",
    saveProduct: "Save Product",
    updateProduct: "Update Product",
    saving: "Saving...",
    loadingProduct: "Loading product...",
    fixErrors: "Fix {count} error(s) before submitting",
    productImageRequired: "Product Image is required",
    categoryRequired: "Category is required",
    subCategoryRequired: "Sub Category is required",
    unitRequired: "Unit is required",
    
    // Category CRUD
    addNewCategory: "Add New Category",
    editCategory: "Edit Category",
    categoryName: "Category Name",
    categoryNameRequired: "Category name is required",
    categoryDescription: "Category Description",
    categoryPlaceholder: "Enter category name",
    categoryDescriptionPlaceholder: "Enter category description",
    saveCategory: "Save Category",
    updateCategory: "Update Category",
    categoryCreated: "Category created successfully",
    categoryUpdated: "Category updated successfully",
    categoryLoading: "Loading category...",
    somethingWentWrong: "Something went wrong",
    
    // Sub Category CRUD
    addNewSubCategory: "Add New Sub-Category",
    editSubCategory: "Edit Sub-Category",
    subCategoryName: "Sub-Category Name",
    subCategoryNameRequired: "Sub-Category name is required",
    subCategoryDescription: "Sub-Category Description",
    subCategoryPlaceholder: "Enter sub-category name",
    subCategoryDescriptionPlaceholder: "Enter sub-category description",
    saveSubCategory: "Save Sub-Category",
    updateSubCategory: "Update Sub-Category",
    subCategoryCreated: "Sub-Category created successfully",
    subCategoryUpdated: "Sub-Category updated successfully",
    subCategoryLoading: "Loading sub-category...",
    
    // Table headers
    actions: "Actions",
    status: "Status",
    stockLevel: "Stock Level",
    
    // Buttons
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    add: "Add",
    
    // Messages
    loading: "Loading...",
    noProductsFound: "No products found",
    noCategoriesFound: "No categories found",
    noSubCategoriesFound: "No sub-categories found",
    productCreated: "Product created successfully",
    productUpdated: "Product updated successfully",
    productDeleted: "Product deleted successfully",
    categoryCreated: "Category created successfully",
    categoryUpdated: "Category updated successfully",
    categoryDeleted: "Category deleted successfully",
    subCategoryCreated: "Sub-category created successfully",
    subCategoryUpdated: "Sub-category updated successfully",
    subCategoryDeleted: "Sub-category deleted successfully",
    failedToCreate: "Failed to create",
    failedToUpdate: "Failed to update",
    failedToDelete: "Failed to delete",
    deleteConfirm: "Are you sure you want to delete this?",
    
    // Filters
    allCategories: "All Categories",
    filterByCategory: "Filter by Category",
    filterByStatus: "Filter by Status",
    search: "Search",
    searchProducts: "Search products...",
    clearFilters: "Clear Filters",
    productFilters: "Product Filters",
    applyFilters: "Apply Filters",
    resetFilters: "Reset Filters",
    allStock: "All Stock",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    lowStock: "Low Stock (< 5)",
    allStatus: "All Status",
    priceRange: "Price Range",
    allPrices: "All Prices",
    underRs100: "Under Rs 100",
    rs100to500: "Rs 100 - 500",
    rs500to1000: "Rs 500 - 1000",
    rs1000to5000: "Rs 1000 - 5000",
    aboveRs5000: "Above Rs 5000",
    min: "Min",
    max: "Max",
    noBrandsAvailable: "No brands available",
    
    // Status
    active: "Active",
    inactive: "Inactive",
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    
    // Stock levels
    inStock: "In Stock",
    lowStockWarning: "Low Stock Warning",
    
    // Summary
    totalProducts: "Total Products",
    totalCategories: "Total Categories",
    totalStock: "Total Stock",
    totalValue: "Total Value",
  },
  ur: {
    // Page titles
    productManagement: "پروڈکٹ مینجمنٹ",
    manageProducts: "اپنے دکان کے پروڈکٹس کا انتظام کریں",
    addProduct: "پروڈکٹ شامل کریں",
    editProduct: "پروڈکٹ میں ترمیم کریں",
    productCategories: "پروڈکٹ زمرے",
    productSubCategories: "پروڈکٹ ذیلی زمرے",
    
    // Form labels
    name: "نام",
    sku: "SKU",
    barcode: "بارکوڈ",
    category: "زمرہ",
    subCategory: "ذیلی زمرہ",
    price: "قیمت",
    cost: "لاگت",
    stock: "اسٹاک",
    minStock: "کم از کم اسٹاک",
    maxStock: "زیادہ سے زیادہ اسٹاک",
    description: "تفصیل",
    image: "تصویر",
    supplier: "فراہم کنندہ",
    brand: "برانڈ",
    unit: "یونٹ",
    weight: "وزن",
    dimensions: "پیمائش",
    taxRate: "ٹیکس ریٹ",
    discount: "ڈسکاؤنٹ",
    
    // Units
    pieces: "پیس",
    kg: "کلوگرام",
    liters: "لیٹر",
    meters: "میٹر",
    boxes: "بوکس",
    countPcs: "تعداد (پیس)",
    weightMg: "وزن (mg)",
    weightG: "وزن (g)",
    weightKg: "وزن (kg)",
    volumeMl: "حجم (ml)",
    volumeL: "حجم (L)",
    
    // CRUD form
    productImage: "پروڈکٹ تصویر",
    changeImage: "تصویر تبدیل کریں",
    clickOrDrag: "اپ لوڈ کرنے کے لیے کلک کریں یا کھینچیں",
    pngJpgWebp: "PNG, JPG, WebP — زیادہ سے زیادہ 5MB",
    onlyPngJpg: "صرف PNG, JPG, JPEG یا WebP اجازت ہے",
    maxFileSize: "زیادہ سے زیادہ فائل سائز 5MB ہے",
    productName: "پروڈکٹ کا نام",
    productNameRequired: "پروڈکٹ کا نام درکار ہے",
    productCode: "پروڈکٹ کوڈ",
    brandName: "برانڈ کا نام",
    brandNameRequired: "برانڈ کا نام درکار ہے",
    barcode: "بارکوڈ",
    barcodeRequired: "بارکوڈ درکار ہے",
    scanOrType: "اسکین یا ٹائپ کریں",
    description: "تفصیل",
    descriptionRequired: "تفصیل درکار ہے",
    productDescription: "پروڈکٹ کی تفصیل",
    selectCategory: "زمرہ منتخب کریں",
    selectSubCategory: "ذیلی زمرہ منتخب کریں",
    selectUnit: "یونٹ منتخب کریں",
    selectTaxType: "ٹیکس کی قسم منتخب کریں",
    defaultCostPrice: "ڈیفالٹ لاگت قیمت",
    defaultRetailPrice: "ڈیفالٹ خوردہ قیمت",
    defaultWholesalePrice: "ڈیفالٹ ہوکری قیمت",
    taxPercent: "ٹیکس فیصد",
    taxType: "ٹیکس کی قسم",
    percentage: "فیصد",
    fixed: "فکسڈ",
    minStockLevel: "کم از کم اسٹاک لیول",
    minStockLevelRequired: "کم از کم اسٹاک لیول درکار ہے",
    maxStockLevel: "زیادہ سے زیادہ اسٹاک لیول",
    maxStockLevelRequired: "زیادہ سے زیادہ اسٹاک لیول درکار ہے",
    maxGreaterThanMin: "زیادہ سے زیادہ کم سے زیادہ ہونا چاہیے",
    allowNegativeStock: "منفی اسٹاک کی اجازت دیں",
    allowDiscount: "ڈسکاؤنٹ کی اجازت دیں",
    maxDiscountPercent: "زیادہ سے زیادہ ڈسکاؤنٹ %",
    mustBeGreaterThanZero: "صفر سے زیادہ ہونا چاہیے",
    rackLocation: "ریک کی جگہ",
    active: "فعال",
    showMoreOptions: "مزید آپشنز دکھائیں",
    hideAdditionalFields: "اضافی فیلڈز چھپائیں",
    scan: "اسکین",
    new: "نیا",
    saveProduct: "پروڈکٹ محفوظ کریں",
    updateProduct: "پروڈکٹ اپ ڈیٹ کریں",
    saving: "محفوظ ہو رہا ہے...",
    loadingProduct: "پروڈکٹ لوڈ ہو رہا ہے...",
    fixErrors: "جمع کرنے سے پہلے {count} غلطی(اں) ٹھیک کریں",
    productImageRequired: "پروڈکٹ تصویر درکار ہے",
    categoryRequired: "زمرہ درکار ہے",
    subCategoryRequired: "ذیلی زمرہ درکار ہے",
    unitRequired: "یونٹ درکار ہے / Unit is required",
    
    // Category CRUD
    addNewCategory: "نیا زمرہ شامل کریں / Add New Category",
    editCategory: "زمرہ میں ترمیم کریں / Edit Category",
    categoryName: "زمرہ کا نام / Category Name",
    categoryNameRequired: "زمرہ کا نام درکار ہے / Category name is required",
    categoryDescription: "زمرہ کی تفصیل / Category Description",
    categoryPlaceholder: "زمرہ کا نام لکھیں / Category ka naam likhein",
    categoryDescriptionPlaceholder: "زمرہ کی تفصیل لکھیں / Category description likhein",
    saveCategory: "زمرہ محفوظ کریں / Save Category",
    updateCategory: "زمرہ اپ ڈیٹ کریں / Update Category",
    categoryCreated: "زمرہ کامیابی سے بنایا گیا / Category created successfully",
    categoryUpdated: "زمرہ کامیابی سے اپ ڈیٹ ہو گیا / Category updated successfully",
    categoryLoading: "زمرہ لوڈ ہو رہا ہے / Category load ho raha hai...",
    somethingWentWrong: "کچھ غلط ہو گیا / Something went wrong",
    
    // Sub Category CRUD
    addNewSubCategory: "نیا ذیلی زمرہ شامل کریں / Add New Sub-Category",
    editSubCategory: "ذیلی زمرہ میں ترمیم کریں / Edit Sub-Category",
    subCategoryName: "ذیلی زمرہ کا نام / Sub-Category Name",
    subCategoryNameRequired: "ذیلی زمرہ کا نام درکار ہے / Sub-Category name is required",
    subCategoryDescription: "ذیلی زمرہ کی تفصیل / Sub-Category Description",
    subCategoryPlaceholder: "ذیلی زمرہ کا نام لکھیں / Sub-Category ka naam likhein",
    subCategoryDescriptionPlaceholder: "ذیلی زمرہ کی تفصیل لکھیں / Sub-Category description likhein",
    saveSubCategory: "ذیلی زمرہ محفوظ کریں / Save Sub-Category",
    updateSubCategory: "ذیلی زمرہ اپ ڈیٹ کریں / Update Sub-Category",
    subCategoryCreated: "ذیلی زمرہ کامیابی سے بنایا گیا / Sub-Category created successfully",
    subCategoryUpdated: "ذیلی زمرہ کامیابی سے اپ ڈیٹ ہو گیا / Sub-Category updated successfully",
    subCategoryLoading: "ذیلی زمرہ لوڈ ہو رہا ہے / Sub-Category load ho raha hai...",
    
    // Table headers
    actions: "اقدامات",
    status: "حیثیت",
    stockLevel: "اسٹاک لیول",
    
    // Buttons
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    delete: "حذف کریں",
    edit: "ترمیم کریں",
    view: "دیکھیں",
    add: "شامل کریں",
    
    // Messages
    loading: "لوڈ ہو رہا ہے...",
    noProductsFound: "کوئی پروڈکٹ نہیں ملا",
    noCategoriesFound: "کوئی زمرہ نہیں ملا",
    noSubCategoriesFound: "کوئی ذیلی زمرہ نہیں ملا",
    productCreated: "پروڈکٹ کامیابی سے بنایا گیا",
    productUpdated: "پروڈکٹ کامیابی سے اپ ڈیٹ ہو گیا",
    productDeleted: "پروڈکٹ کامیابی سے حذف ہو گیا",
    categoryCreated: "زمرہ کامیابی سے بنایا گیا",
    categoryUpdated: "زمرہ کامیابی سے اپ ڈیٹ ہو گیا",
    categoryDeleted: "زمرہ کامیابی سے حذف ہو گیا",
    subCategoryCreated: "ذیلی زمرہ کامیابی سے بنایا گیا",
    subCategoryUpdated: "ذیلی زمرہ کامیابی سے اپ ڈیٹ ہو گیا",
    subCategoryDeleted: "ذیلی زمرہ کامیابی سے حذف ہو گیا",
    failedToCreate: "بنانے میں ناکامی",
    failedToUpdate: "اپ ڈیٹ کرنے میں ناکامی",
    failedToDelete: "حذف کرنے میں ناکامی",
    deleteConfirm: "کیا آپ واقعی اسے حذف کرنا چاہتے ہیں؟",
    
    // Filters
    allCategories: "تمام زمرے / All Categories",
    filterByCategory: "زمرہ کے مطابق فلٹر کریں / Filter by Category",
    filterByStatus: "حیثیت کے مطابق فلٹر کریں / Filter by Status",
    search: "تلاش / Search",
    searchProducts: "پروڈکٹس تلاش کریں / Search products...",
    clearFilters: "فلٹر صاف کریں / Clear Filters",
    productFilters: "پروڈکٹ فلٹرز / Product Filters",
    applyFilters: "فلٹر لاگو کریں / Apply Filters",
    resetFilters: "فلٹر ری سیٹ کریں / Reset Filters",
    allStock: "تمام اسٹاک / All Stock",
    inStock: "اسٹاک میں / In Stock",
    outOfStock: "اسٹاک ختم / Out of Stock",
    lowStock: "کم اسٹاک (< 5) / Low Stock (< 5)",
    allStatus: "تمام حیثیت / All Status",
    priceRange: "قیمت کی حد / Price Range",
    allPrices: "تمام قیمت / All Prices",
    underRs100: "Rs 100 سے کم / Under Rs 100",
    rs100to500: "Rs 100 - 500",
    rs500to1000: "Rs 500 - 1000",
    rs1000to5000: "Rs 1000 - 5000",
    aboveRs5000: "Rs 5000 سے زیادہ / Above Rs 5000",
    min: "کم از کم / Min",
    max: "زیادہ سے زیادہ / Max",
    noBrandsAvailable: "کوئی برانڈ دستیاب نہیں / No brands available",
    
    // Status
    active: "فعال",
    inactive: "غیر فعال",
    lowStock: "کم اسٹاک",
    outOfStock: "اسٹاک ختم",
    
    // Stock levels
    inStock: "اسٹاک میں",
    lowStockWarning: "کم اسٹاک کی انتباہ",
    
    // Summary
    totalProducts: "کل پروڈکٹس",
    totalCategories: "کل زمرے",
    totalStock: "کل اسٹاک",
    totalValue: "کل قدر",
  },
  ur_en: {
    // Page titles
    productManagement: "پروڈکٹ مینجمنٹ / Product Management",
    manageProducts: "اپنے دکان کے پروڈکٹس کا انتظام کریں / Manage your shop products",
    addProduct: "پروڈکٹ شامل کریں / Add Product",
    editProduct: "پروڈکٹ میں ترمیم کریں / Edit Product",
    productCategories: "پروڈکٹ زمرے / Product Categories",
    productSubCategories: "پروڈکٹ ذیلی زمرے / Product Sub-Categories",
    
    // Form labels
    name: "نام / Name",
    sku: "SKU",
    barcode: "بارکوڈ / Barcode",
    category: "زمرہ / Category",
    subCategory: "ذیلی زمرہ / Sub-Category",
    price: "قیمت / Price",
    cost: "لاگت / Cost",
    stock: "اسٹاک / Stock",
    minStock: "کم از کم اسٹاک / Min Stock",
    maxStock: "زیادہ سے زیادہ اسٹاک / Max Stock",
    description: "تفصیل / Description",
    image: "تصویر / Image",
    supplier: "فراہم کنندہ / Supplier",
    brand: "برانڈ / Brand",
    unit: "یونٹ / Unit",
    weight: "وزن / Weight",
    dimensions: "پیمائش / Dimensions",
    taxRate: "ٹیکس ریٹ / Tax Rate",
    discount: "ڈسکاؤنٹ / Discount",
    
    // Units
    pieces: "پیس / Pieces",
    kg: "کلوگرام / Kg",
    liters: "لیٹر / Liters",
    meters: "میٹر / Meters",
    boxes: "بوکس / Boxes",
    countPcs: "تعداد (پیس) / Count (pcs)",
    weightMg: "وزن (mg) / Weight (mg)",
    weightG: "وزن (g) / Weight (g)",
    weightKg: "وزن (kg) / Weight (kg)",
    volumeMl: "حجم (ml) / Volume (ml)",
    volumeL: "حجم (L) / Volume (L)",
    
    // CRUD form
    productImage: "پروڈکٹ تصویر / Product Image",
    changeImage: "تصویر تبدیل کریں / Change image",
    clickOrDrag: "اپ لوڈ کرنے کے لیے کلک کریں یا کھینچیں / Click or drag to upload",
    pngJpgWebp: "PNG, JPG, WebP — زیادہ سے زیادہ 5MB / PNG, JPG, WebP — max 5MB",
    onlyPngJpg: "صرف PNG, JPG, JPEG یا WebP اجازت ہے / Only PNG, JPG, JPEG or WebP allowed",
    maxFileSize: "زیادہ سے زیادہ فائل سائز 5MB ہے / Max file size is 5MB",
    productName: "پروڈکٹ کا نام / Product Name",
    productNameRequired: "پروڈکٹ کا نام درکار ہے / Product Name is required",
    productCode: "پروڈکٹ کوڈ / Product Code",
    brandName: "برانڈ کا نام / Brand Name",
    brandNameRequired: "برانڈ کا نام درکار ہے / Brand Name is required",
    barcode: "بارکوڈ / Barcode",
    barcodeRequired: "بارکوڈ درکار ہے / Barcode is required",
    scanOrType: "اسکین یا ٹائپ کریں / Scan or type",
    description: "تفصیل / Description",
    descriptionRequired: "تفصیل درکار ہے / Description is required",
    productDescription: "پروڈکٹ کی تفصیل / Product description",
    selectCategory: "زمرہ منتخب کریں / Select category",
    selectSubCategory: "ذیلی زمرہ منتخب کریں / Select sub category",
    selectUnit: "یونٹ منتخب کریں / Select unit",
    selectTaxType: "ٹیکس کی قسم منتخب کریں / Select tax type",
    defaultCostPrice: "ڈیفالٹ لاگت قیمت / Default Cost Price",
    defaultRetailPrice: "ڈیفالٹ خوردہ قیمت / Default Retail Price",
    defaultWholesalePrice: "ڈیفالٹ ہوکری قیمت / Default Wholesale Price",
    taxPercent: "ٹیکس فیصد / Tax Percent",
    taxType: "ٹیکس کی قسم / Tax Type",
    percentage: "فیصد / Percentage",
    fixed: "فکسڈ / Fixed",
    minStockLevel: "کم از کم اسٹاک لیول / Min Stock Level",
    minStockLevelRequired: "کم از کم اسٹاک لیول درکار ہے / Min Stock Level is required",
    maxStockLevel: "زیادہ سے زیادہ اسٹاک لیول / Max Stock Level",
    maxStockLevelRequired: "زیادہ سے زیادہ اسٹاک لیول درکار ہے / Max Stock Level is required",
    maxGreaterThanMin: "زیادہ سے زیادہ کم سے زیادہ ہونا چاہیے / Max must be greater than Min",
    allowNegativeStock: "منفی اسٹاک کی اجازت دیں / Allow Negative Stock",
    allowDiscount: "ڈسکاؤنٹ کی اجازت دیں / Allow Discount",
    maxDiscountPercent: "زیادہ سے زیادہ ڈسکاؤنٹ % / Max Discount %",
    mustBeGreaterThanZero: "صفر سے زیادہ ہونا چاہیے / Must be greater than 0",
    rackLocation: "ریک کی جگہ / Rack Location",
    active: "فعال / Active",
    showMoreOptions: "مزید آپشنز دکھائیں / Show more options",
    hideAdditionalFields: "اضافی فیلڈز چھپائیں / Hide additional fields",
    scan: "اسکین / Scan",
    new: "نیا / New",
    saveProduct: "پروڈکٹ محفوظ کریں / Save Product",
    updateProduct: "پروڈکٹ اپ ڈیٹ کریں / Update Product",
    saving: "محفوظ ہو رہا ہے / Saving...",
    loadingProduct: "پروڈکٹ لوڈ ہو رہا ہے / Loading product...",
    fixErrors: "جمع کرنے سے پہلے {count} غلطی(اں) ٹھیک کریں / Fix {count} error(s) before submitting",
    productImageRequired: "پروڈکٹ تصویر درکار ہے / Product Image is required",
    categoryRequired: "زمرہ درکار ہے / Category is required",
    subCategoryRequired: "ذیلی زمرہ درکار ہے / Sub Category is required",
    unitRequired: "یونٹ درکار ہے / Unit is required",
    
    // Category CRUD
    addNewCategory: "نیا زمرہ شامل کریں / Add New Category",
    editCategory: "زمرہ میں ترمیم کریں / Edit Category",
    categoryName: "زمرہ کا نام / Category Name",
    categoryNameRequired: "زمرہ کا نام درکار ہے / Category name is required",
    categoryDescription: "زمرہ کی تفصیل / Category Description",
    categoryPlaceholder: "زمرہ کا نام لکھیں / Enter category name",
    categoryDescriptionPlaceholder: "زمرہ کی تفصیل لکھیں / Enter category description",
    saveCategory: "زمرہ محفوظ کریں / Save Category",
    updateCategory: "زمرہ اپ ڈیٹ کریں / Update Category",
    categoryCreated: "زمرہ کامیابی سے بنایا گیا / Category created successfully",
    categoryUpdated: "زمرہ کامیابی سے اپ ڈیٹ ہو گیا / Category updated successfully",
    categoryLoading: "زمرہ لوڈ ہو رہا ہے / Loading category...",
    somethingWentWrong: "کچھ غلط ہو گیا / Something went wrong",
    
    // Sub Category CRUD
    addNewSubCategory: "نیا ذیلی زمرہ شامل کریں / Add New Sub-Category",
    editSubCategory: "ذیلی زمرہ میں ترمیم کریں / Edit Sub-Category",
    subCategoryName: "ذیلی زمرہ کا نام / Sub-Category Name",
    subCategoryNameRequired: "ذیلی زمرہ کا نام درکار ہے / Sub-Category name is required",
    subCategoryDescription: "ذیلی زمرہ کی تفصیل / Sub-Category Description",
    subCategoryPlaceholder: "ذیلی زمرہ کا نام لکھیں / Enter sub-category name",
    subCategoryDescriptionPlaceholder: "ذیلی زمرہ کی تفصیل لکھیں / Enter sub-category description",
    saveSubCategory: "ذیلی زمرہ محفوظ کریں / Save Sub-Category",
    updateSubCategory: "ذیلی زمرہ اپ ڈیٹ کریں / Update Sub-Category",
    subCategoryCreated: "ذیلی زمرہ کامیابی سے بنایا گیا / Sub-Category created successfully",
    subCategoryUpdated: "ذیلی زمرہ کامیابی سے اپ ڈیٹ ہو گیا / Sub-Category updated successfully",
    subCategoryLoading: "ذیلی زمرہ لوڈ ہو رہا ہے / Loading sub-category...",
    
    // Table headers
    actions: "اقدامات / Actions",
    status: "حیثیت / Status",
    stockLevel: "اسٹاک لیول / Stock Level",
    
    // Buttons
    save: "محفوظ کریں / Save",
    cancel: "منسوخ کریں / Cancel",
    delete: "حذف کریں / Delete",
    edit: "ترمیم کریں / Edit",
    view: "دیکھیں / View",
    add: "شامل کریں / Add",
    
    // Messages
    loading: "لوڈ ہو رہا ہے / Loading...",
    noProductsFound: "کوئی پروڈکٹ نہیں ملا / No products found",
    noCategoriesFound: "کوئی زمرہ نہیں ملا / No categories found",
    noSubCategoriesFound: "کوئی ذیلی زمرہ نہیں ملا / No sub-categories found",
    productCreated: "پروڈکٹ کامیابی سے بنایا گیا / Product created successfully",
    productUpdated: "پروڈکٹ کامیابی سے اپ ڈیٹ ہو گیا / Product updated successfully",
    productDeleted: "پروڈکٹ کامیابی سے حذف ہو گیا / Product deleted successfully",
    categoryCreated: "زمرہ کامیابی سے بنایا گیا / Category created successfully",
    categoryUpdated: "زمرہ کامیابی سے اپ ڈیٹ ہو گیا / Category updated successfully",
    categoryDeleted: "زمرہ کامیابی سے حذف ہو گیا / Category deleted successfully",
    subCategoryCreated: "ذیلی زمرہ کامیابی سے بنایا گیا / Sub-category created successfully",
    subCategoryUpdated: "ذیلی زمرہ کامیابی سے اپ ڈیٹ ہو گیا / Sub-category updated successfully",
    subCategoryDeleted: "ذیلی زمرہ کامیابی سے حذف ہو گیا / Sub-category deleted successfully",
    failedToCreate: "بنانے میں ناکامی / Failed to create",
    failedToUpdate: "اپ ڈیٹ کرنے میں ناکامی / Failed to update",
    failedToDelete: "حذف کرنے میں ناکامی / Failed to delete",
    deleteConfirm: "کیا آپ واقعی اسے حذف کرنا چاہتے ہیں؟ / Are you sure you want to delete this?",
    
    // Filters
    allCategories: "تمام زمرے / All Categories",
    filterByCategory: "زمرہ کے مطابق فلٹر کریں / Filter by Category",
    filterByStatus: "حیثیت کے مطابق فلٹر کریں / Filter by Status",
    search: "تلاش / Search",
    clearFilters: "فلٹر صاف کریں / Clear Filters",
    
    // Status
    active: "فعال / Active",
    inactive: "غیر فعال / Inactive",
    lowStock: "کم اسٹاک / Low Stock",
    outOfStock: "اسٹاک ختم / Out of Stock",
    
    // Stock levels
    inStock: "اسٹاک میں / In Stock",
    lowStockWarning: "کم اسٹاک کی انتباہ / Low Stock Warning",
    
    // Summary
    totalProducts: "کل پروڈکٹس / Total Products",
    totalCategories: "کل زمرے / Total Categories",
    totalStock: "کل اسٹاک / Total Stock",
    totalValue: "کل قدر / Total Value",
  },
};

export const getProductLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return productLabels[langKey] || productLabels.en;
};
