export const posLabels = {
  en: {
    // Page titles
    posSystem: "POS System",
    pointOfSale: "Point of Sale",
    
    // Cart
    cart: "Cart",
    addToCart: "Add to Cart",
    removeFromCart: "Remove from Cart",
    updateQuantity: "Update Quantity",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    total: "Total",
    grandTotal: "Grand Total",
    currentOrder: "Current Order",
    resumed: "Resumed",
    cartEmpty: "Cart is empty",
    clickProductToAdd: "Click a product to add it",
    items: "Items",
    checkout: "Checkout",
    checkoutShortcut: "Checkout  ⇧",
    hold: "Hold",
    inCart: "In cart",
    noName: "No name",
    item: "item",
    itemsPlural: "items",
    resume: "Resume",
    delete: "Delete",
    batch: "Batch",
    
    // Payment
    payment: "Payment",
    pay: "Pay",
    paymentMethod: "Payment Method",
    cash: "Cash",
    card: "Card",
    bankTransfer: "Bank Transfer",
    qarza: "Qarza",
    change: "Change",
    paid: "Paid",
    remaining: "Remaining",
    completePayment: "Complete Payment",
    confirmOrderDetails: "Confirm order details below",
    grandTotal: "Grand Total",
    discount: "Discount",
    customerName: "Customer Name",
    staffMember: "Staff Member",
    orderType: "Order Type",
    retail: "Retail",
    wholesale: "Wholesale",
    cashReceived: "Cash Received",
    changeToReturn: "Change to return",
    shortBy: "Short by",
    platform: "Platform",
    amountReceived: "Amount Received",
    selectPlatform: "Select platform...",
    ledgerAccount: "Ledger Account",
    searchAccount: "Search account...",
    amountOnCredit: "Amount on credit",
    cashQarzaTotal: "Cash + Qarza must total",
    cashPortion: "Cash portion",
    qarzaPortion: "Qarza portion",
    selectQarzaAccount: "Select Qarza account...",
    amountsBalanced: "Amounts balanced",
    fillRest: "Fill rest",
    newQarzaAccount: "New Qarza account",
    optional: "Optional",
    selectStaff: "Select staff...",
    fillRequiredFields: "Fill required fields",
    easypaisa: "Easypaisa",
    jazzcash: "JazzCash",
    raast: "Raast",
    sadapay: "SadaPay",
    nayapay: "NayaPay",
    online: "Online",
    hybrid: "Hybrid",
    
    // Portion Modal
    selectPortion: "Select Portion",
    full: "Full",
    half: "Half",
    customPrice: "Custom Price",
    enterCustomPrice: "Enter Custom Price",
    updateCart: "Update Cart",
    
    // Free Food Modal
    managerApprovalRequired: "Manager Approval Required",
    managerCode: "Manager Code",
    enterManagerCode: "Enter manager code",
    codeRequired: "Code is required.",
    approveAndPrint: "Approve & Print",
    
    // Split Bill Modal
    splitBill: "Split Bill",
    numberOfPeople: "Number of people",
    printSplit: "Print Split",
    
    // Product
    product: "Product",
    products: "Products",
    searchProducts: "Search Products",
    price: "Price",
    stock: "Stock",
    category: "Category",
    quantity: "Quantity",
    
    // Actions
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    clear: "Clear",
    
    // Messages
    loading: "Loading...",
    noProductsFound: "No products found",
    orderCreated: "Order created successfully",
    orderCompleted: "Order completed successfully",
    orderCancelled: "Order cancelled successfully",
    orderHeld: "Order held successfully",
    failedToCreate: "Failed to create order",
    failedToComplete: "Failed to complete order",
    failedToCancel: "Failed to cancel order",
    failedToHold: "Failed to hold order",
    
    // Filters
    filter: "Filter",
    filters: "Filters",
    clearFilters: "Clear Filters",
    allCategories: "All Categories",
    search: "Search",
    searchProductsPlaceholder: "Search products...",
    brand: "Brand",
    priceRange: "Price Range",
    stockStatus: "Stock Status",
    status: "Status",
    allStock: "All Stock",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    lowStock: "Low Stock (< 5)",
    allStatus: "All Status",
    active: "Active",
    inactive: "Inactive",
    allPrices: "All Prices",
    under100: "Under Rs 100",
    price100to500: "Rs 100 - 500",
    price500to1000: "Rs 500 - 1000",
    price1000to5000: "Rs 1000 - 5000",
    above5000: "Above Rs 5000",
    min: "Min",
    max: "Max",
    noBrandsAvailable: "No brands available",
    applyFilters: "Apply Filters",
    resetFilters: "Reset Filters",
    
    // Hold Orders
    heldOrders: "Held Orders",
    noHeldOrders: "No held orders",
    
    // History
    history: "History",
    orderHistory: "Order History",
    productReturn: "Product Return",
    
    // Customer
    customer: "Customer",
    selectCustomer: "Select Customer",
    addCustomer: "Add Customer",
    noCustomer: "No Customer",
    walkIn: "Walk-in Customer",
    
    // Batch
    batch: "Batch",
    selectBatch: "Select Batch",
    batchNumber: "Batch Number",
    
    // Portion
    portion: "Portion",
    full: "Full",
    half: "Half",
    quarter: "Quarter",
  },
  ur: {
    // Page titles
    posSystem: "POS سسٹم",
    pointOfSale: "پوائنٹ آف سیل",
    
    // Cart
    cart: "کارٹ",
    addToCart: "کارٹ میں شامل کریں",
    removeFromCart: "کارٹ سے ہٹائیں",
    updateQuantity: "مقدار اپ ڈیٹ کریں",
    subtotal: "ذیلی کل",
    tax: "ٹیکس",
    discount: "ڈسکاؤنٹ",
    total: "کل",
    grandTotal: "بڑا کل",
    currentOrder: "موجودہ آرڈر",
    resumed: "دوبارہ شروع کیا",
    cartEmpty: "کارٹ خالی ہے",
    clickProductToAdd: "شامل کرنے کے لیے پروڈکٹ پر کلک کریں",
    items: "آئٹمز",
    checkout: "چیک آؤٹ",
    checkoutShortcut: "چیک آؤٹ  ⇧",
    hold: "روکیں",
    inCart: "کارٹ میں",
    noName: "کوئی نام نہیں",
    item: "آئٹم",
    itemsPlural: "آئٹمز",
    resume: "دوبارہ شروع کریں",
    delete: "حذف کریں",
    batch: "بیچ",
    
    // Payment
    payment: "ادائیگی",
    pay: "ادا کریں",
    paymentMethod: "ادائیگی کا طریقہ",
    cash: "نقد",
    card: "کارڈ",
    bankTransfer: "بینک ٹرانسفر",
    qarza: "قرضہ",
    change: "تبدیلی",
    paid: "ادا شدہ",
    remaining: "باقی",
    completePayment: "ادائیگی مکمل کریں",
    confirmOrderDetails: "آرڈر کی تفصیلات نیچے تصدیق کریں",
    grandTotal: "بڑا کل",
    discount: "ڈسکاؤنٹ",
    customerName: "کسٹمر کا نام",
    staffMember: "اسٹاف ممبر",
    orderType: "آرڈر کی قسم",
    retail: "ریٹیل",
    wholesale: "ہول سیل",
    cashReceived: "وصول شدہ نقد",
    changeToReturn: "واپسی کی تبدیلی",
    shortBy: "کمی",
    platform: "پلیٹ فارم",
    amountReceived: "وصول شدہ رقم",
    selectPlatform: "پلیٹ فارم منتخب کریں...",
    ledgerAccount: "لیجر اکاؤنٹ",
    searchAccount: "اکاؤنٹ تلاش کریں...",
    amountOnCredit: "قرضہ پر رقم",
    cashQarzaTotal: "نقد + قرضہ کل ہونا چاہیے",
    cashPortion: "نقد حصہ",
    qarzaPortion: "قرضہ حصہ",
    selectQarzaAccount: "قرضہ اکاؤنٹ منتخب کریں...",
    amountsBalanced: "رقم متوازن ہے",
    fillRest: "باقی بھریں",
    newQarzaAccount: "نیا قرضہ اکاؤنٹ",
    optional: "اختیاری",
    selectStaff: "اسٹاف منتخب کریں...",
    fillRequiredFields: "ضروری فیلڈز بھریں",
    easypaisa: "ایزی پیسہ",
    jazzcash: "جاز کیش",
    raast: "راست",
    sadapay: "سدا پے",
    nayapay: "نیا پے",
    online: "آن لائن",
    hybrid: "ہائبرڈ",
    
    // Portion Modal
    selectPortion: "حصہ منتخب کریں",
    full: "پورا",
    half: "آدھا",
    customPrice: "کسٹم قیمت",
    enterCustomPrice: "کسٹم قیمت درج کریں",
    updateCart: "اپ ڈیٹ کریں",
    
    // Free Food Modal
    managerApprovalRequired: "منیجر کی منظوری ضروری ہے",
    managerCode: "منیجر کا کوڈ",
    enterManagerCode: "کوڈ درج کریں",
    codeRequired: "کوڈ ضروری ہے۔",
    approveAndPrint: "منظوری اور پرنٹ کریں",
    
    // Split Bill Modal
    splitBill: "بل تقسیم کریں",
    numberOfPeople: "لوگوں کی تعداد",
    printSplit: "پرنٹ کریں",
    
    // Product
    product: "پروڈکٹ",
    products: "پروڈکٹس",
    searchProducts: "پروڈکٹس تلاش کریں",
    price: "قیمت",
    stock: "اسٹاک",
    category: "زمرہ",
    quantity: "مقدار",
    
    // Actions
    actions: "اقدامات",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    delete: "حذف کریں",
    edit: "ترمیم کریں",
    clear: "صاف کریں",
    
    // Messages
    loading: "لوڈ ہو رہا ہے...",
    noProductsFound: "کوئی پروڈکٹ نہیں ملا",
    orderCreated: "آرڈر کامیابی سے بنایا گیا",
    orderCompleted: "آرڈر کامیابی سے مکمل ہو گیا",
    orderCancelled: "آرڈر کامیابی سے منسوخ ہو گیا",
    orderHeld: "آرڈر کامیابی سے روکا گیا",
    failedToCreate: "آرڈر بنانے میں ناکامی",
    failedToComplete: "آرڈر مکمل کرنے میں ناکامی",
    failedToCancel: "آرڈر منسوخ کرنے میں ناکامی",
    failedToHold: "آرڈر روکنے میں ناکامی",
    
    // Filters
    filter: "فلٹر",
    filters: "فلٹرز",
    clearFilters: "فلٹر صاف کریں",
    allCategories: "تمام زمرے",
    search: "تلاش",
    searchProductsPlaceholder: "پروڈکٹس تلاش کریں...",
    brand: "برانڈ",
    priceRange: "قیمت کی حد",
    stockStatus: "اسٹاک کی حیثیت",
    status: "حیثیت",
    allStock: "تمام اسٹاک",
    inStock: "اسٹاک میں",
    outOfStock: "اسٹاک ختم",
    lowStock: "کم اسٹاک (< 5)",
    allStatus: "تمام حیثیت",
    active: "فعال",
    inactive: "غیر فعال",
    allPrices: "تمام قیمت",
    under100: "Rs 100 سے کم",
    price100to500: "Rs 100 - 500",
    price500to1000: "Rs 500 - 1000",
    price1000to5000: "Rs 1000 - 5000",
    above5000: "Rs 5000 سے زیادہ",
    min: "کم از کم",
    max: "زیادہ سے زیادہ",
    noBrandsAvailable: "کوئی برانڈ دستیاب نہیں",
    applyFilters: "فلٹر لگائیں",
    resetFilters: "فلٹر ری سیٹ کریں",
    
    // Hold Orders
    heldOrders: "روکے گئے آرڈرز",
    noHeldOrders: "کوئی روکا ہوا آرڈر نہیں",
    
    // History
    history: "تاریخ",
    orderHistory: "آرڈر کی تاریخ",
    productReturn: "پروڈکٹ واپسی",
    
    // Customer
    customer: "کسٹمر",
    selectCustomer: "کسٹمر منتخب کریں",
    addCustomer: "کسٹمر شامل کریں",
    noCustomer: "کوئی کسٹمر نہیں",
    walkIn: "چلنے پھرنے والا کسٹمر",
    
    // Batch
    batch: "بیچ",
    selectBatch: "بیچ منتخب کریں",
    batchNumber: "بیچ نمبر",
    
    // Portion
    portion: "حصہ",
    full: "پورا",
    half: "آدھا",
    quarter: "چوتھائی",
  },
  ur_en: {
    // Page titles
    posSystem: "POS سسٹم / POS System",
    pointOfSale: "پوائنٹ آف سیل / Point of Sale",
    
    // Cart
    cart: "کارٹ / Cart",
    addToCart: "کارٹ میں شامل کریں / Add to Cart",
    removeFromCart: "کارٹ سے ہٹائیں / Remove from Cart",
    updateQuantity: "مقدار اپ ڈیٹ کریں / Update Quantity",
    subtotal: "ذیلی کل / Subtotal",
    tax: "ٹیکس / Tax",
    discount: "ڈسکاؤنٹ / Discount",
    total: "کل / Total",
    grandTotal: "بڑا کل / Grand Total",
    currentOrder: "موجودہ آرڈر / Current Order",
    resumed: "دوبارہ شروع کیا / Resumed",
    cartEmpty: "کارٹ خالی ہے / Cart is empty",
    clickProductToAdd: "شامل کرنے کے لیے پروڈکٹ پر کلک کریں / Click a product to add it",
    items: "آئٹمز / Items",
    checkout: "چیک آؤٹ / Checkout",
    checkoutShortcut: "چیک آؤٹ  ⇧ / Checkout  ⇧",
    hold: "روکیں / Hold",
    inCart: "کارٹ میں / In cart",
    noName: "کوئی نام نہیں / No name",
    item: "آئٹم / item",
    itemsPlural: "آئٹمز / items",
    resume: "دوبارہ شروع کریں / Resume",
    delete: "حذف کریں / Delete",
    batch: "بیچ / Batch",
    
    // Payment
    payment: "ادائیگی / Payment",
    pay: "ادا کریں / Pay",
    paymentMethod: "ادائیگی کا طریقہ / Payment Method",
    cash: "نقد / Cash",
    card: "کارڈ / Card",
    bankTransfer: "بینک ٹرانسفر / Bank Transfer",
    qarza: "قرضہ / Qarza",
    change: "تبدیلی / Change",
    paid: "ادا شدہ / Paid",
    remaining: "باقی / Remaining",
    completePayment: "ادائیگی مکمل کریں / Complete Payment",
    confirmOrderDetails: "آرڈر کی تفصیلات نیچے تصدیق کریں / Confirm order details below",
    grandTotal: "بڑا کل / Grand Total",
    discount: "ڈسکاؤنٹ / Discount",
    customerName: "کسٹمر کا نام / Customer Name",
    staffMember: "اسٹاف ممبر / Staff Member",
    orderType: "آرڈر کی قسم / Order Type",
    retail: "ریٹیل / Retail",
    wholesale: "ہول سیل / Wholesale",
    cashReceived: "وصول شدہ نقد / Cash Received",
    changeToReturn: "واپسی کی تبدیلی / Change to return",
    shortBy: "کمی / Short by",
    platform: "پلیٹ فارم / Platform",
    amountReceived: "وصول شدہ رقم / Amount Received",
    selectPlatform: "پلیٹ فارم منتخب کریں... / Select platform...",
    ledgerAccount: "لیجر اکاؤنٹ / Ledger Account",
    searchAccount: "اکاؤنٹ تلاش کریں... / Search account...",
    amountOnCredit: "قرضہ پر رقم / Amount on credit",
    cashQarzaTotal: "نقد + قرضہ کل ہونا چاہیے / Cash + Qarza must total",
    cashPortion: "نقد حصہ / Cash portion",
    qarzaPortion: "قرضہ حصہ / Qarza portion",
    selectQarzaAccount: "قرضہ اکاؤنٹ منتخب کریں... / Select Qarza account...",
    amountsBalanced: "رقم متوازن ہے / Amounts balanced",
    fillRest: "باقی بھریں / Fill rest",
    newQarzaAccount: "نیا قرضہ اکاؤنٹ / New Qarza account",
    optional: "اختیاری / Optional",
    selectStaff: "اسٹاف منتخب کریں... / Select staff...",
    fillRequiredFields: "ضروری فیلڈز بھریں / Fill required fields",
    easypaisa: "ایزی پیسہ / Easypaisa",
    jazzcash: "جاز کیش / JazzCash",
    raast: "راست / Raast",
    sadapay: "سدا پے / SadaPay",
    nayapay: "نیا پے / NayaPay",
    online: "آن لائن / Online",
    hybrid: "ہائبرڈ / Hybrid",
    
    // Portion Modal
    selectPortion: "حصہ منتخب کریں / Select Portion",
    full: "پورا / Full",
    half: "آدھا / Half",
    customPrice: "کسٹم قیمت / Custom Price",
    enterCustomPrice: "کسٹم قیمت درج کریں / Enter Custom Price",
    updateCart: "اپ ڈیٹ کریں / Update Cart",
    
    // Free Food Modal
    managerApprovalRequired: "منیجر کی منظوری ضروری ہے / Manager Approval Required",
    managerCode: "منیجر کا کوڈ / Manager Code",
    enterManagerCode: "کوڈ درج کریں / Enter manager code",
    codeRequired: "کوڈ ضروری ہے۔ / Code is required.",
    approveAndPrint: "منظوری اور پرنٹ کریں / Approve & Print",
    
    // Split Bill Modal
    splitBill: "بل تقسیم کریں / Split Bill",
    numberOfPeople: "لوگوں کی تعداد / Number of people",
    printSplit: "پرنٹ کریں / Print Split",
    
    // Product
    product: "پروڈکٹ / Product",
    products: "پروڈکٹس / Products",
    searchProducts: "پروڈکٹس تلاش کریں / Search Products",
    price: "قیمت / Price",
    stock: "اسٹاک / Stock",
    category: "زمرہ / Category",
    quantity: "مقدار / Quantity",
    
    // Actions
    actions: "اقدامات / Actions",
    save: "محفوظ کریں / Save",
    cancel: "منسوخ کریں / Cancel",
    delete: "حذف کریں / Delete",
    edit: "ترمیم کریں / Edit",
    clear: "صاف کریں / Clear",
    
    // Messages
    loading: "لوڈ ہو رہا ہے / Loading...",
    noProductsFound: "کوئی پروڈکٹ نہیں ملا / No products found",
    orderCreated: "آرڈر کامیابی سے بنایا گیا / Order created successfully",
    orderCompleted: "آرڈر کامیابی سے مکمل ہو گیا / Order completed successfully",
    orderCancelled: "آرڈر کامیابی سے منسوخ ہو گیا / Order cancelled successfully",
    orderHeld: "آرڈر کامیابی سے روکا گیا / Order held successfully",
    failedToCreate: "آرڈر بنانے میں ناکامی / Failed to create order",
    failedToComplete: "آرڈر مکمل کرنے میں ناکامی / Failed to complete order",
    failedToCancel: "آرڈر منسوخ کرنے میں ناکامی / Failed to cancel order",
    failedToHold: "آرڈر روکنے میں ناکامی / Failed to hold order",
    
    // Filters
    filter: "فلٹر / Filter",
    filters: "فلٹرز / Filters",
    clearFilters: "فلٹر صاف کریں / Clear Filters",
    allCategories: "تمام زمرے / All Categories",
    search: "تلاش / Search",
    searchProductsPlaceholder: "پروڈکٹس تلاش کریں... / Search products...",
    brand: "برانڈ / Brand",
    priceRange: "قیمت کی حد / Price Range",
    stockStatus: "اسٹاک کی حیثیت / Stock Status",
    status: "حیثیت / Status",
    allStock: "تمام اسٹاک / All Stock",
    inStock: "اسٹاک میں / In Stock",
    outOfStock: "اسٹاک ختم / Out of Stock",
    lowStock: "کم اسٹاک (< 5) / Low Stock (< 5)",
    allStatus: "تمام حیثیت / All Status",
    active: "فعال / Active",
    inactive: "غیر فعال / Inactive",
    allPrices: "تمام قیمت / All Prices",
    under100: "Rs 100 سے کم / Under Rs 100",
    price100to500: "Rs 100 - 500",
    price500to1000: "Rs 500 - 1000",
    price1000to5000: "Rs 1000 - 5000",
    above5000: "Rs 5000 سے زیادہ / Above Rs 5000",
    min: "کم از کم / Min",
    max: "زیادہ سے زیادہ / Max",
    noBrandsAvailable: "کوئی برانڈ دستیاب نہیں / No brands available",
    applyFilters: "فلٹر لگائیں / Apply Filters",
    resetFilters: "فلٹر ری سیٹ کریں / Reset Filters",
    
    // Hold Orders
    heldOrders: "روکے گئے آرڈرز / Held Orders",
    noHeldOrders: "کوئی روکا ہوا آرڈر نہیں / No held orders",
    
    // History
    history: "تاریخ / History",
    orderHistory: "آرڈر کی تاریخ / Order History",
    productReturn: "پروڈکٹ واپسی / Product Return",
    
    // Customer
    customer: "کسٹمر / Customer",
    selectCustomer: "کسٹمر منتخب کریں / Select Customer",
    addCustomer: "کسٹمر شامل کریں / Add Customer",
    noCustomer: "کوئی کسٹمر نہیں / No Customer",
    walkIn: "چلنے پھرنے والا کسٹمر / Walk-in Customer",
    
    // Batch
    batch: "بیچ / Batch",
    selectBatch: "بیچ منتخب کریں / Select Batch",
    batchNumber: "بیچ نمبر / Batch Number",
    
    // Portion
    portion: "حصہ / Portion",
    full: "پورا / Full",
    half: "آدھا / Half",
    quarter: "چوتھائی / Quarter",
  },
};

export const getPosLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return posLabels[langKey] || posLabels.en;
};
