export const dashboardLabels = {
  en: {
    // Page titles
    dashboard: "Dashboard",
    businessOverview: "Overview of your business performance",
    
    // Buttons
    quickList: "Quick List",
    refresh: "Refresh",
    
    // Section headings
    salesPerformance: "Sales Performance",
    productsAndCategories: "Products & Categories",
    retailVsWholesale: "Retail vs Wholesale",
    inventoryOverview: "Inventory Overview",
    
    // KPI labels
    totalRevenue: "Total Revenue",
    retailRevenue: "Retail Revenue",
    wholesaleRevenue: "Wholesale Revenue",
    totalOrders: "Total Orders",
    averageOrderValue: "Average Order Value",
    grossProfit: "Gross Profit",
    retail: "Retail",
    wholesale: "Wholesale",
    orders: "orders",
    retailAOV: "Retail AOV",
    wholesaleAOV: "Wholesale AOV",
    margin: "margin",
    
    // Inventory alerts
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    overstock: "Overstock",
    batchesExpiring: "Batches expiring within 30 days",
    batchesBelowMin: "Batches below minimum stock",
    batchesZeroStock: "Batches with zero stock",
    expiringProducts: "Expiring Products — Batch Detail",
    activeAlerts: "Active Alerts",
    batchesExpiringIn7Days: "batches expiring within 7 days",
    batchesWithLowStock: "batches with low stock",
    batchesOutOfStock: "batches out of stock",
    lowStockDetail: "Low Stock — Batch Detail",
    outOfStockDetail: "Out of Stock — Batch Detail",
    productName: "Product Name",
    sku: "SKU",
    batchNumber: "Batch Number",
    expiryDate: "Expiry Date",
    daysRemaining: "Days Remaining",
    stockQty: "Stock Qty",
    currentStock: "Current Stock",
    minStock: "Min Stock",
    maxStock: "Max Stock",
    shortage: "Shortage",
    lastStockDate: "Last Stock Date",
    expiringIn7Days: "Expiring in 7 days",
    expiringIn30Days: "Expiring in 30 days",
    
    // Charts
    dailySales: "Daily Sales",
    weeklySales: "Weekly Sales",
    monthlySales: "Monthly Sales",
    categoryDistribution: "Category Distribution",
    topProducts: "Top Products",
    topSellingProducts: "Top Selling Products",
    salesByCategory: "Sales by Category",
    byRevenue: "By Revenue",
    byUnitsSold: "By Units Sold",
    revenue: "Revenue",
    unitsSold: "Units Sold",
    stockLevel: "Stock Level",
    stockLevelByCategory: "Stock Level by Category",
    inventoryValueByCategory: "Inventory Value by Category",
    
    // Time filters
    last7Days: "Last 7 Days",
    last30Days: "Last 30 Days",
    last90Days: "Last 90 Days",
    last6Months: "Last 6 Months",
    thisYear: "This Year",
    today: "Today",
    days3: "3 Days",
    days7: "7 Days",
    days30: "30 Days",
    months3: "3 Months",
    days90: "90 Days",
    year1: "1 Year",
    allTime: "All Time",
    customRange: "Custom Range",
    customDateRange: "Custom Date Range",
    startDate: "Start Date",
    endDate: "End Date",
    cancel: "Cancel",
    apply: "Apply",
    incomeVsExpense: "Income vs Expense",
    
    // Messages
    loading: "Loading...",
    noDataAvailable: "No data available",
    lastUpdated: "Last Updated",
    
    // Quick Actions
    searchModules: "Search modules...",
    dragToReorder: "Drag to reorder · tap to show/hide",
    done: "Done",
    dashboard: "Dashboard",
    analytics: "Analytics",
    addProducts: "Add Products",
    categories: "Categories",
    subCategories: "Sub-Categories",
    addPurchases: "Add Purchases",
    suppliers: "Suppliers",
    purchaseReturns: "Purchase Returns",
    productReturns: "Product Returns",
    customers: "Customers",
    wastage: "Wastage",
    qarzaAccounts: "Qarza Accounts",
    expenses: "Expenses",
    pos: "POS",
    orderHistory: "Order History",
    settings: "Settings",
    reports: "Reports",
    inventoryReport: "Inventory Report",
    staffReport: "Staff Report",
    creditsDebits: "Credits & Debits",
    expenseKpi: "Expense KPI",
    salesKpi: "Sales KPI",
    purchaseKpi: "Purchase KPI",
    supplierKpi: "Supplier KPI",
    customerKpi: "Customer KPI",
    staff: "Staff",
    addStaff: "Add Staff",
    attendance: "Attendance",
    profile: "Profile",
    appUsers: "App Users",
  },
  ur: {
    // Page titles
    dashboard: "ڈیش بورڈ",
    businessOverview: "اپنے کاروبار کی کارکردگی کا جائزہ",
    
    // Buttons
    quickList: "فہرست",
    refresh: "تازہ کاری",
    
    // Section headings
    salesPerformance: "فروخت کی کارکردگی",
    productsAndCategories: "پروڈکٹس اور زمرے",
    retailVsWholesale: "خردار مقابلہ ہوکری",
    inventoryOverview: "انوینٹری کا جائزہ",
    
    // KPI labels
    totalRevenue: "کل آمدنی",
    retailRevenue: "خردار آمدنی",
    wholesaleRevenue: "ہوکری آمدنی",
    totalOrders: "کل آرڈرز",
    averageOrderValue: "اوسط آرڈر ویلیو",
    grossProfit: "خالص منافع",
    retail: "خردار",
    wholesale: "ہوکری",
    orders: "آرڈرز",
    retailAOV: "خردار اوسط",
    wholesaleAOV: "ہوکری اوسط",
    margin: "مارجن",
    
    // Inventory alerts
    lowStock: "کم اسٹاک",
    outOfStock: "اسٹاک ختم",
    overstock: "زیادہ اسٹاک",
    batchesExpiring: "30 دن میں ختم ہونے والے بیچز",
    batchesBelowMin: "مینیمم اسٹاک سے کم بیچز",
    batchesZeroStock: "زیرو اسٹاک بیچز",
    expiringProducts: "ختم ہونے والے پروڈکٹس — بیچ ڈیٹیل",
    lowStockDetail: "کم اسٹاک — بیچ ڈیٹیل",
    outOfStockDetail: "اسٹاک ختم — بیچ ڈیٹیل",
    productName: "پروڈکٹ کا نام",
    sku: "SKU",
    batchNumber: "بیچ نمبر",
    expiryDate: "ختم ہونے کی تاریخ",
    daysRemaining: "باقی دن",
    stockQty: "اسٹاک مقدار",
    currentStock: "موجودہ اسٹاک",
    minStock: "مینیمم اسٹاک",
    maxStock: "میکسیمم اسٹاک",
    shortage: "کمی",
    lastStockDate: "آخری اسٹاک تاریخ",
    expiringIn7Days: "7 دن میں ختم ہو رہا ہے",
    expiringIn30Days: "30 دن میں ختم ہو رہا ہے",
    
    // Charts
    dailySales: "روزانہ فروخت",
    weeklySales: "ہفتہ وار فروخت",
    monthlySales: "مہینہ وار فروخت",
    categoryDistribution: "زمرہ کی تقسیم",
    topProducts: "بہترین پروڈکٹس",
    topSellingProducts: "بہترین فروخت پروڈکٹس",
    salesByCategory: "زمرہ کے لحاظ سے فروخت",
    byRevenue: "آمدنی کے لحاظ سے",
    byUnitsSold: "یونٹس فروخت کے لحاظ سے",
    revenue: "آمدنی",
    unitsSold: "فروخت یونٹس",
    stockLevel: "اسٹاک لیول",
    stockLevelByCategory: "زمرہ کے لحاظ سے اسٹاک لیول",
    inventoryValueByCategory: "زمرہ کے لحاظ سے انوینٹری ویلیو",
    
    // Time filters
    last7Days: "پچھلے 7 دن",
    last30Days: "پچھلے 30 دن",
    last90Days: "پچھلے 90 دن",
    thisYear: "اس سال",
    today: "آج",
    days3: "3 دن",
    days7: "7 دن",
    days30: "30 دن",
    months3: "3 مہینے",
    days90: "90 دن",
    year1: "1 سال",
    allTime: "تمام وقت",
    customRange: "حسب ضرورت حد",
    customDateRange: "حسب ضرورت تاریخ کی حد",
    startDate: "شروع کی تاریخ",
    endDate: "اختتام کی تاریخ",
    cancel: "منسوخ کریں",
    apply: "لاگو کریں",
    
    // Messages
    loading: "لوڈ ہو رہا ہے...",
    noDataAvailable: "کوئی ڈیٹا دستیاب نہیں",
    lastUpdated: "آخری اپ ڈیٹ",
    
    // Quick Actions
    searchModules: "ماڈیولز تلاش کریں...",
    dragToReorder: "ترتیب بدلنے کے لیے کھینچیں · دکھانے/چھپانے کے لیے ٹیپ کریں",
    done: "مکمل",
    dashboard: "ڈیش بورڈ",
    analytics: "اینالیٹکس",
    addProducts: "پروڈکٹس شامل کریں",
    categories: "زمرے",
    subCategories: "ذیلی زمرے",
    addPurchases: "خریداری شامل کریں",
    suppliers: "سپلائرز",
    purchaseReturns: "خریداری واپسی",
    productReturns: "پروڈکٹ واپسی",
    customers: "گاہک",
    wastage: "ضیاع",
    qarzaAccounts: "قرضے اکاؤنٹس",
    expenses: "اخراجات",
    pos: "POS",
    orderHistory: "آرڈر کی تاریخ",
    settings: "سیٹنگز",
    reports: "رپورٹس",
    inventoryReport: "انوینٹری رپورٹ",
    staffReport: "اسٹاف رپورٹ",
    creditsDebits: "کریڈٹ اور ڈیبٹس",
    expenseKpi: "اخراجات KPI",
    salesKpi: "سیلز KPI",
    purchaseKpi: "خریداری KPI",
    supplierKpi: "سپلائر KPI",
    customerKpi: "گاہک KPI",
    staff: "اسٹاف",
    addStaff: "اسٹاف شامل کریں",
    attendance: "حاضری",
    profile: "پروفائل",
    appUsers: "ایپ صارفین",
  },
  ur_en: {
    // Page titles
    dashboard: "ڈیش بورڈ / Dashboard",
    businessOverview: "اپنے کاروبار کی کارکردگی کا جائزہ / Overview of your business performance",
    
    // Buttons
    quickList: "فہرست / Quick List",
    refresh: "تازہ کاری / Refresh",
    
    // Section headings
    salesPerformance: "فروخت کی کارکردگی / Sales Performance",
    productsAndCategories: "پروڈکٹس اور زمرے / Products & Categories",
    retailVsWholesale: "خردار مقابلہ ہوکری / Retail vs Wholesale",
    inventoryOverview: "انوینٹری کا جائزہ / Inventory Overview",
    
    // KPI labels
    totalRevenue: "کل آمدنی / Total Revenue",
    retailRevenue: "خردار آمدنی / Retail Revenue",
    wholesaleRevenue: "ہوکری آمدنی / Wholesale Revenue",
    totalOrders: "کل آرڈرز / Total Orders",
    averageOrderValue: "اوسط آرڈر ویلیو / Average Order Value",
    grossProfit: "خالص منافع / Gross Profit",
    retail: "خردار / Retail",
    wholesale: "ہوکری / Wholesale",
    orders: "آرڈرز / orders",
    retailAOV: "خردار اوسط / Retail AOV",
    wholesaleAOV: "ہوکری اوسط / Wholesale AOV",
    margin: "مارجن / margin",
    
    // Inventory alerts
    lowStock: "کم اسٹاک",
    outOfStock: "اسٹاک ختم",
    overstock: "زیادہ اسٹاک",
    batchesExpiring: "30 دن میں ختم ہونے والے بیچز",
    batchesBelowMin: "مینیمم اسٹاک سے کم بیچز",
    batchesZeroStock: "زیرو اسٹاک بیچز",
    expiringProducts: "ختم ہونے والے پروڈکٹس — بیچ ڈیٹیل",
    activeAlerts: "فعل الرٹس",
    batchesExpiringIn7Days: "7 دن میں ختم ہونے والے بیچز",
    batchesWithLowStock: "کم اسٹاک والے بیچز",
    batchesOutOfStock: "اسٹاک ختم بیچز",
    lowStockDetail: "کم اسٹاک — بیچ ڈیٹیل / Low Stock — Batch Detail",
    outOfStockDetail: "اسٹاک ختم — بیچ ڈیٹیل / Out of Stock — Batch Detail",
    productName: "پروڈکٹ کا نام / Product Name",
    sku: "SKU",
    batchNumber: "بیچ نمبر / Batch Number",
    expiryDate: "ختم ہونے کی تاریخ / Expiry Date",
    daysRemaining: "باقی دن / Days Remaining",
    stockQty: "اسٹاک مقدار / Stock Qty",
    currentStock: "موجودہ اسٹاک / Current Stock",
    minStock: "مینیمم اسٹاک / Min Stock",
    maxStock: "میکسیمم اسٹاک / Max Stock",
    shortage: "کمی / Shortage",
    lastStockDate: "آخری اسٹاک تاریخ / Last Stock Date",
    expiringIn7Days: "7 دن میں ختم ہو رہا ہے / Expiring in 7 days",
    expiringIn30Days: "30 دن میں ختم ہو رہا ہے / Expiring in 30 days",
    
    // Charts
    dailySales: "روزانہ فروخت / Daily Sales",
    weeklySales: "ہفتہ وار فروخت / Weekly Sales",
    monthlySales: "مہینہ وار فروخت / Monthly Sales",
    categoryDistribution: "زمرہ کی تقسیم / Category Distribution",
    topProducts: "بہترین پروڈکٹس / Top Products",
    topSellingProducts: "بہترین فروخت پروڈکٹس / Top Selling Products",
    salesByCategory: "زمرہ کے لحاظ سے فروخت / Sales by Category",
    byRevenue: "آمدنی کے لحاظ سے / By Revenue",
    byUnitsSold: "یونٹس فروخت کے لحاظ سے / By Units Sold",
    revenue: "آمدنی / Revenue",
    unitsSold: "فروخت یونٹس / Units Sold",
    stockLevel: "اسٹاک لیول / Stock Level",
    stockLevelByCategory: "زمرہ کے لحاظ سے اسٹاک لیول / Stock Level by Category",
    inventoryValueByCategory: "زمرہ کے لحاظ سے انوینٹری ویلیو / Inventory Value by Category",
    
    // Time filters
    last7Days: "پچھلے 7 دن / Last 7 Days",
    last30Days: "پچھلے 30 دن / Last 30 Days",
    last90Days: "پچھلے 90 دن / Last 90 Days",
    last6Months: "پچھلے 6 مہینے / Last 6 Months",
    thisYear: "اس سال / This Year",
    today: "آج / Today",
    days3: "3 دن / 3 Days",
    days7: "7 دن / 7 Days",
    days30: "30 دن / 30 Days",
    months3: "3 مہینے / 3 Months",
    days90: "90 دن / 90 Days",
    year1: "1 سال / 1 Year",
    allTime: "تمام وقت / All Time",
    customRange: "حسب ضرورت حد / Custom Range",
    customDateRange: "حسب ضرورت تاریخ کی حد / Custom Date Range",
    startDate: "شروع کی تاریخ / Start Date",
    endDate: "اختتام کی تاریخ / End Date",
    cancel: "منسوخ کریں / Cancel",
    apply: "لاگو کریں / Apply",
    incomeVsExpense: "آمدنی اور خرچ / Income vs Expense",
    
    // Messages
    loading: "لوڈ ہو رہا ہے / Loading...",
    noDataAvailable: "کوئی ڈیٹا دستیاب نہیں / No data available",
    lastUpdated: "آخری اپ ڈیٹ / Last Updated",
    
    // Quick Actions
    searchModules: "ماڈیولز تلاش کریں / Search modules...",
    dragToReorder: "ترتیب بدلنے کے لیے کھینچیں · دکھانے/چھپانے کے لیے ٹیپ کریں / Drag to reorder · tap to show/hide",
    done: "مکمل / Done",
    dashboard: "ڈیش بورڈ / Dashboard",
    analytics: "اینالیٹکس / Analytics",
    addProducts: "پروڈکٹس شامل کریں / Add Products",
    categories: "زمرے / Categories",
    subCategories: "ذیلی زمرے / Sub-Categories",
    addPurchases: "خریداری شامل کریں / Add Purchases",
    suppliers: "سپلائرز / Suppliers",
    purchaseReturns: "خریداری واپسی / Purchase Returns",
    productReturns: "پروڈکٹ واپسی / Product Returns",
    customers: "گاہک / Customers",
    wastage: "ضیاع / Wastage",
    qarzaAccounts: "قرضے اکاؤنٹس / Qarza Accounts",
    expenses: "اخراجات / Expenses",
    pos: "POS",
    orderHistory: "آرڈر کی تاریخ / Order History",
    settings: "سیٹنگز / Settings",
    reports: "رپورٹس / Reports",
    inventoryReport: "انوینٹری رپورٹ / Inventory Report",
    staffReport: "اسٹاف رپورٹ / Staff Report",
    creditsDebits: "کریڈٹ اور ڈیبٹس / Credits & Debits",
    expenseKpi: "اخراجات KPI / Expense KPI",
    salesKpi: "سیلز KPI / Sales KPI",
    purchaseKpi: "خریداری KPI / Purchase KPI",
    supplierKpi: "سپلائر KPI / Supplier KPI",
    customerKpi: "گاہک KPI / Customer KPI",
    staff: "اسٹاف / Staff",
    addStaff: "اسٹاف شامل کریں / Add Staff",
    attendance: "حاضری / Attendance",
    profile: "پروفائل / Profile",
    appUsers: "ایپ صارفین / App Users",
  },
};

export const getDashboardLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return dashboardLabels[langKey] || dashboardLabels.en;
};
