// Staff module labels for all languages (English, Urdu, Urdu/English)
export const staffLabels = {
  en: {
    // Page titles
    staffManagement: "Staff Management",
    manageStaff: "Manage your staff members",
    staffDetails: "Staff Details",
    createStaff: "Create Staff",
    editStaff: "Edit Staff",
    markAttendance: "Mark Attendance",
    
    // Buttons
    addStaff: "Add Staff",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    back: "Back",
    
    // Filters
    searchPlaceholder: "Search by name, CNIC, phone...",
    allRoles: "All Roles",
    allStatus: "All Status",
    allSalaryTypes: "All Salary Types",
    
    // Roles
    cashier: "Cashier",
    tailor: "Tailor",
    stockKeeper: "Stock Keeper",
    other: "Other",
    
    // Status
    active: "Active",
    inactive: "Inactive",
    
    // Salary Types
    fixed: "Fixed",
    percentage: "Percentage",
    
    // Table headers
    name: "Name",
    cnic: "CNIC",
    phone: "Phone",
    role: "Role",
    salaryType: "Salary Type",
    status: "Status",
    joinDate: "Join Date",
    actions: "Actions",
    
    // Form fields
    fullName: "Full Name",
    cnicPlaceholder: "Enter CNIC",
    phonePlaceholder: "Enter phone number",
    address: "Address",
    addressPlaceholder: "Enter address",
    salary: "Salary",
    salaryPlaceholder: "Enter salary amount",
    commissionRate: "Commission Rate",
    commissionPlaceholder: "Enter commission rate (%)",
    
    // Messages
    staffCreated: "Staff created successfully",
    staffUpdated: "Staff updated successfully",
    staffDeleted: "Staff deleted successfully",
    deleteConfirm: "Are you sure you want to delete {name}?",
    failedToCreate: "Failed to create staff",
    failedToUpdate: "Failed to update staff",
    failedToDelete: "Failed to delete staff",
    loading: "Loading...",
    noStaffFound: "No staff found",
    
    // Attendance
    attendanceMarked: "Attendance marked successfully",
    attendanceDate: "Attendance Date",
    present: "Present",
    absent: "Absent",
    late: "Late",
    leave: "Leave",
    
    // Staff Detail
    staffDetails: "Staff Details",
    profile: "Profile",
    documents: "Documents",
    saleOrders: "Sale Orders",
    salaryBreakdown: "Salary Breakdown",
    paymentSummary: "Payment Summary",
    staffPayments: "Staff Payments",
    uploadImages: "Upload Images",
    selectMultipleImages: "You can select multiple images to upload",
    preview: "Preview",
    upload: "Upload",
    images: "Images",
    noImagesUploaded: "No images uploaded",
    posOrders: "POS Orders",
    noPosOrdersFound: "No POS orders found for this staff",
    selectDateRange: "Select date range to view salary breakdown",
    salaryBreakdownFixedOnly: "Salary breakdown is only applicable for fixed salary staff",
    totalEarnings: "Total Earnings",
    totalPaid: "Total Paid",
    totalRemaining: "Total Remaining",
    staffName: "Staff Name",
    monthlySalary: "Monthly Salary",
    totalExpected: "Total Expected",
    workingDays: "Working Days",
    totalDays: "Total Days",
    expected: "Expected",
    paid: "Paid",
    remaining: "Remaining",
    allocatedPayments: "Allocated Payments (FIFO)",
    paymentStatus: "Payment Status",
    full: "Full",
    partial: "Partial",
    unpaid: "Unpaid",
    addPayment: "Add Payment",
    recordPayment: "Record Payment",
    paymentAmount: "Payment Amount",
    paymentMonth: "Payment Month",
    paymentNotes: "Payment Notes",
    deletePayment: "Delete Payment",
    deletePaymentConfirm: "Are you sure you want to delete this payment?",
    documentAdded: "Document added successfully",
    documentRemoved: "Document removed successfully",
    failedToAddDocument: "Failed to add document",
    failedToRemoveDocument: "Failed to remove document",
    paymentRecorded: "Payment recorded successfully",
    failedToRecordPayment: "Failed to record payment",
    imagesUploaded: "Images uploaded successfully",
    failedToUploadImages: "Failed to upload images",
    imageRemoved: "Image removed successfully",
    failedToRemoveImage: "Failed to remove image",
    staffNotFound: "Staff not found",
    clear: "Clear",
    to: "to",
    earned: "Earned",
    items: "Items",
    paymentMethod: "Payment Method",
    orderNumber: "Order #",
    joinDate: "Join Date",
    salary: "salary",
    personalInfo: "Personal Information",
    salaryInfo: "Salary Information",
    additionalInfo: "Additional Information",
    emergencyContact: "Emergency Contact",
    photo: "Photo",
    notes: "Notes",
    create: "Create",
    edit: "Edit",
  },
  ur: {
    // Page titles
    staffManagement: "اسٹاف مینجمنٹ",
    manageStaff: "اپنے اسٹاف کے ممبران کا انتظام کریں",
    staffDetails: "اسٹاف کی تفصیلات",
    createStaff: "اسٹاف بنائیں",
    editStaff: "اسٹاف میں ترمیم کریں",
    markAttendance: "حاضری لگائیں",
    
    // Buttons
    addStaff: "اسٹاف شامل کریں",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    delete: "حذف کریں",
    edit: "ترمیم کریں",
    view: "دیکھیں",
    back: "واپس",
    
    // Filters
    searchPlaceholder: "نام، شناختی کارڈ، فون سے تلاش کریں...",
    allRoles: "تمام کردار",
    allStatus: "تمام حیثیت",
    allSalaryTypes: "تمام تنخواہ کی اقسام",
    
    // Roles
    cashier: "کیشیئر",
    tailor: "ٹیلر",
    stockKeeper: "اسٹاک کیپر",
    other: "دیگر",
    
    // Status
    active: "فعال",
    inactive: "غیر فعال",
    
    // Salary Types
    fixed: "مقررہ",
    percentage: "فیصد",
    
    // Table headers
    name: "نام",
    cnic: "شناختی کارڈ",
    phone: "فون",
    role: "کردار",
    salaryType: "تنخواہ کی قسم",
    status: "حیثیت",
    joinDate: "شمولیت کی تاریخ",
    actions: "اقدامات",
    
    // Form fields
    fullName: "پورا نام",
    cnicPlaceholder: "شناختی کارڈ درج کریں",
    phonePlaceholder: "فون نمبر درج کریں",
    address: "پتہ",
    addressPlaceholder: "پتہ درج کریں",
    salary: "تنخواہ",
    salaryPlaceholder: "تنخواہ کی رقم درج کریں",
    commissionRate: "کمیشن ریٹ",
    commissionPlaceholder: "کمیشن ریٹ درج کریں (%)",
    
    // Messages
    staffCreated: "اسٹاف کامیابی سے بنایا گیا",
    staffUpdated: "اسٹاف کامیابی سے اپ ڈیٹ ہوا",
    staffDeleted: "اسٹاف کامیابی سے حذف ہو گیا",
    deleteConfirm: "کیا آپ واقعی {name} کو حذف کرنا چاہتے ہیں؟",
    failedToCreate: "اسٹاف بنانے میں ناکامی",
    failedToUpdate: "اسٹاف اپ ڈیٹ کرنے میں ناکامی",
    failedToDelete: "اسٹاف حذف کرنے میں ناکامی",
    loading: "لوڈ ہو رہا ہے...",
    noStaffFound: "کوئی اسٹاف نہیں ملا",
    
    // Attendance
    attendanceMarked: "حاضری کامیابی سے لگی گئی",
    attendanceDate: "حاضری کی تاریخ",
    present: "حاضر",
    absent: "غایب",
    late: "دیر سے",
    leave: "چھٹی",
    
    // Staff Detail
    staffDetails: "اسٹاف کی تفصیلات",
    profile: "پروفائل",
    documents: "دستاویزات",
    saleOrders: "فروخت کے آرڈرز",
    salaryBreakdown: "تنخواہ کی تفصیل",
    paymentSummary: "ادائیگی کا خلاصہ",
    staffPayments: "اسٹاف کی ادائیگیاں",
    uploadImages: "تصاویر اپ لوڈ کریں",
    selectMultipleImages: "آپ متعدد تصاویر منتخب کر سکتے ہیں",
    preview: "پیش نظارہ",
    upload: "اپ لوڈ",
    images: "تصاویر",
    noImagesUploaded: "کوئی تصویر اپ لوڈ نہیں ہوئی",
    posOrders: "POS آرڈرز",
    noPosOrdersFound: "اس اسٹاف کے لیے کوئی POS آرڈر نہیں ملا",
    selectDateRange: "تنخواہ کی تفصیل دیکھنے کے لیے تاریخ کی حد منتخب کریں",
    salaryBreakdownFixedOnly: "تنخواہ کی تفصیل صرف مقررہ تنخواہ والے اسٹاف کے لیے قابل اطلاق ہے",
    totalEarnings: "کل آمدنی",
    totalPaid: "کل ادا شدہ",
    totalRemaining: "کل باقی",
    staffName: "اسٹاف کا نام",
    monthlySalary: "ماہانہ تنخواہ",
    totalExpected: "کل متوقع",
    workingDays: "کام کے دن",
    totalDays: "کل دن",
    expected: "متوقع",
    paid: "ادا شدہ",
    remaining: "باقی",
    allocatedPayments: "مقررہ ادائیگیاں (FIFO)",
    paymentStatus: "ادائیگی کی حیثیت",
    full: "مکمل",
    partial: "جزوی",
    unpaid: "غیر ادا شدہ",
    addPayment: "ادائیگی شامل کریں",
    recordPayment: "ادائیگی ریکارڈ کریں",
    paymentAmount: "ادائیگی کی رقم",
    paymentMonth: "ادائیگی کا مہینہ",
    paymentNotes: "ادائیگی کے نوٹس",
    deletePayment: "ادائیگی حذف کریں",
    deletePaymentConfirm: "کیا آپ واقعی اس ادائیگی کو حذف کرنا چاہتے ہیں؟",
    documentAdded: "دستاویز کامیابی سے شامل ہو گئی",
    documentRemoved: "دستاویز کامیابی سے ہٹا دی گئی",
    failedToAddDocument: "دستاویز شامل کرنے میں ناکامی",
    failedToRemoveDocument: "دستاویز ہٹانے میں ناکامی",
    paymentRecorded: "ادائیگی کامیابی سے ریکارڈ ہو گئی",
    failedToRecordPayment: "ادائیگی ریکارڈ کرنے میں ناکامی",
    imagesUploaded: "تصاویر کامیابی سے اپ لوڈ ہو گئیں",
    failedToUploadImages: "تصاویر اپ لوڈ کرنے میں ناکامی",
    imageRemoved: "تصویر کامیابی سے ہٹا دی گئی",
    failedToRemoveImage: "تصویر ہٹانے میں ناکامی",
    staffNotFound: "اسٹاف نہیں ملا",
    clear: "صاف کریں",
    to: "تک",
    earned: "کما",
    items: "آئٹمز",
    paymentMethod: "ادائیگی کا طریقہ",
    orderNumber: "آرڈر #",
    joinDate: "شمولیت کی تاریخ",
    salary: "تنخواہ",
    personalInfo: "ذاتی معلومات",
    salaryInfo: "تنخواہ کی معلومات",
    additionalInfo: "اضافی معلومات",
    emergencyContact: "ایمرجنسی رابطہ",
    photo: "تصویر",
    notes: "نوٹس",
    create: "بنائیں",
    edit: "ترمیم کریں",
  },
  ur_en: {
    // Page titles
    staffManagement: "اسٹاف مینجمنٹ / Staff Management",
    manageStaff: "اپنے اسٹاف کا انتظام کریں / Manage your staff members",
    staffDetails: "اسٹاف تفصیلات / Staff Details",
    createStaff: "اسٹاف بنائیں / Create Staff",
    editStaff: "اسٹاف میں ترمیم کریں / Edit Staff",
    markAttendance: "حاضری لگائیں / Mark Attendance",
    
    // Buttons
    addStaff: "اسٹاف شامل کریں / Add Staff",
    save: "محفوظ کریں / Save",
    cancel: "منسوخ کریں / Cancel",
    delete: "حذف کریں / Delete",
    edit: "ترمیم کریں / Edit",
    view: "دیکھیں / View",
    back: "واپس / Back",
    
    // Filters
    searchPlaceholder: "تلاش کریں / Search by name, CNIC, phone...",
    allRoles: "تمام کردار / All Roles",
    allStatus: "تمام حیثیت / All Status",
    allSalaryTypes: "تمام تنخواہ کی اقسام / All Salary Types",
    
    // Roles
    cashier: "کیشیئر / Cashier",
    tailor: "ٹیلر / Tailor",
    stockKeeper: "اسٹاک کیپر / Stock Keeper",
    other: "دیگر / Other",
    
    // Status
    active: "فعال / Active",
    inactive: "غیر فعال / Inactive",
    
    // Salary Types
    fixed: "مقررہ / Fixed",
    percentage: "فیصد / Percentage",
    
    // Table headers
    name: "نام / Name",
    cnic: "شناختی کارڈ / CNIC",
    phone: "فون / Phone",
    role: "کردار / Role",
    salaryType: "تنخواہ کی قسم / Salary Type",
    status: "حیثیت / Status",
    joinDate: "شمولیت کی تاریخ / Join Date",
    actions: "اقدامات / Actions",
    
    // Form fields
    fullName: "پورا نام / Full Name",
    cnicPlaceholder: "شناختی کارڈ درج کریں / Enter CNIC",
    phonePlaceholder: "فون نمبر درج کریں / Enter phone number",
    address: "پتہ / Address",
    addressPlaceholder: "پتہ درج کریں / Enter address",
    salary: "تنخواہ / Salary",
    salaryPlaceholder: "تنخواہ کی رقم درج کریں / Enter salary amount",
    commissionRate: "کمیشن ریٹ / Commission Rate",
    commissionPlaceholder: "کمیشن ریٹ درج کریں (%) / Enter commission rate (%)",
    
    // Messages
    staffCreated: "اسٹاف کامیابی سے بنایا گیا / Staff created successfully",
    staffUpdated: "اسٹاف کامیابی سے اپ ڈیٹ ہوا / Staff updated successfully",
    staffDeleted: "اسٹاف کامیابی سے حذف ہو گیا / Staff deleted successfully",
    deleteConfirm: "کیا آپ واقعی حذف کرنا چاہتے ہیں؟ / Are you sure you want to delete {name}?",
    failedToCreate: "اسٹاف بنانے میں ناکامی / Failed to create staff",
    failedToUpdate: "اسٹاف اپ ڈیٹ کرنے میں ناکامی / Failed to update staff",
    failedToDelete: "اسٹاف حذف کرنے میں ناکامی / Failed to delete staff",
    loading: "لوڈ ہو رہا ہے / Loading...",
    noStaffFound: "کوئی اسٹاف نہیں ملا / No staff found",
    
    // Attendance
    attendanceMarked: "حاضری کامیابی سے لگی گئی / Attendance marked successfully",
    attendanceDate: "حاضری کی تاریخ / Attendance Date",
    present: "حاضر / Present",
    absent: "غایب / Absent",
    late: "دیر سے / Late",
    leave: "چھٹی / Leave",
    
    // Staff Detail
    staffDetails: "اسٹاف کی تفصیلات / Staff Details",
    profile: "پروفائل / Profile",
    documents: "دستاویزات / Documents",
    saleOrders: "فروخت کے آرڈرز / Sale Orders",
    salaryBreakdown: "تنخواہ کی تفصیل / Salary Breakdown",
    paymentSummary: "ادائیگی کا خلاصہ / Payment Summary",
    staffPayments: "اسٹاف کی ادائیگیاں / Staff Payments",
    uploadImages: "تصاویر اپ لوڈ کریں / Upload Images",
    selectMultipleImages: "آپ متعدد تصاویر منتخب کر سکتے ہیں / You can select multiple images to upload",
    preview: "پیش نظارہ / Preview",
    upload: "اپ لوڈ / Upload",
    images: "تصاویر / Images",
    noImagesUploaded: "کوئی تصویر اپ لوڈ نہیں ہوئی / No images uploaded",
    posOrders: "POS آرڈرز / POS Orders",
    noPosOrdersFound: "اس اسٹاف کے لیے کوئی POS آرڈر نہیں ملا / No POS orders found for this staff",
    selectDateRange: "تنخواہ کی تفصیل دیکھنے کے لیے تاریخ کی حد منتخب کریں / Select date range to view salary breakdown",
    salaryBreakdownFixedOnly: "تنخواہ کی تفصیل صرف مقررہ تنخواہ والے اسٹاف کے لیے قابل اطلاق ہے / Salary breakdown is only applicable for fixed salary staff",
    totalEarnings: "کل آمدنی / Total Earnings",
    totalPaid: "کل ادا شدہ / Total Paid",
    totalRemaining: "کل باقی / Total Remaining",
    staffName: "اسٹاف کا نام / Staff Name",
    monthlySalary: "ماہانہ تنخواہ / Monthly Salary",
    totalExpected: "کل متوقع / Total Expected",
    workingDays: "کام کے دن / Working Days",
    totalDays: "کل دن / Total Days",
    expected: "متوقع / Expected",
    paid: "ادا شدہ / Paid",
    remaining: "باقی / Remaining",
    allocatedPayments: "مقررہ ادائیگیاں (FIFO) / Allocated Payments (FIFO)",
    paymentStatus: "ادائیگی کی حیثیت / Payment Status",
    full: "مکمل / Full",
    partial: "جزوی / Partial",
    unpaid: "غیر ادا شدہ / Unpaid",
    addPayment: "ادائیگی شامل کریں / Add Payment",
    recordPayment: "ادائیگی ریکارڈ کریں / Record Payment",
    paymentAmount: "ادائیگی کی رقم / Payment Amount",
    paymentMonth: "ادائیگی کا مہینہ / Payment Month",
    paymentNotes: "ادائیگی کے نوٹس / Payment Notes",
    deletePayment: "ادائیگی حذف کریں / Delete Payment",
    deletePaymentConfirm: "کیا آپ واقعی اس ادائیگی کو حذف کرنا چاہتے ہیں؟ / Are you sure you want to delete this payment?",
    documentAdded: "دستاویز کامیابی سے شامل ہو گئی / Document added successfully",
    documentRemoved: "دستاویز کامیابی سے ہٹا دی گئی / Document removed successfully",
    failedToAddDocument: "دستاویز شامل کرنے میں ناکامی / Failed to add document",
    failedToRemoveDocument: "دستاویز ہٹانے میں ناکامی / Failed to remove document",
    paymentRecorded: "ادائیگی کامیابی سے ریکارڈ ہو گئی / Payment recorded successfully",
    failedToRecordPayment: "ادائیگی ریکارڈ کرنے میں ناکامی / Failed to record payment",
    imagesUploaded: "تصاویر کامیابی سے اپ لوڈ ہو گئیں / Images uploaded successfully",
    failedToUploadImages: "تصاویر اپ لوڈ کرنے میں ناکامی / Failed to upload images",
    imageRemoved: "تصویر کامیابی سے ہٹا دی گئی / Image removed successfully",
    failedToRemoveImage: "تصویر ہٹانے میں ناکامی / Failed to remove image",
    staffNotFound: "اسٹاف نہیں ملا / Staff not found",
    clear: "صاف کریں / Clear",
    to: "تک / to",
    earned: "کما / Earned",
    items: "آئٹمز / Items",
    paymentMethod: "ادائیگی کا طریقہ / Payment Method",
    orderNumber: "آرڈر # / Order #",
    joinDate: "شمولیت کی تاریخ / Join Date",
    salary: "تنخواہ / salary",
    personalInfo: "ذاتی معلومات / Personal Information",
    salaryInfo: "تنخواہ کی معلومات / Salary Information",
    additionalInfo: "اضافی معلومات / Additional Information",
    emergencyContact: "ایمرجنسی رابطہ / Emergency Contact",
    photo: "تصویر / Photo",
    notes: "نوٹس / Notes",
    create: "بنائیں / Create",
    edit: "ترمیم کریں / Edit",
  },
};

export const getStaffLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return staffLabels[langKey] || staffLabels.en;
};
