export const userLabels = {
  en: {
    // Page titles
    userManagement: "User Management",
    manageStaffUserAccounts: "Manage staff and user accounts",
    addUser: "Add User",
    addStaff: "Add Staff",
    createUserAccount: "Create User Account",
    
    // Form labels
    name: "Name",
    email: "Email",
    phone: "Phone",
    role: "Role",
    password: "Password",
    confirmPassword: "Confirm Password",
    permissions: "Permissions",
    activeAccount: "Active Account",
    
    // Roles
    staff: "Staff",
    manager: "Manager",
    admin: "Admin",
    
    // Permission labels
    dashboard: "Dashboard",
    pos: "Sale Page",
    products: "Products",
    purchases: "Purchases",
    expenses: "Expenses",
    reports: "Reports",
    accounts: "Accounts",
    staff: "Staff Page",
    manageUsers: "Manage Users",
    settings: "Settings",
    ordersPage: "Sales History Page",
    deleteOrders: "Delete Orders",
    editOrders: "Edit Orders",
    menuItems: "Menu Manager Page",
    menuItemsEdit: "Edit Menu Items",
    menuItemsDelete: "Delete Menu Items",
    foodExpenses: "Food Expenses",
    foodExpensesEdit: "Edit Food Expenses",
    foodExpensesDelete: "Delete Food Expenses",
    otherExpenses: "Other Expenses",
    otherExpensesEdit: "Edit Other Expenses",
    otherExpensesDelete: "Delete Other Expenses",
    staff: "Staff Page",
    staffEdit: "Edit Staff",
    staffDelete: "Delete Staff",
    staffOrdersEdit: "Edit Staff Orders",
    staffOrdersDelete: "Delete Staff Orders",
    staffExpenses: "Staff Expenses",
    staffExpensesEdit: "Edit Staff Expenses",
    staffExpensesDelete: "Delete Staff Expenses",
    staffSalaries: "Staff Salaries",
    staffSalariesEdit: "Edit Salaries",
    staffSalariesDelete: "Delete Salaries",
    qarza: "Business Qarza",
    qarzaEdit: "Edit Business Qarza",
    qarzaDelete: "Delete Business Qarza",
    personalQarza: "Personal Qarza",
    personalQarzaEdit: "Edit Personal Qarza",
    personalQarzaDelete: "Delete Personal Qarza",
    hostelPos: "Hostel Sale Page",
    hostelOrders: "Hostel Sales History",
    hostelOrdersEdit: "Edit Hostel Orders",
    hostelOrdersDelete: "Delete Hostel Orders",
    hostelQarza: "Hostel Qarza",
    hostelQarzaEdit: "Edit Hostel Qarza",
    hostelQarzaDelete: "Delete Hostel Qarza",
    gymPos: "Gym Sale Page",
    gymOrders: "Gym Sales History",
    gymOrdersEdit: "Edit Gym Orders",
    gymOrdersDelete: "Delete Gym Orders",
    gymQarza: "Gym Qarza",
    gymQarzaEdit: "Edit Gym Qarza",
    gymQarzaDelete: "Delete Gym Qarza",
    
    // Buttons
    create: "Create",
    update: "Update",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    
    // Messages
    loading: "Loading...",
    noUsersFound: "No Users found.",
    userCreated: "User created successfully",
    userUpdated: "User updated successfully",
    userDeleted: "User deleted successfully",
    passwordsDoNotMatch: "Passwords do not match",
    operationFailed: "Operation failed",
    deleteFailed: "Delete failed",
    saveFailed: "Save failed",
    deleteConfirm: "Delete this user?",
    leaveBlank: "(leave blank)",
    
    // Status
    disabled: "Disabled",
    
    // Search
    searchUsers: "Search users...",
    
    // Other
    noPhone: "No phone",
  },
  ur: {
    // Page titles
    userManagement: "صارف مینجمنٹ",
    manageStaffUserAccounts: "سٹاف اور صارف اکاؤنٹس کا انتظام کریں",
    addUser: "صارف شامل کریں",
    addStaff: "سٹاف شامل کریں",
    createUserAccount: "صارف اکاؤنٹ بنائیں",
    
    // Form labels
    name: "نام",
    email: "ای میل",
    phone: "فون",
    role: "کردار",
    password: "پاسورڈ",
    confirmPassword: "پاسورڈ کی تصدیق کریں",
    permissions: "اجازتیں",
    activeAccount: "فعال اکاؤنٹ",
    
    // Roles
    staff: "سٹاف",
    manager: "منیجر",
    admin: "ایڈمن",
    
    // Permission labels
    dashboard: "ڈیش بورڈ",
    pos: "سیلز صفحہ",
    products: "پروڈکٹس",
    purchases: "خریداری",
    expenses: "خرچے",
    reports: "رپورٹس",
    accounts: "اکاؤنٹس",
    staff: "سٹاف صفحہ",
    manageUsers: "صارفین کا انتظام",
    settings: "ترتیبات",
    ordersPage: "فروخت کے ریکارڈ کا صفحہ",
    deleteOrders: "آرڈرز حذف کریں",
    editOrders: "آرڈرز میں ترمیم کریں",
    menuItems: "مینو آئٹمز مینیجر صفحہ",
    menuItemsEdit: "مینو آئٹمز میں ترمیم کریں",
    menuItemsDelete: "مینو آئٹمز حذف کریں",
    foodExpenses: "خوراک کے اخراجات",
    foodExpensesEdit: "خوراک کے اخراجات میں ترمیم",
    foodExpensesDelete: "خوراک کے اخراجات حذف کریں",
    otherExpenses: "دیگر اخراجات",
    otherExpensesEdit: "دیگر اخراجات میں ترمیم",
    otherExpensesDelete: "دیگر اخراجات حذف کریں",
    staff: "سٹاف صفحہ",
    staffEdit: "سٹاف میں ترمیم کریں",
    staffDelete: "سٹاف حذف کریں",
    staffOrdersEdit: "سٹاف آرڈرز میں ترمیم کریں",
    staffOrdersDelete: "سٹاف آرڈرز حذف کریں",
    staffExpenses: "سٹاف اخراجات",
    staffExpensesEdit: "سٹاف اخراجات میں ترمیم",
    staffExpensesDelete: "سٹاف اخراجات حذف کریں",
    staffSalaries: "سٹاف تنخواہیں",
    staffSalariesEdit: "تنخواہوں میں ترمیم کریں",
    staffSalariesDelete: "تنخواہیں حذف کریں",
    qarza: "کاروباری قرضہ",
    qarzaEdit: "کاروباری قرضہ میں ترمیم",
    qarzaDelete: "کاروباری قرضہ حذف کریں",
    personalQarza: "ذاتی قرضہ",
    personalQarzaEdit: "ذاتی قرضہ میں ترمیم",
    personalQarzaDelete: "ذاتی قرضہ حذف کریں",
    hostelPos: "ہاسٹل سیلز صفحہ",
    hostelOrders: "ہاسٹل آرڈرز کا ریکارڈ",
    hostelOrdersEdit: "ہاسٹل آرڈرز میں ترمیم کریں",
    hostelOrdersDelete: "ہاسٹل آرڈرز حذف کریں",
    hostelQarza: "ہاسٹل قرضہ",
    hostelQarzaEdit: "ہاسٹل قرضہ میں ترمیم",
    hostelQarzaDelete: "ہاسٹل قرضہ حذف کریں",
    gymPos: "جم سیلز صفحہ",
    gymOrders: "جم آرڈرز کا ریکارڈ",
    gymOrdersEdit: "جم آرڈرز میں ترمیم کریں",
    gymOrdersDelete: "جم آرڈرز حذف کریں",
    gymQarza: "جم قرضہ",
    gymQarzaEdit: "جم قرضہ میں ترمیم",
    gymQarzaDelete: "جم قرضہ حذف کریں",
    
    // Buttons
    create: "بنائیں",
    update: "اپڈیٹ",
    edit: "ترمیم کریں",
    delete: "حذف کریں",
    cancel: "منسوخ کریں",
    save: "محفوظ کریں",
    close: "بند کریں",
    
    // Messages
    loading: "لوڈ ہو رہا ہے...",
    noUsersFound: "کوئی صارف نہیں ملا۔",
    userCreated: "صارف کامیابی سے بنایا گیا",
    userUpdated: "صارف کامیابی سے اپڈیٹ ہو گیا",
    userDeleted: "صارف کامیابی سے حذف ہو گیا",
    passwordsDoNotMatch: "پاسورڈز مماثل نہیں ہیں",
    operationFailed: "ناکام",
    deleteFailed: "حذف ناکام",
    saveFailed: "محفوظ کرنا ناکام",
    deleteConfirm: "کیا آپ واقعی اس صارف کو حذف کرنا چاہتے ہیں؟",
    leaveBlank: "(خالی چھوڑیں)",
    
    // Status
    disabled: "غیر فعال",
    
    // Search
    searchUsers: "...صارف تلاش کریں",
    
    // Other
    noPhone: "فون نہیں",
  },
  ur_en: {
    // Page titles
    userManagement: "صارف مینجمنٹ / User Management",
    manageStaffUserAccounts: "سٹاف اور صارف اکاؤنٹس کا انتظام کریں / Manage staff and user accounts",
    addUser: "صارف شامل کریں / Add User",
    addStaff: "سٹاف شامل کریں / Add Staff",
    createUserAccount: "صارف اکاؤنٹ بنائیں / Create User Account",
    
    // Form labels
    name: "نام / Name",
    email: "ای میل / Email",
    phone: "فون / Phone",
    role: "کردار / Role",
    password: "پاسورڈ / Password",
    confirmPassword: "پاسورڈ کی تصدیق کریں / Confirm Password",
    permissions: "اجازتیں / Permissions",
    activeAccount: "فعال اکاؤنٹ / Active Account",
    
    // Roles
    staff: "سٹاف / Staff",
    manager: "منیجر / Manager",
    admin: "ایڈمن / Admin",
    
    // Permission labels
    dashboard: "ڈیش بورڈ / Dashboard",
    pos: "سیلز صفحہ / Sale Page",
    ordersPage: "فروخت کے ریکارڈ کا صفحہ / Sales History Page",
    deleteOrders: "آرڈرز حذف کریں / Delete Orders",
    editOrders: "آرڈرز میں ترمیم کریں / Edit Orders",
    menuItems: "مینو آئٹمز مینیجر صفحہ / Menu Manager Page",
    menuItemsEdit: "مینو آئٹمز میں ترمیم کریں / Edit Menu Items",
    menuItemsDelete: "مینو آئٹمز حذف کریں / Delete Menu Items",
    foodExpenses: "خوراک کے اخراجات / Food Expenses",
    foodExpensesEdit: "خوراک کے اخراجات میں ترمیم / Edit Food Expenses",
    foodExpensesDelete: "خوراک کے اخراجات حذف کریں / Delete Food Expenses",
    otherExpenses: "دیگر اخراجات / Other Expenses",
    otherExpensesEdit: "دیگر اخراجات میں ترمیم / Edit Other Expenses",
    otherExpensesDelete: "دیگر اخراجات حذف کریں / Delete Other Expenses",
    staff: "سٹاف صفحہ / Staff Page",
    staffEdit: "سٹاف میں ترمیم کریں / Edit Staff",
    staffDelete: "سٹاف حذف کریں / Delete Staff",
    staffOrdersEdit: "سٹاف آرڈرز میں ترمیم کریں / Edit Staff Orders",
    staffOrdersDelete: "سٹاف آرڈرز حذف کریں / Delete Staff Orders",
    staffExpenses: "سٹاف اخراجات / Staff Expenses",
    staffExpensesEdit: "سٹاف اخراجات میں ترمیم / Edit Staff Expenses",
    staffExpensesDelete: "سٹاف اخراجات حذف کریں / Delete Staff Expenses",
    staffSalaries: "سٹاف تنخواہیں / Staff Salaries",
    staffSalariesEdit: "تنخواہوں میں ترمیم کریں / Edit Salaries",
    staffSalariesDelete: "تنخواہیں حذف کریں / Delete Salaries",
    qarza: "کاروباری قرضہ / Business Qarza",
    qarzaEdit: "کاروباری قرضہ میں ترمیم / Edit Business Qarza",
    qarzaDelete: "کاروباری قرضہ حذف کریں / Delete Business Qarza",
    personalQarza: "ذاتی قرضہ / Personal Qarza",
    personalQarzaEdit: "ذاتی قرضہ میں ترمیم / Edit Personal Qarza",
    personalQarzaDelete: "ذاتی قرضہ حذف کریں / Delete Personal Qarza",
    hostelPos: "ہاسٹل سیلز صفحہ / Hostel Sale Page",
    hostelOrders: "ہاسٹل آرڈرز کا ریکارڈ / Hostel Sales History",
    hostelOrdersEdit: "ہاسٹل آرڈرز میں ترمیم کریں / Edit Hostel Orders",
    hostelOrdersDelete: "ہاسٹل آرڈرز حذف کریں / Delete Hostel Orders",
    hostelQarza: "ہاسٹل قرضہ / Hostel Qarza",
    hostelQarzaEdit: "ہاسٹل قرضہ میں ترمیم / Edit Hostel Qarza",
    hostelQarzaDelete: "ہاسٹل قرضہ حذف کریں / Delete Hostel Qarza",
    gymPos: "جم سیلز صفحہ / Gym Sale Page",
    gymOrders: "جم آرڈرز کا ریکارڈ / Gym Sales History",
    gymOrdersEdit: "جم آرڈرز میں ترمیم کریں / Edit Gym Orders",
    gymOrdersDelete: "جم آرڈرز حذف کریں / Delete Gym Orders",
    gymQarza: "جم قرضہ / Gym Qarza",
    gymQarzaEdit: "جم قرضہ میں ترمیم / Edit Gym Qarza",
    gymQarzaDelete: "جم قرضہ حذف کریں / Delete Gym Qarza",
    
    // Buttons
    create: "بنائیں / Create",
    update: "اپڈیٹ / Update",
    edit: "ترمیم کریں / Edit",
    delete: "حذف کریں / Delete",
    cancel: "منسوخ کریں / Cancel",
    save: "محفوظ کریں / Save",
    close: "بند کریں / Close",
    
    // Messages
    loading: "لوڈ ہو رہا ہے / Loading...",
    noUsersFound: "کوئی صارف نہیں ملا۔ / No Users found.",
    userCreated: "صارف کامیابی سے بنایا گیا / User created successfully",
    userUpdated: "صارف کامیابی سے اپڈیٹ ہو گیا / User updated successfully",
    userDeleted: "صارف کامیابی سے حذف ہو گیا / User deleted successfully",
    passwordsDoNotMatch: "پاسورڈز مماثل نہیں ہیں / Passwords do not match",
    operationFailed: "ناکام / Operation failed",
    deleteFailed: "حذف ناکام / Delete failed",
    saveFailed: "محفوظ کرنا ناکام / Save failed",
    deleteConfirm: "کیا آپ واقعی اس صارف کو حذف کرنا چاہتے ہیں؟ / Delete this user?",
    leaveBlank: "(خالی چھوڑیں) / (leave blank)",
    
    // Status
    disabled: "غیر فعال / Disabled",
    
    // Search
    searchUsers: "...صارف تلاش کریں / Search users...",
    
    // Other
    noPhone: "فون نہیں / No phone",
  },
};

export const getUserLabels = (language) => {
  const langKey = language === "ur_en" ? "ur_en" : language === "ur" ? "ur" : "en";
  return userLabels[langKey] || userLabels.en;
};
